docs/_scripts/build_docs/index.ts, docs/_scripts/build_docs/render_document.ts, docs/_scripts/build_docs/run_code.ts, package.json, packages/malloy-db-bigquery/package.json, packages/malloy-db-postgres/package.json, packages/malloy-db-test/package.json, packages/malloy-db-test/src/expr.spec.ts, packages/malloy-db-test/src/join.spec.ts, packages/malloy-db-test/src/malloy_query.spec.ts, packages/malloy-db-test/src/production-models.spec.ts, packages/malloy-render/package.json, packages/malloy-vscode/package.json, packages/malloy-vscode/src/extension/commands/run_query_utils.ts, packages/malloy-vscode/src/extension/extension.ts, packages/malloy-vscode/src/server/diagnostics/diagnostics.ts, scripts/third_party_licenses.ts
Remove "malloy-" from packages, as it's implied with the organizational scope `@malloy-lang/`. This should make it simpler to import. Following [babel](https://github.com/babel/babel/tree/main/packages) conventions (package folder is `babel-x`, package name is `@babel/x`.
=> shorten package names for simpler imports

README.md, cloudbuild/README.md, cloudbuild/build-test/build-test.sh, cloudbuild/build-test/cloudbuild.yaml, default.nix
cloudbuild: infra for running tests, config checked in
nix: environment for furnishing required binaries for ci build (e.g. jvm, node, yarn, etc.)
--
Flow:
* cloudbuild trigger picks up PR
* docker image with nix is started
* `build_run.sh` script is run
* `yarn install`, etc. is run in nix (specifically in `nix-shell`) context
* build status is reported back to PRs
--
For contributors, CI will automatically run. For non-contributor submitted PRs, contributors must comment `/gcbrun` to kick off the build. Once we decide we like cloudbuild, we'll change an admin setting to block mering of PRs unless cloudbuild passes.
--
Future directions:
* support for postgresql tests
* migrate to a different GCP project
* building a docker image based on `nixos/nix` which has packages pre-downloaded for …
=> Cloudbuild and Nix

packages/malloy-db-test/src/handexpr.spec.ts, packages/malloy-db-test/src/orderby.spec.ts, packages/malloy-vscode/src/server/highlights/highlights.ts, packages/malloy-vscode/src/server/lenses/lenses.ts, packages/malloy-vscode/src/server/symbols/symbols.ts, packages/malloy/src/index.ts, packages/malloy/src/malloy.ts, packages/malloy/src/runtime_types.ts
This PR removed the `Runner` and `Compiler` classes, as they didn't feel like the right abstraction — all they really did was encapsulate some state (the `urlReader`, `lookupSQLRunner`, and `lookupSchemaReader`), and the `Compiler` did two logical steps, _parse_, and _compile_, because that's how it's implemented under the hood.
We think it makes more sense to think of `parse` and `compile` as two steps. 
The functions `parse`, `compile, and `run` have been added as static methods on the `Malloy` class for now. They may move elsewhere.
The logical flow for running a query using the underlying API is now:
```ts
const parse = Malloy.parse(file.text, file.url);
const queryModel = await Malloy.compile(urlReader, lookupSchemaReader, parse);
const query = queryModel.getPreparedQuery();
const …
```
=> `Malloy.parse`, `.run`, and `.compile` instead of `Runner` and `Compiler`

packages/malloy/src/model/malloy_query.ts
Use the primary key as an field expression instead of generating a new intrinic field.  This should be much more reliable.
=> Better implementation

packages/malloy-render/src/html/html_view.ts, packages/malloy-render/src/index.ts, packages/malloy-vscode/src/extension/commands/run_named_query.ts, packages/malloy-vscode/src/extension/commands/run_query.ts, packages/malloy-vscode/src/extension/commands/run_query_utils.ts, packages/malloy-vscode/src/server/lenses/lenses.ts
Experimental, but I think we should just have two lenses over queries Run and Render.   Since we are a data tool, the Run button should show the raw data.  The Render button passes these results to the renderer.  I think this will make Malloy more comprehensible.
=> Change the Run buttons to Run | Render

packages/malloy-vscode/src/extension/commands/run_query_utils.ts
Simple change to open an new panel for run vs render (don't reuse the same one)
=> Make a new panel when querying for data.

packages/malloy-render/src/html/dashboard.ts, packages/malloy-render/src/html/list.ts, packages/malloy-render/src/html/table.ts, packages/malloy-render/src/html/utils.ts, packages/malloy-vscode/package.json, packages/malloy-vscode/src/extension/commands/run_named_query.ts, packages/malloy-vscode/src/extension/commands/run_query.ts, packages/malloy-vscode/src/extension/commands/run_query_utils.ts, packages/malloy-vscode/src/extension/state.ts, packages/malloy-vscode/src/extension/webview_message_manager.ts, packages/malloy-vscode/src/extension/webviews/components/Spinner/Spinner.tsx, packages/malloy-vscode/src/extension/webviews/components/Spinner/index.ts, packages/malloy-vscode/src/extension/webviews/components/Spinner/spinner.svg, packages/malloy-vscode/src/extension/webviews/components/index.ts, packages/malloy-vscode/src/extension/webviews/index.ts, packages/malloy-vscode/src/extension/webviews/query_page/App.tsx, packages/malloy-vscode/src/extension/webviews/query_page/entry.ts, packages/malloy-vscode/src/extension/webviews/webview_html.ts, packages/malloy-vscode/tsconfig.json, packages/malloy-vscode/webpack.config.js, packages/malloy/src/index.ts, packages/malloy/src/malloy.ts, postgres_test/dump_malloytest.sh, yarn.lock
Add the plumbing to put arbitrary React interactiveness into the query result webview. 
For now, the way the webview behaves does not visibly change much, but it will be possible to add interactive features.
This PR also adds `setTimeout`s into the `render` methods of collection renderers between the rendering of each cell. This makes the overall render span multiple JS tasks, allowing other tasks, e.g. React rendering, to occur during a "slow" render. This dramatically improves the responsiveness of an app that uses the rendering library.
=> Put React into the query result WebView

packages/malloy/src/lang/field-space.ts
@mtoy-googly-moogly fixed an issue where no fields would show up when a query was refined, e.g.
```
query: flights -> airport_dashboard {? origin.code: 'SJC' }
```
However, if the query contained any field definitions rather than field references, the resulting query would not correctly re-define those fields. 
This PR should fix that.
Two sample models (`iowa.malloy` and `flights_beta.malloy`) are now compiling again with this change.
=> Fix refined queries which contain field expressions

packages/malloy/src/lang/ast/ast-main.ts
Fixes an issue where the `filterList` of a query is mutated incorrectly.
Minimal example:
```
explore: base is table('malloy-data.faa.flights') {
query: base_query is {
where: true
group_by: one is 1
}
}
explore: extended is base {
query: extended_query is {
nest: base_query
nest: no_data is base_query {? false }
}
}
```
Running `extended_query` should yield:
```
[
{
"base_query": [
{
"one": 1
}
],
"no_data": []
}
]
```
But instead it yielded:
```
[
{
"base_query": [],
"no_data": []
}
]
```
Because `base_query`'s `filterList` was mutated to include the `false` filter. 
The fix just copies the `filterList` array when creating the new query.
=> Fix issue where filterList is mutated incorrectly

packages/malloy/src/lang/grammar/Malloy.g4
Allow spaces between property names and colons:
```
query: by_carrier is {
group_by  : carriers.nickname
aggregate : flight_count
aggregate : destination_count is destination.count()
}
```
=> Allow spaces between property names and colons

docs/_scripts/build_docs/render_document.ts, docs/_scripts/build_docs/run_code.ts, docs/_src/language/basic.md
Allows model files to be defined inline in a doc.
To define a model in queries appearing _later in the document_, use snippet parameters `isModel` with value `true` and `modelPath` with a path (rooted at the sample model directory). This defines a virtual file at that path for later snippets to use. 
````md
```malloy
--! {"isModel": true, "modelPath": "/inline/airports_mini.malloy"}
explore: airports is table('malloy-data.faa.airports'){
dimension: county_and_state is concat(county, ', ', state)
measure: airport_count is count()
measure: average_elevation is avg(elevation)
}
```
```malloy
--! {"isRunnable": true, "runMode": "auto", "isPaginationEnabled": true, "source": "/inline/airports_mini.malloy"}
query: airports->{
group_by:county_and_state
aggregate: airport_count
}
```
````
Note …
=> Allow inline models in docs

packages/malloy/src/malloy.ts
* Fix The `day` truncation to yield a `DataDate` not a `DataNumber`, e.g. 
```malloy
query: flights -> {
group_by: flight_date is dep_time.day
top: 5
aggregate: flight_count
}
```
Previously `day` truncation (timeframe "day") was treated like `day` extraction (timeframe "day_of_month"), which does yield a `DataNumber`.
=> "day" timeframe is date, not number

docs/_src/examples/wordle/wordle1a.md, docs/_src/examples/wordle/wordle2.md, docs/_src/examples/wordle/wordle215.md, docs/_src/examples/wordle/wordle217.md, docs/_src/examples/wordle/wordle4.md, packages/malloy-db-test/src/nomodel.spec.ts, packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/beta.spec.ts, packages/malloy/src/lang/field-space.ts, packages/malloy/src/lang/grammar/Malloy.g4, packages/malloy/src/lang/parse-to-ast.ts, packages/malloy/src/lang/parse-tree-walkers/document-highlight-walker.ts, packages/malloy/src/model/malloy_types.ts, samples/wordle/wordlebot.malloy
Currently just the parser work for this.
Need malloy_query work to  finish, a join of `type: "crossJoin"` now will have a optional `onExpression:`
=> Add join_cross: with optional ON

packages/malloy-vscode/package.json
Fixes https://github.com/looker-open-source/malloy/issues/239
This change makes the Malloy extension activate when VSCode starts up, rather than at specific activation points. This has the downside that users who have the Malloy extension installed will _always_ have the Malloy extension activated, instead of having it activated only when they use Malloy-specific features. But this is less likely for us to accidentally run into issues like https://github.com/looker-open-source/malloy/issues/238 in the future. For now, we make `"*"` an activation event. Later, we can use specific activation events instead.
=> Activate VSCode extension on startup

packages/malloy-db-postgres/src/postgres_connection.ts
We were missing a bunch of postgres types.  We need to introduce an 'opaque' type but we are using 'string' for now.
=> add missing postgres types

packages/malloy-vscode/package.json
In https://github.com/looker-open-source/malloy/pull/241, we made the extension activate on VSCode startup in order to quickly fix issues with the Edit Connections command not being available when the button is clicked. This is bad practice, and causes VSCode startup to be slow. 
In this PR, we instead flesh out the list of activation events, so that any time Malloy-related things happen, the extension activates.
Fixes https://github.com/looker-open-source/malloy/issues/245
=> Use real activation events, rather than * (startup)

packages/malloy-vscode/src/server/server.ts
Fixes https://github.com/looker-open-source/malloy/issues/254
Apparently the call to `connection.client.register(DidChangeConfigurationNotification.type, ...)` was not necessary.
=> Remove unnecessary capability registration from server

packages/malloy-vscode/src/extension/commands/edit_connections.ts
Fixes https://github.com/looker-open-source/malloy/issues/256
In the future we can give the user more options here. But for now, this is the least likely to cause problems. When you click "Save" in the connections editor:
* If `malloy.connections` is unset, or is only set in user config, user config is updated
* If `malloy.connections` is set in workspace config, both user config and workspace config are updated
=> When saving connections, update workspace config only if already set. Always update user config.

packages/malloy-vscode/src/server/server.ts
Fixes https://github.com/looker-open-source/malloy/issues/272
This solves a race condition where an old version of a document finishes validating after a new version, and so overrides the diagnostics for the newest version with those of the older version.
=> Language server: do not send diagnostics for old document versions

docs/_scripts/build_docs/run_code.ts, packages/malloy-vscode/src/extension/commands/run_named_query.ts, packages/malloy-vscode/src/extension/commands/run_query.ts, packages/malloy-vscode/src/extension/commands/run_query_file.ts, packages/malloy-vscode/src/extension/commands/run_query_utils.ts, packages/malloy-vscode/src/extension/webview_message_manager.ts, packages/malloy-vscode/src/extension/webviews/connections_page/App.tsx, packages/malloy-vscode/src/extension/webviews/query_page/App.tsx, packages/malloy-vscode/src/extension/webviews/query_page/ResultKindToggle.tsx, packages/malloy-vscode/src/extension/webviews/webview_html.ts, packages/malloy-vscode/src/server/lenses/lenses.ts
Removes the "Render" code lens, and instead add HTML / SQL / JSON toggles in the webview. Defaults to HTML. SQL and JSON are currently highlighted the same way as in the docs, and does not respect the user's VSCode theme. This is because theme colors aren't passed into the webview nicely. See [here](https://stackoverflow.com/questions/55877879/vs-code-webview-css-variable-names-for-used-theme-tokencolors) and [here](https://github.com/Microsoft/vscode/issues/56356). A possible solution is to use [shiki](https://shiki.matsu.io/) which can highlight according to TextMate themes.
Closes https://github.com/looker-open-source/malloy/issues/273
=> Show HTML/SQL/JSON tabs in query result panel

packages/malloy-vscode/src/extension/webviews/query_page/App.tsx
Temporarily remove syntax highlighting for JSON results, since large results can take awhile to display. When we have virtualization, we can add this back.
=> Use lighter-weight rendering for JSON results for now

README.md, docs/_src/connection_instructions.md, docs/_src/table_of_contents.json
I made a dedicated connection instructions page, and then removed them from the readme. Also moved to a list instead of separate headers for Install instructions to streamline the readme. 
I also renamed a couple headers in the docs and added connection instructions under "Getting Started" - open ot moving this or adding an admin/VSCode Plugin section.
=> new connection instructions page and shortened readme

packages/malloy/src/lang/ast/ast-main.ts
Fixes #310
At least I think it should. I have zero ability to write tests for things like field order in lang/ write now.
=> keep old fields first when refining a query

docs/_scripts/build_docs/run_code.ts, package.json, packages/malloy-render/src/html/bar_chart.ts, packages/malloy-render/src/html/chart.ts, packages/malloy-render/src/html/container.ts, packages/malloy-render/src/html/dashboard.ts, packages/malloy-render/src/html/date.ts, packages/malloy-render/src/html/html_view.ts, packages/malloy-render/src/html/image.ts, packages/malloy-render/src/html/json.ts, packages/malloy-render/src/html/link.ts, packages/malloy-render/src/html/list.ts, packages/malloy-render/src/html/table.ts, packages/malloy-render/src/html/text.ts, packages/malloy-render/src/html/utils.ts, packages/malloy-render/src/html/vega_spec.ts, packages/malloy-render/src/renderer.ts, packages/malloy-vscode/src/extension/webviews/query_page/App.tsx, yarn.lock
Benefits:
* Easier to add event listeners to DOM elements than to render the string HTML into a DOM and then add event listeners afterwards
* Comparable rendering speed (in my tests, this was 1% slower on average, but I didn't do enough tests to determine whether that's actually a significant 1% or just normal variance)
* Near instantaneous display speeds
* Allows for safer rendering, using `document.createTextNode` instead of unsanitized HTML strings
The only noticeable effect of this PR should be that the "Displaying" spinner should be much faster (nearly instantaneous).
=> Render DOM elements, not strings

packages/malloy/src/lang/grammar/build-parser.sh
Fixes the following issue on Linux systems, which use `md5sum` instead of `md5`:
```
[nix-shell:~/Development/malloy]$ yarn build
yarn run v1.22.17
$ yarn workspace @malloydata/malloy build-parser && yarn tsc --build
$ (cd src/lang/grammar ; sh build-parser.sh)
build-parser.sh: line 23: md5: command not found
```
=> md5 or md5sum based on OS

packages/malloy/src/lang/grammar/build-parser.sh
Before this patch, as long as the last command in the file succeeded, build-parser.sh would exit with a zero status code. With this change, the script will exit immediately with a non-zero status code if any constituent line fails.
---
Before fix:
```
[nix-shell:~/Development/malloy]$ yarn build
yarn run v1.22.17
$ yarn workspace @malloydata/malloy build-parser && yarn tsc --build
$ (cd src/lang/grammar ; sh build-parser.sh)
build-parser.sh: line 23: md5: command not found
ANTLR parser ../lib/Malloy/MalloyParser.ts is up to date
$ /usr/local/google/home/aryehh/Development/malloy/node_modules/.bin/tsc --build
Done in 0.88s.
[nix-shell:~/Development/malloy]$ echo $?
0
```
After fix:
```
% sh ./packages/malloy/src/lang/grammar/build-parser.sh …
```
=> Exit build-parser.sh Upon Failure

packages/malloy-vscode/src/extension/commands/edit_connections.ts, packages/malloy-vscode/src/extension/commands/run_query_utils.ts, packages/malloy-vscode/src/extension/webview_views/help_view.ts, packages/malloy-vscode/src/extension/webviews/webview_html.ts
Adds the following CSP directives to all webviews in the VSCode extension:
* `default-src 'none'`
Makes all of [child-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src), [connect-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src), [font-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/font-src), [frame-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src), [img-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src), [manifest-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/manifest-src), …
=> Add a strict CSP to webviews

docs/_scripts/build_docs/run_code.ts, packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy-vscode/src/common/connection_manager.ts, packages/malloy-vscode/src/extension/commands/run_query_utils.ts, packages/malloy/src/connection.ts, packages/malloy/src/malloy.ts, packages/malloy/src/runtime_types.ts
This makes the `Connection` interface require that `runSQL` can take an optional second parameter of type `{ rowLimit?: number }`. The implication here is that all Malloy connections must allow for `rowLimit` to be provided.
This also makes the VSCode extension respect any limit on the last stage of a pipeline when running queries. E.g. `query: flights -> { project: * }` will still use whatever `rowLimit` is set in the user/workspace configuration, but `query: flights -> { project: *; limit: 1000 }` will use a page size of 100. The thinking here is that it's less surprising to users, so when they run a query with a high limit, they actually get what they asked for. 
Fixes https://github.com/looker-open-source/malloy/issues/290
=> Make `rowLimit` a standard connection option, and use it if a query has a limit

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy/src/connection.ts, packages/malloy/src/index.ts, packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/grammar/Malloy.g4, packages/malloy/src/lang/index.ts, packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/parse-to-ast.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, packages/malloy/src/model/sql_block.ts, packages/malloy/src/runtime_types.ts
This is a lot of renames, so it touches a lot of files. Formalizes the use of SQL and refactors a bit to aim at a future where SQL blocks have sections.
An `SQLBLock` is ...
```
/**
* Use factory makeSQLBlock to create one of these, it will compute the
* name: property and fill it in.
*/
export interface SQLBlock extends AliasedName {
type: "sqlBlock";
name: string; //  hash of the connection and the select
before?: string[];
select: string;
after?: string[];
connection?: string;
}
```
and the list of all `sql:` statements from a translator run are available in the `sqlBlocks:` property of the translation ...
AND ...
The translator, for defs which are used as explores (structs) ... there is an `sqlStructs:` response which asks for a structdef for the SQLBlocks which are used in explores. …
=> Refactor SQL definitions to use SQLBlock interface

packages/malloy-vscode/src/extension/webviews/webview_html.ts
Vega uses `eval`: https://github.com/vega/vega/issues/1106
=> Allow `unsafe-eval` for now, because vega uses it

packages/malloy/src/lang/parse-malloy.ts
Fixes an issue where if an empty string is passed to the translator as the source for a URL, then the translator asks for that URL again, due to a bad check (`!thing` vs `thing === undefined`).
=> Fix infinite loop when source file is empty string

packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/test/parse.spec.ts
Fixes #358
... and many other errors which were waiting for us once we started writing more complex models.
* Error on a query which has no fields (and so can't deduce the type)
* Deduction uses item being refined as the starting guess instead of undefined
* Errors if a refinement attempts to change the query type
* Deduction smarter and more correct.
=> better heuristic for query type

docs/_src/examples/ga_sessions.md, packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/postgres.ts, packages/malloy/src/dialect/standardsql.ts, packages/malloy/src/lang/ast/ast-time-expr.ts, packages/malloy/src/lang/test/parse.spec.ts, samples/ga_sessions/ga_sessions.malloy, samples/hackernews/hackernews.malloy
Fixes #106 
Only it will never really fix it. It will only be fixed when do do not allow any pass through function calls, and there is a set of Malloy functions which are documented, and each one generates SQL.
=> Better typing of results of function calls in expressions

docs/_src/language/join.md, packages/malloy-db-test/src/handexpr.spec.ts, packages/malloy-db-test/src/join.spec.ts, packages/malloy-db-test/src/models/faa_model.ts, packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/field-space.ts, packages/malloy/src/lang/grammar/Malloy.g4, packages/malloy/src/lang/parse-to-ast.ts, packages/malloy/src/lang/test/field-symbols.spec.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts
Fixes #347
Once upon a time we had plans to allow reversed foreign key join with something like
```
source: users {
join_many: orders with orders.user_id
```
And automatically generate a join into the primary key of users.
Only we never implemented that, and in the grammar a `with` clause could ONLY be a field name with no dots.
---
With this PR the `with` clause takes any expression, and always joins based on the primary key of the source being join in. This will allow any expression based on the outer source to be used as a foreign key for joining the new source, including, as mentioned in #347 _exisitingJoinName.fieldName_
=> Allow expressions in join: ... with 

packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/field-space.ts, packages/malloy/src/lang/grammar/Malloy.g4, packages/malloy/src/lang/parse-to-ast.ts, packages/malloy/src/lang/test/parse.spec.ts
Fixes #413
Very common pattern, a useful nested query is embedded in another query, with a small refinement ... as in
```
query: dashboard is {
nest: by_color { limit: 5 }
nest: by_size { limit: 5 }
}
```
=> allow a nest reference to include a refinement

packages/malloy/src/lang/ast/ast-expr.ts, packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/field-space.ts, packages/malloy/src/lang/field-utils.ts, packages/malloy/src/lang/grammar/Malloy.g4, packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/space-field.ts, packages/malloy/src/lang/test/field-symbols.spec.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts
=> Allow query operations to refine the input source

packages/malloy/src/lang/ast/ast-expr.ts, packages/malloy/src/lang/parse-to-ast.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts
This PR applies the same change as #442 applied to filter expressions, but to field expressions. Now, field expressions' `code` field (renamed from `source`) will match the original spacing of the source code.
=> Use original spacing for `code` of `FieldDef`s (continuation of #442)

packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/grammar/Malloy.g4, packages/malloy/src/lang/parse-to-ast.ts, packages/malloy/src/lang/test/parse.spec.ts
Somehow indexes never supported dotted names. With this index index syntax is now
`index:` _fieldPath_ ( `,` _fieldPath_ )* (`by` _fieldName_)?
=> allow join elements in index lists

packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/test/parse.spec.ts
This died with an exception on unknown dialect ...
```
query: x->{ project: x is y / 2 }
```
This pr prevents the exception and allows the "Unknown source 'x'" error to be reported.
=> Fix reference to unknown source in query

packages/malloy/src/model/malloy_query.ts
Query in the linked issue is now:
```sql
SELECT 
SUM(product_0.productRevenue) as total_productRevenue
FROM `bigquery-public-data.google_analytics_sample.ga_sessions_20170801` as ga_sessions
LEFT JOIN UNNEST(ga_sessions.hits) as hits_0
LEFT JOIN UNNEST(hits_0.product) as product_0
ORDER BY 1 desc
```
Other left join lines like 1923 and 1936 in this same file don't start with `\n`, so makes sense that this one wouldn't either.
=> Remove extra new line in unnest join, closes #401

packages/malloy-db-test/src/postgres.spec.ts, packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/postgres.ts, packages/malloy/src/dialect/standardsql.ts, packages/malloy/src/model/malloy_query.ts
Closes https://github.com/looker-open-source/malloy/issues/495
`packages/malloy-db-test/src/postgres.spec.ts` isn't quite set up to easily make and drop schemas and tables, but an automated test could be added eventually to mirror the manual test below:
=> Handle Postgres table paths with capitals, closes #495, closes #499

packages/malloy-db-test/src/nomodel.spec.ts, packages/malloy/src/model/malloy_query.ts
Query [from issue](https://github.com/looker-open-source/malloy/issues/469) becomes
```sql
SELECT 
users_0.state as state
FROM `malloy-data.ecomm.order_items` as order_items
LEFT JOIN `malloy-data.ecomm.users` AS users_0
ON users_0.id=order_items.user_id AND ((users_0.state='California')or((users_0.state='New York')or(users_0.state='Oregon')))
GROUP BY 1
ORDER BY 1 asc
```
An alternative would be "add parens only if `conditions` has an 'or'".
=> Parens around join filters, closes #469

packages/malloy-db-test/src/datetimes.spec.ts, packages/malloy-db-test/src/expr.spec.ts, packages/malloy-db-test/src/is-sql-eq.ts, packages/malloy-db-test/src/sql-eq.ts, packages/malloy/src/lang/ast/ast-time-expr.ts, packages/malloy/src/lang/ast/ast-types.ts, packages/malloy/src/lang/ast/time-utils.ts, packages/malloy/src/lang/test/parse.spec.ts
This is not correct yet. I have some test errors introduced by moving this into a matcher than I don't quite understand, but I am ready for a review of the overall approach.
Not 100% sure this is how we should go, but after working in a couple of different problems, I have managed to abstract out a pattern for a custom matcher which I find useful. If we like this, I'll make more tests use this instead of the way they are testing now, it makes the tests, and test failures, way easier to understand.
It has the following features
1) To use this feature you need three lines of code in your file ..
```Typescript
import "./is-sql-eq";
import { mkSqlEqWith } from "./sql-eq";
// and the inside the loop where you are iterating over the connections generating a runtime ...
// you set up some inital …
```
=> Move to a custom matcher for SQL result checking

packages/malloy/src/model/malloy_query.ts, samples/imdb/imdb.malloy
IMDB and data_access_logs were failing to index because we weren't added dependancies to the indexes.
=> Add dependancies for indexed fields

packages/malloy-render/src/html/vega_spec.ts
Potential fix for https://github.com/looker-open-source/malloy/issues/112. This disables Vega's internal sorting and allows the underlying data to dictate the sort. I think this is in general what we want but @anikaks maybe I'm not thinking of something?
Natural
total_sales_dollars 
category_class
=> Remove Vega's default sorting

packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/model/sql_block.ts
The connection name was being dropped for SQL blocks not on the default connection.
=> Preserve "on" connection in sql blocks

packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy-render/src/html/vega_spec.ts, packages/malloy/src/malloy.ts
`instanceof Array` can fail because it checks for constructor identity, but not all arrays are constructed using the same constructor, including arrays returned by the duckdb node api, so use known safe checks instead.
=> Use constructor safe type checks

packages/malloy-db-duckdb/package.json, yarn.lock
This moves us to a bleeding edge version so we get the latest patches, but I think we'll still need to manually poke the lock file periodically, it won't continuously update us.
=> Track duckdb next

.gitignore, packages/malloy-vscode/scripts/build-extension.ts, packages/malloy-vscode/src/common/connection_manager.ts, packages/malloy-vscode/src/common/duckdb_availability.ts, packages/malloy-vscode/src/extension/connection_manager.ts, packages/malloy-vscode/src/extension/webviews/connections_page/ConnectionEditor/ ConnectionEditor.tsx
We don't have node binaries for DuckDB for every machine/architecture we want to support. This change makes it possible to build the extension even if the DuckDB binary doesn't exist, by making the extension check whether it is available (through a constant which is defined during the build).
=> Make extension build succeed even if duckdb is not available

demo/malloy-demo-composer/scripts/serve.ts
Using Electron's developer tools works for `node_modules` and `src` files, but malloy packages are resolved to local paths outside of the electron app's directory. This sort of solution is [recommended](https://esbuild.github.io/api/#customizing-server-behavior) by esbuild when slightly more complex server behavior is needed.
I needed this to track down #599
=> Allow sourcemaps from packages

packages/malloy-db-postgres/src/postgres_connection.ts
I was testing malloy with postgres on localhost. I created a table with a "character(50)" column, and malloy doesn't seem to like this postgres type. I traced down to its mapping and added this new/missing mapping.
=> Add postgres type "character"

demo/malloy-demo-composer/src/core/query.ts
I was getting errors complaining about unknown field "foo is " whenever I renamed a group_by expression, turns out the quoting was capturing the `is` and not just the identifier.
=> Fix 'as' quoting

packages/malloy-vscode/scripts/build-extension.ts
Issue arose from merge conflict resolution (` vs ") to allow string interpolation of the duckdb versioning.
=> Fix issue on publish step extension on win32-x64.

packages/malloy-vscode/src/common/connection_manager.ts
Using url.pathname does not properly decode and generate valid pathing for cross-platform usage.
See https://nodejs.org/api/url.html#urlfileurltopathurl for more details.
=> Fix relative pathing in vscode extension on Windows

packages/malloy-db-test/src/handexpr.spec.ts, packages/malloy/src/lang/ast/ast-expr.ts, packages/malloy/src/lang/grammar/Malloy.g4, packages/malloy/src/lang/parse-to-ast.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts
OK ... experiment ... half implemented
The parser does NOT check the field name list against the output field name list, because it doesn't have that available at the moment it is generating the list.
Will need to fix that eventually, for now the SQL writer will throw and it will be a bad user experience to have errors there.
=> add field list to ungrouped()

demo/malloy-demo-composer/public/not_packaged.html, demo/malloy-demo-composer/scripts/package.ts, demo/malloy-demo-composer/src/electron/main.ts, scripts/third_party_licenses.ts
Enable a popup from the application menu to see licenses for software used in the app. Accessed via View -> View Open Source Licenses. Additionally:
- Include desktop app in license check script, and increase time between calls to github
- Add menu item in Help to access Malloy docs
- Dummy html page for when trying to view licenses when not packaged
- Flag to enable packaging of electron binary without notarization
=> Third-party licenses available in desktop

.eslintrc.js, packages/malloy-db-duckdb/src/duckdb_connection.ts, packages/malloy-vscode/src/common/connection_manager.ts
Some of the blank pages we were getting were because we throwing string literals instead of `Error` objects, resulting in `error.message` being `null`.
=> Only throw Error objects

demo/malloy-demo-composer/scripts/build.ts, demo/malloy-demo-composer/scripts/package.ts
Typescript type cleanup and make sure that the `dist` directory actually exists before attempting to write out the license file.
=> Script touchups

cloudbuild/deploy/deploy-patch-extension.sh, packages/malloy-vscode/scripts/publish-extensions.ts
Updates publish script to expand publish automation.
- converts to specifying `major`, `minor`, `patch`, or `pre-release` as input to the publish script
- version format follows semver with `<major>.<minor>.<patch>`
- will auto-generate `patch` number for all publish types
- only increments to `major` or `minor` require a commit.
- `minor` must be EVEN, pre-releases will use ODD numbers as recommended by the documentation (see https://code.visualstudio.com/api/working-with-extensions/publishing-extension)
=> Add publish script for patch  of vscode extension.

packages/malloy-db-test/src/nomodel.spec.ts, packages/malloy/src/lang/grammar/Malloy.g4, packages/malloy/src/model/malloy_query.ts, samples/faa/flights.malloy
For excluding dimensions we've switched to the word 'exclude' for clarity (this syntax may or may not change so please don't get too attached).  
When dealing with nested query, allow exclude to specify dimensions above the current nesting level.  For example..
```
query: airports -> {
where: state = 'TX' | 'NY'
group_by:
faa_region
state
aggregate:
c
all_ is all(c)
airport_count is c {? fac_type = 'AIRPORT'}
nest: fac_type is {
group_by: fac_type
aggregate:
c
all_ is all(c)
all_state is all(c,state)
all_state_region is exclude(c,fac_type)
all_of_this_type is exclude(c, state, faa_region)
all_top is exclude(c, state, faa_region, fac_type)
}
}
```
=> Allow ungroup anywhere in the dimensional heirachy

packages/malloy-render/src/html/utils.ts
Create a more distinct gradient for maps and other visualizations than the current teal -> blue gradient.
Fixes: https://github.com/looker-open-source/malloy/issues/671
Before: 
After:
=> Increase gradient contrast

README.md
In my VSCode theme, it's quite hard to see "Preview" and I wasn't sure what I should be looking for (a button? A VSCode extension page?). Added some extra navigational text to the README so it's more clear where to find the Preview button.
=> README: Clarify location of "Preview" word

packages/malloy/src/lang/field-space.ts, packages/malloy/src/lang/test/parse.spec.ts
`accept:` and `except:` were being parsed but ignored, silly mistake in a re-factor.
the test which should have caught this, it turns out, did not exist.
Fixes #694
=> Fix accept/except

packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/test/parse.spec.ts
Fixes #687
I don't think appending to an existing named query has worked since the `:{}` event.
Fixed, now, and added the missing test.
=> fix new queries appending to old queries

packages/malloy-db-duckdb/src/duckdb.d.ts
callbacks are optional, all exec methods can have parameters.
=> More correct typing

packages/malloy-vscode/src/worker/files.ts, packages/malloy-vscode/src/worker/types.ts, packages/malloy-vscode/src/worker/worker_connection.ts
@anikaks pointed out that she now needed to save a file for VS Code to pick up changes, which didn't use to be the case. That's because the old code was using VS Code's notion of the file buffer, not the filesystem version. This restores that behavior by adding a message to retrieve the filed contents via VS Code.
=> Use vscode file buffer instead of file system

docs/_scripts/build_docs/page.ts, docs/_src/examples/faa/bigquery.md, docs/_src/examples/faa/postgres.md, docs/_src/table_of_contents.json, docs/css/document.css
PR discussed with @anikaks about adding a Postgres example into the documentation (#615).
I wanted to group this new example in the docs sidebar alongside the BQ version that it modifies, so I also included a **change to the sidebar logic** to allow for section nesting.  Previously you couldn't put an expanding section within a section.
=> Multilevel docs sidebar (and add Postgres example)

packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/test-translator.ts
1) make tests actually work
2) don't add an extra error when importing a file with errors
=> Don't throw "INTERNAL ERROR" when an imported file has errors

packages/malloy-vscode/src/extension/webviews/assets/copy.svg, packages/malloy-vscode/src/extension/webviews/query_page/App.tsx, packages/malloy-vscode/src/extension/webviews/query_page/CopyHTMLButton.tsx, packages/malloy-vscode/src/extension/webviews/query_page/Scroll.tsx
Feature request from @lloydtabb - adds a copy to clipboard button for quick export.
=> Add a Copy HTML to Clipboard button

packages/malloy/src/dialect/duckdb.ts
Malloy currently uses `make_interval` for time intervals in DuckDB, but I think DuckDB requires a different syntax (see: [Timestamp Functions](https://duckdb.org/docs/sql/functions/timestamp)), closer to standard SQL, like:
- `CURRENT_TIMESTAMP  - INTERVAL 5 DAY`
- `CURRENT_TIMESTAMP  + INTERVAL 1 MONTH`
...and so on.
=> Fix time alterations in DuckDB dialect

packages/malloy/src/lang/ast/ast-time-expr.ts
Seems like https://github.com/looker-open-source/malloy/pull/759 missed one reference (perhaps it was added after that branch was checked and before it was merged)?
=> Fix issue where FieldSpace was referenced instead of FSPair

packages/malloy/src/lang/ast/apply-expr.ts, packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/field-space.ts, packages/malloy/src/lang/test/parse.spec.ts
Sources which were queries don't quite follow the "as/name", and this was causing joins of a source based on query to fail.
Fixes #800
=> Fix joining a from(query) source

package-lock.json
npm wants us to update our dependencies ... the easy step is to ask npm to do it ...
npm install output before
25 vulnerabilities (4 moderate, 14 high, 7 critical)
after
18 vulnerabilities (4 moderate, 14 high)
maybe we should also look at the 14, or maybe just land this and move on?
=> run npm audit fix 2022-09-29

demo/malloy-demo-composer/src/app/malloyGrammar.ts, demo/malloy-duckdb-wasm/src/utils/malloyGrammar.ts, packages/malloy/src/lang/parse-tree-walkers/document-completion-walker.ts, vscode-extension/malloy.tmGrammar.json, vscode-extension/src/server/completions/completion_docs.ts
Fixes https://github.com/looker-open-source/malloy/issues/706
In docs:
In VSCode as a source property:
In VSCode as a query property:
In the DuckDB WASM demo:
=> Syntax highlight (etc.) declare correctly

docs/_scripts/build_docs/index.ts, docs/_scripts/build_docs/render_document.ts, docs/js/search.js
Update the docs renderer and search script to work with code snippets.
Some details: code snippets are included in results, just like paragraphs, but their content is collapsed to only include the lines that match the search terms and the surrounding couple lines (with ellipses to show collapse). Currently you can't un-collapse them. Matches in code snippets count for less than matches in paragraphs in terms of ranking.
Screenshots:
=> Include code snippets in search results in docs

package-lock.json, packages/malloy/package.json
An npm warning we get when installing "@malloydata/malloy" is that "querystring@0.2.0" is deprecated, this removes that dependency by removing "url", which is unused by this package, and also a couple other packages that aren't directly used by the Malloy package.
=> Prune Malloy dependencies

docs/_src/language/expressions.md, packages/malloy/src/dialect/duckdb.ts, packages/malloy/src/dialect/postgres.ts, test/src/databases/all/expr.spec.ts, test/src/util/index.ts
Fixes https://github.com/looker-open-source/malloy/issues/801
Initial task was to fix https://github.com/looker-open-source/malloy/issues/801, which was that `TRUNC` was used in DuckDB where `FLOOR` was intended (this was a copypasta when interval extraction was initially implemented).
Doing so revealed several other problems.
1. Date literals didn't work in DuckDB
```
query: stuff -> {
group_by: thing is @2020-01-01
}
```
```
Catalog Error: Scalar Function with name date does not exist!
Did you mean "day"?
LINE 2:    DATE('2020-01-01') as "thing"
^
```
We were just using the wrong syntax for creating a date from a literal.
2. Adding durations in week or quarter units didn't work in DuckDB
```
query: stuff -> {
group_by: thing is now + 1 week
}
```
```
Parser Error: syntax error at or …
```
=> Fix interval extraction for Postgres and DuckDB

demo/malloy-demo-composer/src/core/query.ts, packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-duckdb/src/duckdb_common.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy/src/index.ts, packages/malloy/src/lang/ast/ast-expr.ts, packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/test/field-symbols.spec.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, test/src/databases/bigquery/handexpr.spec.ts, test/src/databases/bigquery/malloy_query.spec.ts, test/src/models/faa_model.ts, test/src/models/medicare_model.ts
This PR makes `tablePath` required in `StructDef`s with `structSource.type === 'table'`.
Previously, code generation could not rely on this being present, and had to recreate it from `theStructDef.name` using `parseTableURL` (now renamed to `parseTableURI`).
=> StructSource with type "table" must have a tablePath

package-lock.json, packages/malloy-render/package.json, vscode-extension/package.json
If you install `@malloydata/render` from npm by itself, it doesn't include the required `vega` and `vega-lite` dependencies.
=> Add vega dependency to render

.eslintrc.cjs, demo/malloy-demo-composer/src/app/ActionMenu/ActionMenu.tsx, demo/malloy-demo-composer/src/app/AddFilter/AddFilter.tsx, demo/malloy-demo-composer/src/app/AggregateActionMenu/AggregateActionMenu.tsx, demo/malloy-demo-composer/src/app/DimensionActionMenu/DimensionActionMenu.tsx, demo/malloy-demo-composer/src/app/FilterContextBar/FilterContextBar.tsx, demo/malloy-demo-composer/src/app/NestQueryActionMenu/NestQueryActionMenu.tsx, demo/malloy-demo-composer/src/app/QuerySummaryPanel/QuerySummaryPanel.tsx, demo/malloy-demo-composer/src/app/StageActionMenu/StageActionMenu.tsx, demo/malloy-demo-composer/src/app/TypeIcon/TypeIcon.tsx, demo/malloy-demo-composer/src/app/assets/img/type_icons/type-icon-query.svg, demo/malloy-demo-composer/src/app/data/use_search.ts, demo/malloy-demo-composer/src/core/compile.ts, demo/malloy-demo-composer/src/core/query.ts, demo/malloy-demo-composer/src/electron/config.ts, packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-duckdb/src/duckdb_common.ts, packages/malloy-db-duckdb/src/duckdb_connection.ts, packages/malloy-db-duckdb/src/duckdb_wasm_connection.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy-render/src/html/html_view.ts, packages/malloy/src/index.ts, packages/malloy/src/lang/parse-to-ast.ts, test/src/databases/bigquery/handexpr.spec.ts, test/src/models/faa_model.ts, test/src/runtimes.ts, vscode-extension/src/extension/webviews/connections_page/connections_vscode_context.ts, vscode-extension/src/extension/webviews/query_page/query_vscode_context.ts, vscode-extension/src/worker/run_query.ts
Makes sure we're not deep importing from Malloy packages because this reflects bad API hygiene, and make sure we're only importing each package once.
=> Clean up imports and exports

demo/malloy-demo-bq-cli/package.json, demo/malloy-demo-composer/package.json, demo/malloy-duckdb-wasm/package.json, package.json, packages/malloy-db-bigquery/package.json, packages/malloy-db-duckdb/package.json, packages/malloy-db-postgres/package.json, packages/malloy-render/package.json, packages/malloy/package.json, test/package.json, vscode-extension/package.json
There's some weirdness in the way existing packages reference versions (@malloydata/render requires @malloydata/malloy 0.0.1 but the default @malloydata/malloy is now at 0.0.2), this attempts to fix that. I'm tempted to bump everything to 0.0.3 and make life simpler, however.
=> Bump package versions to fix some packages

vscode-extension/src/server/diagnostics/diagnostics.ts, vscode-extension/src/server/server.ts
Fixes an issue in the VSCode extension where errors in an imported file appear at the same line number in the importing file. E.g.:
`a.malloy`
```
// 
source: foo is table('this.table.does.not.exist') {}
```
`b.malloy`
```
import "a.malloy"
source: bar is foo {}
```
Line 2 of `b.malloy` would show an error for the invalid table.
Additionally, reports diagnostics for the imported file (but with the correct URI). Now, as long as you have the "Problems" tab open, or have the imported file visible, you should see an indication that there's an error in the imported file.
=> Don't show errors for imported files in the importing file

demo/malloy-demo-composer/src/core/query.ts
Fixes https://github.com/looker-open-source/malloy/issues/883
In https://github.com/looker-open-source/malloy/issues/883, there was an issue when removing fields that are used in an order by which referenced the field by index instead of by name. Specifically, the code which removes the order by on a field when the field is removed did not account for order bys which referenced fields by index. This meant that if you had `order_by: 3` and you removed a field, you could change the meaning of the order by unintentionally, or invalidate it entirely. 
Rather than handle all of the edge cases (such as adding a field before the order by field, which would require incrementing the index), this PR just adds a conversion step when loading a query (either via "Load Query" or "Duplicate") which …
=> Convert order by index to order by name in composer

packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/grammar/build_parser.js, packages/malloy/src/lang/test/parse.spec.ts
Fixes #911 
There may be other places where a change like this is needed. I leave that for future Michael to worry about.
=> Don't generate StructRef references to non exported sources

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-duckdb/src/duckdb_common.ts, packages/malloy-db-postgres/src/postgres_connection.ts, test/src/databases/bigquery/malloy_query.spec.ts, test/src/databases/postgres/postgres.spec.ts
The bigquery reader has a hack, which I just moved forward to these readers ...
A better fix is a plan to pass an "unsupported" type to the compiler ( #900  ), but this is quick and will let people use tables with fields of unknown types.
=> Handle unknown schema types in DuckDB and PostgreSQL 

packages/malloy/src/index.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts
Some small changes for the Composer. Adds a `getFlattenedQuery` method to a `PreparedQuery`, which converts a query with a `pipeHead` into one without a `pipeHead`. Also exports a couple extra types for the Composer to use.
=> Flatten query API

packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/test/parse.spec.ts
A bare `}%` in a file causes `Malloy.parse` to throw, which is two problems.
1) If the ANTLR generated code throws, we should catch it and report it as an error.
2) `}%` is a problem which we workaround here by ignoring a popMode if we are at the top level
=> handle bare }%

packages/malloy/src/lang/ast/apply-expr.ts, packages/malloy/src/lang/ast/ast-expr.ts, packages/malloy/src/lang/grammar/MalloyLexer.g4, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/parse-to-ast.ts, packages/malloy/src/lang/test/parse.spec.ts
OK, we don't support `even is (num %2 == 0)` because ... I never wrote the `%` operator into the grammar.
=> Add missing mod (%) operator

packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/test/parse.spec.ts
`Schema Error: Syntax Error:` is a little confusing. The word schema there is related to an internal detail, that the error occured when requesting the schema for a block.
Decided to drop the `:`, and emphasize that this error is in the SQL, not in the Malloy.
Fixes #967 
```
Invalid SQL, Syntax error: Unexpected string literal 'bigquery-public-data.san_francisco.`sfpd_incidents
```
Or in the case where there are multiple lines in the server error message
```
Invalid SQL, FIRST LINE
SECOND LINE
THIRD LINE
```
=> Make understandable sql errors in blocks

.eslintrc.cjs, docs/_scripts/build_docs/page.ts, package-lock.json, package.json, packages/malloy-db-duckdb/src/duckdb_common.ts, packages/malloy-render/src/drill.ts, packages/malloy-render/src/html/chart.ts, packages/malloy/src/lang/ast/ast-types.ts, packages/malloy/src/lang/zone.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/bigquery-postgres/streaming.spec.ts, tsconfig.packages.json
Confusingly, turning off `noImplicitAny` generates a lot of errors because before, arrays initialized without types like 
```typescript
const x = [];
``` 
were implicitly giving `any[]` types.
😕
=> Align typescript versions

docs/_src/examples/ecommerce.md, docs/_src/examples/faa/bigquery.md, docs/_src/examples/ga_sessions.md, docs/_src/examples/iowa/iowa.md, docs/_src/examples/names.md
The current "this model _here_" link resolves to a non-existent GitHub location resulting in 404 errors.  The new links correct this.
=> Corrects path to dot malloy files for examples

package-lock.json, package.json
Custom matchers which failed were throwing inside jest instead of reporting their error messages, due to a bug which has been fixed.
=> Update npm jest-expect-message

packages/malloy/src/model/malloy_query.ts, test/src/databases/bigquery/joined_filters.spec.ts
Fixes a bug where a join of a source with multiple filters (with commas, not `and`) only uses the last one.
We were just resetting the list of filters to `[]` before processing each filter, rather than only at the start.
=> Fix joins with multiple filters

cloudbuild/build-test/test.sh, package.json, packages/malloy-db-bigquery/package.json, packages/malloy-db-duckdb/package.json, packages/malloy-db-postgres/package.json, packages/malloy-render/package.json, packages/malloy/package.json, test/package.json
Top level build was only building malloy, and malloy wasn't cleaning its tsc build cache on clean. And hilarity ensued...
=> Top-level build now builds all workspaces

package.json, packages/malloy-db-duckdb/src/duckdb_wasm_connection.ts
Allow a callback to handle loading tables with external filesystems, like relative file paths in github repos.
=> Allow side-loading of files

.eslintrc.cjs, packages/malloy-render/src/html/vega_spec.ts, packages/malloy/src/lang/ast/elements/refined-source.ts, packages/malloy/src/lang/ast/field-space/dynamic-space.ts, packages/malloy/src/lang/ast/types/malloy-element.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/model/malloy_query.ts
Importing directly from `"lodash"` causes `_` to be defined globally and can lead to conflicts with other versions or underscore, so as a library we should only import the methods we need directly.
=> Require targeted lodash imports

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-duckdb/src/duckdb_common.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy/src/lang/ast/expressions/expr-id-reference.ts, packages/malloy/src/lang/ast/expressions/expr-not.ts, packages/malloy/src/lang/ast/types/expression-def.ts, packages/malloy/src/lang/ast/types/space-field.ts, packages/malloy/src/lang/ast/types/type-desc.ts, packages/malloy/src/lang/test/field-symbols.spec.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, test/src/databases/bigquery/malloy_query.spec.ts, test/src/databases/postgres/postgres.spec.ts
OId behavior was the create a string expression with the value "this field has an unsupported type in it"
This should allow unsupported types to be passed to functions, and to be type cast. Beyond that they would still be unsupported.
* `query: x -> { project: * }` with unsupported fields works
* `query: x -> { group_by: unsupportedTypeField }` also works
* `query: x -> { where: unsupportedTypeField != NULL; ... }` also works
* `source: { dimension: x is` _any other expression with unsupported fields_ `}` will error
* `source: { dimension: xOk is(` _unsupported expression_ `)::__any malloy_type__ }` will compile, it may fail when you run the SQL (like you can't cast a GEOGRAPHY to a STRING in BigQuery)
=> Allow unsupported types in schemas

packages/malloy-render/src/html/utils.ts
`yieldTask` in the renderer was a nice win for responsiveness during slow renders, but was total overkill. This PR reduces the number of tasks to roughly one per 100ms, so we're not blowing up the task queue. This dramatically improves performance in renders of large tables.
=> Debounce yieldTask's creation of tasks to 100ms

packages/malloy-render/src/html/unsupported.ts
Property 'value' comes from an index signature, so it must be accessed with ['value'].
=> Fix property access.

test/src/databases/bigquery/handexpr.spec.ts
Updating the row limit on occasionally failing test. Records 10-12 had the same aggregate value that was the order by column, so which row was returned as the 10th record was not guaranteed to be consistent.
=> Change row limit of flaky test.

package-lock.json, packages/malloy-db-duckdb/package.json
0.7.0 shipped without binaries for darwin x86 and win32, backing back down until 0.7.1
Reverts malloydata/malloy#1026
=> Revert "Update DuckDB to 0.7.0"

packages/malloy-db-bigquery/src/bigquery_connection.ts, test/src/databases/bigquery/wildcard_table_names.spec.ts
This patch supports BigQuery wildcard table names in Malloy:
- validated the correctness of wildcard use in BigQuery table names.
- returned the first table that matches the wildcard prefix to build table schema.
- populated a pseudo column `_TABLE_SUFFIX` when there are wildcard table names.
=> Support BigQuery wildcard table names in Malloy

packages/malloy-db-bigquery/src/bigquery_connection.ts, test/src/databases/bigquery/injestion_time_partitioning.spec.ts
Following PR #1042, this patch continues the support of BigQuery's _PARTITIONTIME and _PARTITIONDATE in Malloy:
- Added more tests for _PARTITIONTIME
- Populated the _PARTITIONDATE pseudo column for ingestion day-partitioned tables.
=> Support BigQuery's _PARTITIONTIME and _PARTITIONDATE in Malloy

packages/malloy/src/lang/ast/types/malloy-element.ts, test/src/api.spec.ts, test/src/runtimes.ts
It turns out compiling a model from a pre-existing model, which has been around since the beginning of time because it was the basis for all my compiler tests, doesn't take anything from the pre-existing model except sources.
Not any more :)
=> Fix extendModel with queries

packages/malloy-db-postgres/src/postgres_connection.ts
Malloy code was augmented to make any unknown types cause failures.
The special casing for UUID in postgres can now be removed.
fixes #1021
=> Remove special casing for UUID in postgres

packages/malloy/src/lang/ast/sources/named-source.ts, packages/malloy/src/lang/ast/sources/sql-source.ts, packages/malloy/src/lang/ast/types/malloy-element.ts, packages/malloy/src/lang/ast/types/model-entry.ts, packages/malloy/src/lang/test/parse-expects.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/sql-block.spec.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_types.ts
Fixes #1076 
StructDefs which resulted from an `sql:` statement now have a bit on them, in the structdef.
We clear that bit when we alias them into a `source:`
This allows us to treat sql blocks as if they were a thing which is neither a query nor structdef, and properly error when people forget to use from_sql (and not erroneously error when people do)
KInd of a lot of work to maintain a distinction which none of us believe in, but this is the most peaceful thing for me, given that there is no guarantee we are actually going to get to source/query, this PR correctly implements the current intended semantics for SQL blocks.
We will undo this when we do source/query, and that's OK with me too.
=> Fix extending models with from_sql based sources

packages/malloy/src/index.ts, packages/malloy/src/lang/test/model_serialization.spec.ts, packages/malloy/src/malloy.ts
This patch supports the `Explore` object serialization with JSON:
- encapsulated structDef in an Explore and all its parents, sources into a struct for JSON serialization.
- leave the server side optimization of `_fieldMap` field to future, as it contains self references.
=> Support Explore object serialization with JSON

packages/malloy-db-bigquery/src/bigquery_connection.ts
To specify projectId and credentials dynamically, we can pass `projectId` to BigQuery, and we can pass `credentials` body in lieu of `serviceAccountKeyPath`.
=> Pass projectId and credentials body to BQ auth

packages/malloy/src/model/malloy_query.ts
Fix the "'Expected this query struct to have a parent, as no model was present.'" error is closure compilers.
=> Fix  - no model was present error.

packages/malloy/src/lang/ast/types/expression-def.ts, packages/malloy/src/lang/test/parse.spec.ts
There was no test for this, and the timezone change broke it.
It is fixed and there is a test now
=> Restore ability to compare timestamp and date values to NULL

packages/malloy/src/lang/ast/elements/define-query.ts, packages/malloy/src/lang/test/parse.spec.ts
=> query: statement should error on redefine

packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/duckdb.ts, packages/malloy/src/dialect/postgres.ts, packages/malloy/src/dialect/standardsql.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/bigquery-duckdb/nested_source_table.spec.ts
Aparently they didn't implement 
> Binder Error: Nested lateral joins or lateral joins in correlated subqueries are not (yet) supported
May have to revert to using array indexes :(
=> Nested pipelines are busted in DuckDB

packages/malloy/src/dialect/standardsql.ts
JS renaming in closure compilers causes issues in places where struct variables are accessed as dicts. Putting this fix while I figure out the lint rule with the details.
=> Remove dict type accesses on struct type (without [] operator)

packages/malloy/src/lang/ast/expressions/expr-coalesce.ts, packages/malloy/src/lang/ast/expressions/pick-when.ts, packages/malloy/src/lang/test/parse.spec.ts
Previously the following expressions all had a type of `null`, and therefore could not be used to define a field:
```malloy
my_string ? pick null when = 'bad_value'
my_string ? pick null when = 'bad_value' else my_string
pick null when my_string = 'bad_value' else my_string
```
Now all of those get type `string` and can be used to define a field.
Also added a new test function `exprType` in `parse.spec.ts` to check the type of an expression, not just that it parsed, as in this case, the expressions were already parsing, but just had a type of `null`. We may want to consider using this function in other tests, too.
=> Allow null to be first branch value of pick statement

packages/malloy/src/malloy.ts, test/src/api.spec.ts
- Fix unsafe property access of a returned record that could be undefined.
- Add test to verify new behavior.
=> Update getNamedQuery handling when requesting a named query that does not exist.

packages/malloy-db-duckdb/package.json
A bad merge accidentally pinned the duckdb package's malloy version to 0.0.40, and that has cause it to diverge.
=> Fix duckdb malloy version

packages/malloy/src/malloy.ts, packages/malloy/src/tags.ts, test/src/tags.spec.ts
We use special comments in files to tell the renderer where to find the json file which describes the render parameters.
Those should be in the "model" tags, which I implemented, but then forgot to provide an API for.
Fixed.
* Tags starting with `##` are file/document/model tags ( as they always were )
* `await XXX.getModel().getTags().getMalloyTags()` will now get you the tag parse for a model
=> Attach document level tags on model

packages/malloy/src/lang/parse-tree-walkers/document-symbol-walker.ts, packages/malloy/src/lang/test/document-symbol-walker.spec.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/malloy.ts
The rule is that the `lensRange` for a document symbol will start before the "block tags" (tags before the `type:`) unless there is more than one definition in the block, in which case it will start before the "individual tags" the tags before the `name is ...`. 
This is implemented for:
* Turtles
* Unnamed top level queries
* Top level queries
* Sources
As these are the only things with code lenses (except SQL blocks, see note below). If we add more code lenses, we will have to implement this for those things, too.
Note: SQL blocks are not included here, as we are phasing them out, and they currently don't support tags at all. Also, run "references" (`run: query_name` as opposed to `run: -> query_name`) are not included, as tags are not supported for those yet. 
Turtles:
Unnamed queries: …
=> Add new `lensRange` for `DocumentSymbol`s to move code lenses above tags

packages/malloy-render/src/html/html_view.ts
Fix case where dataStyles specifies a renderer and there are no tag or magic name overrides.
=> Return defined renderer

packages/malloy/src/lang/ast/expressions/expr-string.ts, packages/malloy/src/lang/grammar/DeltaMalloy.g4, packages/malloy/src/lang/grammar/MalloyLexer.g4, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-tree-walkers/document-highlight-walker.ts, packages/malloy/src/lang/parse-tree-walkers/find-external-references.ts, packages/malloy/src/lang/string-parser.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/strings.spec.ts, test/src/databases/all/expr.spec.ts, test/src/util/index.ts
This PR makes ' ` and " strings all behave the same. The can all contain \ escapes for bfrnt and uXXXX for unicode.
Also, every place in the language where a string is legal, a ' or " string is legal. The only difference in the two
is which quote character you have to use \ on
=> Cleanup Strings

packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/test/parse.spec.ts
This is different than allowing """ strings as literals because we do a different thing in the parse step.
=> Allow ' and " strings in CONNECTION.sql()

packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-tree-walkers/find-external-references.ts, packages/malloy/src/lang/parse-utils.ts, packages/malloy/src/lang/test/strings.spec.ts
Legal in
```
timezone: """if you really want to"""
import: """foo:\\my\\server\\wants\\backslash"""
dimension: lyric is """
i wonder wonder who
who wrote the book of love
"""
source: flights is bigquerr.table("""flights""")
```
If the string contains a `%{ }%` query, there will be an error
=> Allow """ strings (almost) everywhere

packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-utils.ts, packages/malloy/src/lang/test/strings.spec.ts
Since it is common to write these strings in the middle of indented code, it is nice to remove the extra indent
added to make the string line up with the code
```
source: a is b extend {
dimension: poem is """
hello
to all
and to all
a good night
"""
Produces the string
hello
to all
and to all
a good night
```
This PR looks for the minimum space indent on any non blank line, and then deletes that many spaces on every line that starts with spaces
Descision was made NOT to de-indent sql blocks because
```
run: bigquery.sql("""
SELECT
*
FROM (%{ bigquery.sql("""
SELECT
1 as one,
2 as two
""") -> { project: * } }%)
""") -> { project: * }
```
Reads better without indentation removal
```
SELECT 
base.one as `one`,
base.two as `two`
FROM (
SELECT
*
FROM (SELECT 
base.one as `one`,
base.two as …
```
=> de-indent """ strings in expressions

packages/malloy/src/lang/malloy-to-ast.ts
`top: N` will still be legal, but the `by` clause is going away in m4.
This PR adds it to the m4 warning list.
=> Deprecate `top:N by`

.gitignore, packages/malloy-malloy-sql/.gitignore, packages/malloy-malloy-sql/package.json, packages/malloy-malloy-sql/src/grammar/malloySQL.pegjs, packages/malloy-malloy-sql/src/grammar/malloySQLSQL.pegjs, packages/malloy-malloy-sql/src/grammar/test/parse.spec.ts, packages/malloy-malloy-sql/src/index.ts, packages/malloy-malloy-sql/src/malloySQLErrors.ts, packages/malloy-malloy-sql/src/malloySQLParser.ts, packages/malloy-malloy-sql/src/malloySQLSQLParser.ts, packages/malloy-malloy-sql/src/types.ts
Use two parsers, one to split up the MalloySQL document, the second to handle MalloySQL SQL cells, so that it can be used separately for notebook cells.
I tried to just modify the original parser to handle both scenarios but peggy didn't want to play along.
=> Split out MalloySQL SQL parser

packages/malloy-render/src/index.ts
DataStyles references all the other types in this file, so they should be exported, too.
=> Export DataStyles related types

packages/malloy-malloy-sql/src/grammar/test/parse.spec.ts, packages/malloy-malloy-sql/src/malloySQLParser.ts, packages/malloy-malloy-sql/src/types.ts
In order to be able to easily re-serialize a parsed document we need a hint whether the connection was directly or indirectly assigned.
=> Flag inherited connections

packages/malloy-malloy-sql/src/grammar/malloySQL.pegjs, packages/malloy-malloy-sql/src/grammar/test/parse.spec.ts
Check that `>>>` is not preceded by `EOL`. Don't include `EOL` in statement body so notebooks don't have extra space.
=> Don't catch mid-line delimiter starts

packages/malloy-malloy-sql/src/grammar/malloySQL.pegjs, packages/malloy-malloy-sql/src/grammar/test/parse.spec.ts
Comment parsing can be done by the MalloySQLSQL parser, does not need to confuse things here.
=> Fix cells with only comments

packages/malloy/src/index.ts
Malloy service needs QueryValue for rendering.
=> Export QueryValue

cloudbuild/README.md, cloudbuild/build-test/cloudbuild.yaml, cloudbuild/deploy/cloudbuild.yaml
**tl;dr**: this ensures that the latest package definitions are fetched from `nixpkgs`
---
We change the image to `nixos/nix:2.15.2` to ensure that we pull this specific image from the cache, which is populated with a more recent version of `nixpkgs`.
Updating `nixos/nix` references was done with the following:
```bash
git grep --null --files-with-matches "nixos/nix" |
xargs --null -I{} sed -i 's/nixos\/nix/nixos\/nix:2.15.2/' {}
```
This will allow us to use the latest official package references; for example https://search.nixos.org/packages?channel=23.05&show=nodejs_18.
---
For a concrete example of why this is helpful, see https://github.com/malloydata/malloy/pull/1314#discussion_r1309498349.
=> Specific nixos/nix:2.15.2

default.nix
Node.js 16.x will leave maintenance status 2022-09-11. Source: https://github.com/nodejs/release#release-schedule.
Per the OpenJS foundation, the 18.x series is currently recommended. Source: https://nodejs.org/en.
Resolves https://github.com/malloydata/malloy/issues/1313
=> Bump Node.js to v18 per Pending v16 EOL

README.md
`documentation.md` has been subsumed by `developing.md`
=> Remove Dead Documentation Link

packages/malloy-syntax-highlight/grammars/malloy-notebook/malloy-notebook-language.json, packages/malloy-syntax-highlight/grammars/malloy-sql/malloy-sql-language.json, packages/malloy-syntax-highlight/grammars/malloy/malloy-language.json
Add a schema to our language config, and then fix the issues it highlights - `lineComment` is meant to be a single string used to comment out a line, not an array of potential lineComment starts. VS Code was falling back to multi-line commenting for single lines as a result.
=> Language config schemas

packages/malloy/src/lang/malloy-parse-info.ts, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/test/imports.spec.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/malloy.ts
There are a few use cases, like notebook cells, where the document URL is not ideal for importing, but we still want to be able to import from. There's a bunch of hackery in the VS Code extension that makes this work, but it would be cleaner to push this into the parser itself. This adds an optional parser parameter, `importBaseURL`, that can be used as the basis for importing.
=> Allow import base url

packages/malloy/src/lang/ast/field-space/query-spaces.ts, packages/malloy/src/lang/ast/query-items/field-references.ts, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/test/query.spec.ts
On the way to towards a more full featured star.
`select: * { except: badThing, otherBadThing }`
What's missing is "*" in index doesn't use this, and the user request was also to have rename, which is more code to implement
=> add * { except: } for wildcard expansion in select: *

.eslintignore, package-lock.json, packages/malloy-syntax-highlight/.eslintignore, packages/malloy-syntax-highlight/grammars/malloy/malloy.monarch.ts, packages/malloy-syntax-highlight/grammars/malloy/malloy.tmGrammar.json, packages/malloy-syntax-highlight/grammars/malloy/tokenizations/darkPlus.ts, packages/malloy-syntax-highlight/package.json, packages/malloy-syntax-highlight/test/visual/index.html, packages/malloy-syntax-highlight/test/visual/malloy.tmGrammar.json
Old:
New:
Also add a super simple visual tester for the textmate grammar with `npm run serve-visual`
=> Fix `run:` highlighting

packages/malloy-render/src/html/image.ts
Adds support for the following properties for an image tag:
- width: set a width value to be applied to the image. Will also be applied to the null value placeholder to maintain consistent size
- height: set a height value to be applied to the image. Will also be applied to the null value placeholder to maintain consistent size
- alt: set alt text for the image
Set width to 200px. All images will be 200px wide. The corresponding height will be according to the aspect ratio of the image. The null value placeholder will also be sized to 200px wide to maintain horizontal alignment in dashboards.
```
```
Set height to 200px. All images will be 200px tall. Width will be according to the aspect ratio of the image. Null value placeholders will get the 200px height as well.
```
```
Set width and …
=> feat: image properties for width, height, alt text

packages/malloy/src/lang/grammar/MalloyLexer.g4, packages/malloy/src/lang/test/literals.spec.ts, packages/malloy/src/lang/test/parse.spec.ts
A tab was not included in the list of characters which it is legal to have inside of a string.
Grammar review as long I was here, also allow \U00A0 ( unicode non breaking space) as a space character in source code
Fixes #1402
=> allows tabs in strings

packages/malloy/src/dialect/duckdb/duckdb.ts, packages/malloy/src/dialect/postgres/postgres.ts, packages/malloy/src/dialect/standardsql/standardsql.ts, test/src/databases/duckdb/duckdb.spec.ts, test/src/databases/postgres/postgres.spec.ts
Fixes https://github.com/malloydata/malloy/issues/1364
The issue is that when we convert SQL types to Malloy types, we only check literal values like BOOLEAN, VARCHAR, etc. If a user casts to a VARCHAR with max length like `VARCHAR(3)`, this is not caught by our type conversion and results in an Unsupported Type, which then won't get rendered as a string.
The solution I've added here is to add an additional set of checks that use regex pattern matching so we can capture more complex SQL types than just literals. If this solution is acceptable, then I will implement it in the other connectors besides DuckDB.
=> fix: capture VARCHARs with max length as strings

packages/malloy/src/malloy.ts
To be used for "Jump to definition" in various places.
=> Explore location in fields

packages/malloy/src/tags.ts, test/src/tags.spec.ts
Reported by @skokenes who found that
```
```
Was producing the same thing as `# image`.
The culprit was a bug which would cause `any any.thing` to result in `any`.
=> fix "x x.y" taglines

packages/malloy-render/src/html/image.ts
Previous PR for adding width/height attributes to images claimed you could pass valid CSS text values for size, but that was incorrect. The code was actually pulling out numeric values and hardcoding to pixels.
This PR updates to the desired behavior: user's can define image sizes in pixels, ems, percentages, etc.
=> fix: text not numeric img size props

package-lock.json, packages/malloy-db-duckdb/package.json, packages/malloy-render/.storybook/main.ts, packages/malloy-render/.storybook/registered_data.json, packages/malloy-render/README.md, packages/malloy-render/src/html/image.ts, packages/malloy-render/src/html/utils.ts, packages/malloy-render/src/stories/basic.stories.ts, packages/malloy-render/src/stories/image.stories.ts, packages/malloy-render/src/stories/static/basic.malloy, packages/malloy-render/src/stories/static/data/logos.csv, packages/malloy-render/src/stories/static/image.malloy, packages/malloy/src/malloy.ts
Introduces the ability to have dynamic data lookup in the Malloy renderer, with the first implementation being with the `# image.alt` property:
The renderer can optionally read tags of `field` as being references to data within the current record or any record above. To indicate reading from a record above, `^` are used to indicate how many record levels in the results tree to go up before looking for a field value. For example, `field=brand` would look at a brand field in the current cell's record (assuming we land https://github.com/malloydata/whatsnext/blob/main/wns/WN-0005/wn-0005.md). `field='^brand'` would look up brand in the parent record of the current cell. `field='^^brand'` would look at the parent's parent record, so on and so forth. When navigating up the tree, array parents …
=> feat: dynamic rendering props

packages/malloy-render/src/html/unsupported.ts, packages/malloy/src/malloy.ts
For instance, latitude and longitude in our postgres "airports" table are the unsupported type "double precision". Because both 'number' and 'object' types were falling into this conditional, it was generating:
`TypeError: cannot use 'in' operator to search for 'value' in 171.73`
=> Handle unsupported values that are numbers

package-lock.json, packages/malloy/package.json, test/package.json, test/src/databases/all/time.spec.ts, test/src/databases/bigquery/time.spec.ts, test/src/databases/duckdb/duckdb.spec.ts, test/src/databases/postgres/postgres.spec.ts
We were using luxon 2.4.0 in some places and luxon 1.26 in others, update to 2.4.0 and fix API usage.
=> Consistently use luxon 2.4.0

packages/malloy-syntax-highlight/tsconfig.json
When installed as a submodule, these packages are hoisted so they are not predictably in malloy's node_modules directory.
=> Use node resolution to allow hoisting in submodules

packages/malloy-render/src/html/table.ts, packages/malloy-render/src/stories/basic.stories.ts, packages/malloy-render/src/stories/static/basic.malloy, test/src/render/__snapshots__/render.spec.ts.snap, test/src/render/render.spec.ts
When rendering a nested query with no group_bys, you can get an ugly looking table with unnecessarily embedded headers:
```malloy
{
group_by: category
aggregate: avg_retail is retail_price.avg()
nest:
mens is {
aggregate:
avg_price is retail_price.avg()
total_cost is cost.sum()
where: department="Men"
}
womens is {
aggregate:
avg_price is retail_price.avg()
total_cost is cost.sum()
where: department="Women"
}
}
```
Using a `# flatten` tag, a nested query with no group_bys will automatically pull the column names of the nested measures up a level like so:
```malloy
{
group_by: category
aggregate: avg_retail is retail_price.avg()
nest:
mens is {
aggregate:
avg_price is retail_price.avg()
total_cost is cost.sum()
where: department="Men"
}
womens is {
aggregate:
avg_price is …
```
=> Add flattened measure lists

test/src/databases/all/lenses.spec.ts, test/src/util/db-jest-matchers.ts
This code was clearly meant to be short-lived, but it also caused _all tests that use nests_ to be skipped, _regardless of whether the connection supports nesting_.
=> Fix code that skips tests that use `nest:` on databases that don't support nests

packages/malloy-malloy-sql/src/grammar/malloySQLSQL.pegjs, packages/malloy-malloy-sql/src/grammar/test/parse.spec.ts
Bring Malloy SQL in line with current turducken syntax.
Fixes #1401
=> Allow '}' to end embedded SQL

packages/malloy-db-postgres/src/postgres_connection.ts
Correctly set up timezone for non-pooled connections, fix possible infinite recursion with raw sql execution, pass configuration into pooled connections.
=> Postgres fixes

packages/malloy/package.json, packages/malloy/src/lang/ast/elements/pipeline-desc.ts, packages/malloy/src/lang/ast/elements/source-query-nodes.ts, packages/malloy/src/lang/ast/query-builders/index-builder.ts, packages/malloy/src/lang/ast/query-builders/partial-builder.ts, packages/malloy/src/lang/ast/query-builders/project-builder.ts, packages/malloy/src/lang/ast/query-builders/reduce-builder.ts, packages/malloy/src/lang/ast/query-elements/existing-query.ts, packages/malloy/src/lang/ast/query-elements/full-query.ts, packages/malloy/src/lang/ast/query-properties/calculate.ts, packages/malloy/src/lang/ast/query-properties/nest.ts, packages/malloy/src/lang/ast/query-properties/qop-desc.ts, packages/malloy/src/lang/ast/query-properties/refinements.ts, packages/malloy/src/lang/ast/query-utils.ts, packages/malloy/src/lang/ast/struct-utils.ts, packages/malloy/src/lang/ast/types/query-property-interface.ts, packages/malloy/src/lang/test/lenses.spec.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/query.spec.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, test/src/databases/all/lenses.spec.ts, test/src/util/db-jest-matchers.ts, test/src/util/index.ts
Implements the experimental parts (scalar lense) of [WN 0006](https://github.com/malloydata/whatsnext/blob/main/wns/WN-0006/WN-0006.md)
* Feature requires experimental tag: `##! experimental { scalar_lenses }`
* Anywhere where you can reference a view name in a query, you can reference a dimension or measure instead
* E.g. `run: flights -> flight_count` is equivalent to `run: flights -> { aggregate: flight_count }`
* Can be used in views and nests as well
* Doesn't work with dotted names (yet)
* Particularly useful for shorthand query "column building" style: `flights -> carrier + flight_count + { where: origin.state = 'CA' }`
Adds support for the first literal view of a refinement chain not specifying any fields.
* Previously, `run: flights -> { where: true } + metrics` would fail with …
=> WN-0006 Scalar Lenses and support views with literal heads having no fields

packages/malloy/src/lang/ast/elements/pipeline-desc.ts, packages/malloy/src/lang/ast/elements/source-query-nodes.ts, packages/malloy/src/lang/ast/query-elements/full-query.ts, packages/malloy/src/lang/ast/query-properties/nest.ts, packages/malloy/src/lang/ast/query-properties/refinements.ts, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-tree-walkers/document-symbol-walker.ts, packages/malloy/src/lang/test/lenses.spec.ts, packages/malloy/src/model/malloy_types.ts, test/src/databases/all/lenses.spec.ts
Updates to the scalar lenses experiment feature —
* `nest: name_of_dimension` is equivalent to `nest: { group_by: name_of_dimension }`
* Using `join_name.field_name` is allowed in view refinement chains
=> WN-0006 Scalar Lenses Part II

packages/malloy/src/lang/ast/expressions/expr-id-reference.ts, packages/malloy/src/lang/ast/field-space/column-space-field.ts, packages/malloy/src/lang/ast/field-space/join-space-field.ts, packages/malloy/src/lang/ast/field-space/query-space-field.ts, packages/malloy/src/lang/ast/field-space/query-spaces.ts, packages/malloy/src/lang/ast/field-space/reference-field.ts, packages/malloy/src/lang/ast/field-space/rename-space-field.ts, packages/malloy/src/lang/ast/field-space/static-space.ts, packages/malloy/src/lang/ast/field-space/struct-space-field-base.ts, packages/malloy/src/lang/ast/field-space/wild-space-field.ts, packages/malloy/src/lang/ast/query-items/field-declaration.ts, packages/malloy/src/lang/ast/query-properties/joins.ts, packages/malloy/src/lang/ast/query-properties/ordering.ts, packages/malloy/src/lang/ast/query-properties/qop-desc.ts, packages/malloy/src/lang/ast/query-properties/refinements.ts, packages/malloy/src/lang/ast/query-properties/top.ts, packages/malloy/src/lang/ast/types/lookup-result.ts, packages/malloy/src/lang/ast/types/space-entry.ts, packages/malloy/src/lang/ast/types/space-param.ts, packages/malloy/src/lang/test/lenses.spec.ts, packages/malloy/src/lang/test/source.spec.ts, test/src/databases/all/lenses.spec.ts
Before this fix, this query does the wrong thing:
```malloy
source: x is duckdb.sql("SELECT 1 AS n") extend {
measure: c is count()
view: v is { aggregate: c }
}
run: x -> v + {
aggregate: e is c { where: false }
}
```
In particular, `e` should be `0` in the result, but it is `1` instead. This is because `c` (in the definition of `e`) is being treated as an output field, and the compiler gets confused when there is an output field with filters, because that shouldn't normally be possible.
This was due to an issue involving mutating the `SpaceEntry` that is copied from the refinement LHS `exprSpace` into the `QuerySpace` of the refinement RHS in order to specify that in the `QuerySpace` the field is in the output space. With a small refactor of the way that output space is recorded for …
=> Fix refinement output space issue

packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/test/imports.spec.ts, packages/malloy/src/lang/translate-response.ts
For @whscullin 
A `TranslateResponse` (i.e. a return from `.translate()` will now always have a `fromSources` array of URLs fetched so far.
Since you will get a translate reponse for every import, asking for the actual source for each url, you probably don't want to look at `fromSources` until you have come back from the `.final = true` response before you pay attention to the lsit.
=> correctly  compute dependencies

jest.config.js, package-lock.json, package.json, packages/malloy-render/.gitignore, packages/malloy-render/.npmignore, packages/malloy-render/.storybook/main.ts, packages/malloy-render/package.json, packages/malloy-render/src/component/render.ts, packages/malloy-render/src/component/table.ts, packages/malloy-render/src/html/html_view.ts, packages/malloy-render/src/renderer_types.ts, packages/malloy-render/src/stories/basic.stories.ts, packages/malloy-render/src/stories/image.stories.ts, packages/malloy-render/src/stories/render-malloy-legacy.ts, packages/malloy-render/src/stories/render-malloy.ts, packages/malloy-render/src/stories/static/tables.malloy, packages/malloy-render/src/stories/tables.stories.ts, packages/malloy-render/src/stories/themes.css, packages/malloy-render/src/stories/util.ts
This PR sets up the foundation for the next generation Malloy renderer.
- Lit installed for web components, storybook/types added for missing types
- New renderer deployed inside the legacy HTMLView behind a `## renderer_next` document tag
- New renderer wrapper implemented as a Lit web component
- Initial implementation of a basic table matching design specs from @tschomer 
- basic theme control with CSS variables
- Stories showing new renderer as well as ability to custom theme it
In the future, we will probably want to export the web component directly so that developers have flexibility to use it in different ways like so:
```typescript
import "@malloy/render";
// In vanilla js
const el = document.createElement("malloy-render");
// In Lit
html`<malloy-render></malloy-render>`
// In …
```
=> feat: renderer next setup

package-lock.json, packages/malloy-db-duckdb/package.json, packages/malloy-db-duckdb/src/duckdb_connection.ts, packages/malloy-db-duckdb/src/duckdb_wasm_connection.ts, packages/malloy/src/dialect/duckdb/duckdb.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/nomodel.spec.ts
Experiment with updating to duckdb 0.9.0. There was an issue with prebuilt binaries for 0.9.0 so this uses a recent dev build.
@lloydtabb / @christopherswenson - A bunch of UDF tests are failing, like "Multi value to udf". The results from DuckDB are lacking the "t1" property name. Not clear to me if this is a bug or a change in behavior we need to adapt to.
BigQuery:
```json
[
{
"fun": [
{
"t1": 52
}
]
}
]
```
DuckDB/DuckDB WASM:
```json
[
{
"fun": [
{
"": 52
}
]
}
]
```
=> duckdb 0.9.2

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-duckdb/src/duckdb_connection.ts, packages/malloy-db-duckdb/src/duckdb_wasm_connection.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy/src/run_sql_options.ts
This was less successful than I'd hoped - node-pg and our duckdb node library both do not support cancellation, only bigquery and duckdb-wasm have support.
=> Attempt to support cancel when possible

packages/malloy-render/.storybook/preview.ts, packages/malloy-render/src/component/render.ts, packages/malloy-render/src/component/table.ts, packages/malloy-render/src/component/util.ts, packages/malloy-render/src/stories/basic.stories.ts, packages/malloy-render/src/stories/static/basic.malloy, packages/malloy-render/src/stories/static/tables.malloy, packages/malloy-render/src/stories/tables.stories.ts, packages/malloy/src/malloy.ts
Implements nested tables in the next-gen renderer according to our design spec
- Table cells have left and right gutters, defaulting to 15px side
- Gutter divs used instead of padding, because in the future we need to render content in those gutters while hiding text overflow within the cell content
- Gutter divs also required because in some scenarios, we want to remove the border from the gutter. This is mainly the case for nested tables. We don't want nested tables that are side by side to look like they are connected, so we don't draw borders in the gutters on the bookends of tables (nested or otherwise)
- Nested tables gutters should not cascade, so gutters aren't applied in the cells embedding a nested table
- Column widths must be hardcoded for nested columns to line up across …
=> feat: nested tables

packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/parse-tree-walkers/model-annotation-walker.ts, packages/malloy/src/lang/test/model-annotation-walker.spec.ts, packages/malloy/src/lang/translate-response.ts, packages/malloy/src/malloy.ts, packages/malloy/src/run_sql_options.ts, packages/malloy/src/runtime_types.ts
> I have not written any tests for this since it's somewhat experimental at the moment, and none of our built-in connections have any use for it yet.
Adds `modelAnnotation` and `queryAnnotation` options to the `RunSQLOptions` passed into the `Connection.runSQL` and `.runSQLStream` methods.
These can be manually provided if you want:
```ts
myConnection.runSQL('SELECT 1', { modelAnnotation: someAnnotationObject });
```
You can also pass it in manually in the `.run()` methods in the `RuntimeAPI`.
The easy way, though, is that the `Runtime` API automatically adds these in:
```ts
const result = runtime.loadQuery('duckdb.sql("select 1") -> { select: * }').run(
// runtime automatically adds in `modelAnnotation` and `queryAnnotation`
);
```
Then in a connection, you can implement custom logic for …
=> Make the runtime API automatically pass query and model annotations into the connection when running a query

package-lock.json, packages/malloy-render/.storybook/preview-head.html, packages/malloy-render/package.json, packages/malloy-render/src/component/render.ts, packages/malloy-render/src/component/table.ts, packages/malloy-render/src/stories/tables.stories.ts, packages/malloy-render/src/stories/themes.css, packages/malloy/src/malloy.ts
https://github.com/malloydata/malloy/assets/5554373/044345c6-6e42-4502-b48f-c5ce1d907282
- Table now has a scroll wrapper around it. It will fit width/height to whatever it is embedded within
- Table uses a self-consuming context to determine if its at root or not.
- If at root, a set of sticky headers is drawn. The sticky headers are just another instance of the malloy-table embedded, but with only 1 row drawn at each level and all non-headers hidden
- On scroll, a class is added so that the sticky headers will change color. In order for this to work, sticky header versions of malloy-table are rendered within the parent root instead of its own ShadowDOM root
- For sticky headers, all pointer events are removed from base wrapper and then explicitly added to th cells. Otherwise, user can't …
=> feat: pinned headers

packages/malloy/src/index.ts
There were more types, but they've been already handled by other PRs.
=> Export types we're using elsewhere

packages/malloy-render/src/component/render.ts, packages/malloy-render/src/component/table.ts
Adds a few style changes to support VS Code extension integration and testing
- Adds and exposes `container` part so that table wrapper can be styled with CSS; needed to control max height of table in a notebook
- Adds a compact mode setting so that we can easily test some variations on the table design with real data
- Cleans up some of the number typography
=> feat: styling prep for VS Code ext

packages/malloy-render/src/component/render-numeric-field.ts, packages/malloy-render/src/component/table.ts, packages/malloy-render/src/stories/static/tables.malloy, packages/malloy-render/src/stories/tables.stories.ts
Adds number formatting from old renderer to new renderer: `number`, `currency`, `percent`, and `duration`
For the number formatting logic in render-numeric-field.ts, the logic is just copied out of the legacy renderer code. I opted not to create separate renderer components for number formats for now; it seems wasteful to create a web component for every numeric cell in a table if it doesn't have any need for state, lifecycle events, etc.
So for now, our formatting just takes a numeric value and field def and returns a string of what it should look like. If our requirements grow such that these numbers need more complex features, we can refactor into a component.
=> feat: number formatting

packages/malloy/src/lang/parse-tree-walkers/document-symbol-walker.ts, packages/malloy/src/malloy.ts
We want to enable lenses to preview sources to `import` statements, so add that information to the list of symbols returned from the document symbol walker.
Also enable removing a hack in the extension to retrieve `NamedQuery` objects for a model for schema views.
=> Add lens support for imports

packages/malloy-malloy-sql/src/grammar/malloySQLSQL.pegjs, packages/malloy-malloy-sql/src/grammar/test/parse.spec.ts
Reverts malloydata/malloy#1473
Since `}` is a valid Malloy character this can terminate a Malloy block prematurely.
=> Revert "Allow '}' to end embedded SQL"

packages/malloy/src/malloy.ts
So that abortSignal can be passed down.
=> Fix runStream options type

test/src/databases/all/problems.spec.ts
Since we added a mode where errors don't throw, this test can validate warnings after errors.
=> Enable test using noThrowOnError

packages/malloy-render/src/component/bar-chart.ts, packages/malloy-render/src/component/chart-settings.ts, packages/malloy-render/src/component/render-result-metadata.ts, packages/malloy-render/src/component/render.ts, packages/malloy-render/src/component/table-layout.ts, packages/malloy-render/src/component/table.ts, packages/malloy-render/src/component/util.ts, packages/malloy-render/src/component/vega-chart.ts, packages/malloy-render/src/component/vega-lite-base-spec.ts, packages/malloy-render/src/component/vega-types.ts, packages/malloy-render/src/stories/bars.stories.ts, packages/malloy-render/src/stories/static/bars.malloy, packages/malloy-render/src/vega.d.ts
This PR adds a very basic nested bar chart to the new renderer.
In order to keep this PR from being massive, many necessary features and implementation details have been left out as future TODOs. Those include the following:
- this PR only implements bar chart as nested within a table cell; root level bar chart renderings do not work yet
- the bar chart implementation has its own bespoke Vega spec. We will rearchitect this to use a more generalized XY Plot components like the old renderer does. Starting just with bar here to keep things simple
- the extraction of which fields are X and Y in the bar chart is rudimentary
- many of the styles needed to calculate size and render the bar charts are hardcoded, instead of referencing the theme
- only supports strings in X axis and numbers in Y …
=> feat: basic nested bar chart

package-lock.json, package.json
You will now get a warning if you try to do `npm install` with a node < 18, or an npm < 9, which is what our `package-lock.json` file is built with. Also update the node typings to match. Node 16 is EOL and we've updated the other places it's referenced: `default.nix` and `.node-version`
=> Update node engine and types packages to 18

packages/malloy-render/src/component/render.ts, packages/malloy/src/index.ts
Enable the renderer to optionally receive `queryResult` and `modelDef` and reconstruct the Result object internally, as an override to providing an already constructed Result object. This makes it easier to use the web component in apps like notebooks that are receiving the serialized queryResult and modelDef but don't have malloy code for constructing the Result.
=> feat: renderer can produce result

packages/malloy/src/tags.ts
There was a debugging method `Tag.peek()` which was vaguely use for me to inspect tag trees for parsing errors. Made it more generally useful, it now does a more full dump of a tag tree and all the values.
=> better tag inspection

packages/malloy/src/tags.ts, test/src/tags.spec.ts
Fixes a bug where setting a property on a tag which does not yet have properties doesn't work, e.g.
```
```
This occurred because the code which extracted the object on which to set the new property did not create an empty `.properties` object that was actually linked to the parent object (`plot`). In that case, the `properties` object is created when the `.x` is set, but it is not linked back to the `plot`.
Fixed this by changing that function to create the `.properties` before the child `Tag` object is created, so that `pathToSet === parent.properties`.
=> Fix property set on existing tag with no properties

packages/malloy/src/tags.ts, test/src/tags.spec.ts
Make tag inspector show a slightly truer version of the tag tree, it was previously duping entities.
=> retain refs for tag inspector

packages/malloy-render/src/component/table-layout.ts, packages/malloy-render/src/stories/tables.stories.ts, packages/malloy-render/src/stories/themes.stories.ts, packages/malloy/src/dialect/functions/all_functions.ts, packages/malloy/src/dialect/functions/sql.ts, packages/malloy/src/lang/ast/expressions/expr-aggregate-function.ts, packages/malloy/src/lang/ast/expressions/expr-func.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, packages/malloy/src/model/utils.ts, test/src/databases/all/expr.spec.ts
TODO:
(The join stuff is going to be disabled for now because it doesn't fully work with the compiler's join finder yet. We were thinking first step would be to disable it with an error, second step would be to fix it and re-enable.) 
Need to think about, for the future:
- Whether we want a real syntax for this rather than functions, e.g. `sql'MY SQL EXPRESSION'!number`
- Whether a user can specify an aggregate or analytic expression
=> WIP: SQL expression functions

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-duckdb/src/duckdb_common.ts, packages/malloy-db-duckdb/src/duckdb_connection.ts, packages/malloy-db-duckdb/src/duckdb_wasm_connection.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy/src/index.ts, packages/malloy/src/run_sql_options.ts, packages/malloy/src/runtime_types.ts
Provide a common constructor signature for Connection classes to simplify factories. The signature is now essentially
```
constructor<T extends ConnectionConfig>(config: T, optionsReader?: QueryOptionReader)
```
=> Common Connection constructor signature

packages/malloy/src/model/malloy_query.ts, test/src/databases/all/nomodel.spec.ts
Fixes https://github.com/malloydata/malloy/issues/1598
=> Fix bug where `count()` at root gets a distinct key unnecessarily

packages/malloy/src/dialect/dialect_map.ts, packages/malloy/src/dialect/functions/string_agg.ts, packages/malloy/src/dialect/functions/util.ts, packages/malloy/src/dialect/postgres/functions/string_agg.ts, packages/malloy/src/dialect/standardsql/functions/string_agg.ts, packages/malloy/src/lang/ast/expressions/expr-func.ts, packages/malloy/src/lang/ast/expressions/function-ordering.ts, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/test/expressions.spec.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, test/src/databases/all/functions.spec.ts
=> Bug fixes/improvements for string_agg

packages/malloy/src/lang/ast/view-elements/qop-desc-view.ts, packages/malloy/src/lang/ast/view-elements/reference-view.ts, packages/malloy/src/lang/ast/view-elements/view-arrow.ts, packages/malloy/src/lang/ast/view-elements/view-refine.ts, packages/malloy/src/lang/ast/view-elements/view.ts, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-tree-walkers/document-symbol-walker.ts, packages/malloy/src/lang/test/document-symbol-walker.spec.ts, packages/malloy/src/lang/test/lenses.spec.ts
Fixes https://github.com/malloydata/malloy/issues/1605
Bug: `nest: a + b + { order_by: a }` failed to compile with an error that `a` could not be found in the output space (when evaluating the `order_by`.
This was actually an unfortunate parsing error. The rule for nests was:
```g4
nestEntry
: tags fieldPath (PLUS vExpr)?    # nestExisting
| tags queryName isDefine vExpr   # nestDef
;
```
But this meant that `nest: a + b + { order_by: a }` would be parsed the same as `nest: a + (b + { order_by: a })`, which should make it clear why "`a` is not in the output space."
My solution is to change the rule for nests to:
```g4
nestEntry
: tags (queryName isDefine)? vExpr   # nestDef
;
```
This makes the `name is` part syntactically optional. Then, in the AST builder for the `nestDef`, we traverse …
=> Fix bug where `nest: a + b + { order_by: a }` could not look up `a`

packages/malloy/src/dialect/duckdb/duckdb.ts
support tables like `years_*.csv` in addition to `./years_*.csv`
=> Escape table names with wildcards and urls

packages/malloy/src/dialect/functions/all_functions.ts, packages/malloy/src/dialect/functions/sum_moving.ts, test/src/databases/all/functions.spec.ts
Fixes https://github.com/malloydata/malloy/issues/1492
Adds a `sum_moving` function similar to the `avg_moving` function:
Two overloads:
* `sum_moving(x, n)` — sum of `x` for the current row plus `n` preceding rows
* `sum_moving(x, n, m)` — sum of `x` for the current row plus `n` preceding rows and `m` following rows
=> Add `sum_moving` function

packages/malloy-db-duckdb/src/duckdb_connection.ts, packages/malloy/src/runtime_types.ts
Add support for loading the MotherDuck extension and providing a MotherDuck token. You can use MotherDuck databases now with:
```typescript
const connection = new DuckDBConnection({
name: 'duckdb',
databasePath: 'md:my_db',
motherDuckToken: '<motherduck_token>',
})
```
Also add the ability to specify additional extensions:
```typescript
const connection = new DuckDBConnection({
name: 'duckdb',
additionalExtensions: ['spacial']
})
```
=> Support MotherDuck

packages/malloy/src/lang/ast/expressions/expr-func.ts, packages/malloy/src/lang/doc/experimental.md, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/test/expressions.spec.ts, test/src/databases/all/functions.spec.ts
Also add the `aggregate_order_by` experiment for using `order_by` on an aggregate.
=> Allow `partititon_by` and `order_by` on analytic functions without the `partition_by` and `function_order_by` experiments

packages/malloy-db-duckdb/src/duckdb_connection.ts
Prevent going into the web login flow, because console text gets lost, make sure errors are exposed to the caller.
=> Error on MotherDuck if no token

packages/malloy-db-duckdb/src/duckdb_connection.ts
Do not throw errors here, because they happen asynchronously inside a constructor, they can never be caught, which will cause node to exit.
=> Don't throw uncatchable error

package-lock.json, packages/malloy-render/package.json, packages/malloy-render/src/component/render.ts, packages/malloy-render/src/component/table.ts
The VSCode Extension does not have great support for scrollable content within a cell output, so we have to implement our own solution for passing wheel events to the cell content vs. the notebook frame. In order to know when a wheel event over a cell should be consumed by the cell vs. the notebook, we need to know about the scroll position of the malloy table. We need to know whether the table is scrolled all the way to the top and/or the bottom. We can use this to then determine in VSCode whether the table has more room to scroll up/down, or if scrolling should resume on the notebook.
=> feat: expose table scroll

packages/malloy-db-bigquery/src/bigquery.spec.ts, packages/malloy-db-duckdb/src/duckdb.spec.ts, packages/malloy-db-duckdb/src/duckdb_wasm_connection.spec.ts, packages/malloy-db-postgres/src/postgres.spec.ts, packages/malloy-db-snowflake/src/snowflake_connection.spec.ts, packages/malloy-db-snowflake/src/snowflake_executor.spec.ts, test/package.json, test/src/databases/all/db_index.spec.ts, test/src/databases/all/expr.spec.ts, test/src/databases/all/join.spec.ts, test/src/databases/all/nomodel.spec.ts, test/src/databases/all/orderby.spec.ts, test/src/databases/all/time.spec.ts, test/src/databases/bigquery-postgres/multi_connection.spec.ts, test/src/databases/bigquery-postgres/streaming.spec.ts, test/src/databases/duckdb/duckdb.spec.ts, test/src/databases/duckdb/streaming.spec.ts, test/src/render/render.spec.ts, test/src/util/index.ts
This introduces `onlyIf()`, a utility function to allow a test to be skipped by conditional, while still allowing test runners to pick up the test signature. 
It also hardens `describeIfDatabaseAvailable()` so that the `describe()` returned can handle `describe.each()`s with empty input arrays.
Database tests in packages don't have access to the utils script so a mini skip header is used for those.
=> Fix support for running individual dbs

packages/malloy/src/lang/ast/expressions/apply.ts, packages/malloy/src/lang/ast/expressions/expr-compare.ts, packages/malloy/src/lang/ast/expressions/expr-granular-time.ts, packages/malloy/src/lang/test/expressions.spec.ts, packages/malloy/src/lang/test/test-translator.ts
Before this change, any comparison of a time field with granularity would treat the time result as a range. After this change, only the apply operator ( `?` ) will treat a granular time entity as a range
=> Only treat granular results as ranges with apply operator

packages/malloy-db-trino/src/trino_connection.ts, packages/malloy/src/dialect/trino/trino.ts
=> Trino: more test fixes.

packages/malloy-db-duckdb/src/duckdb.spec.ts, packages/malloy-db-duckdb/src/duckdb_common.ts
Add some schema parsing tests for DuckDBConnection to parallel the ones for TrinoConnection in order to create a template for SchemaDef output tests.
=> DuckDB schema parsing tests

test/src/databases/all/expr.spec.ts, test/src/util/db-jest-matchers.ts
`/` now means "match a record/struct field in a result column"
I also removed `-- debug` and replaced with `# test.debug` and prettied up the output
Docs for malloyResultMatches are now ...
```TypeScript
/**
* Jest matcher for running a Malloy query, checks that each row
* contains the values matching the template. If you only want to
* check the first row, use the first form. If you want to check
* multiple rows, use the second.
*
*     await expect('query').malloyResultMatches(runtime, {colName: colValue});
*     await expect('query').malloyResultMatches(runtime, [{colName: colValue}]);
*
*   * If you use an array, the number of rows in the result must match the rows in the match
*   * The empty match {} accepts ANY data, but will errror if there is not a row
*   * If the query is …
```
=> Add support for inline (records) in malloyResultMatcher

packages/malloy-db-trino/src/trino_connection.spec.ts, packages/malloy-db-trino/src/trino_connection.ts
Handle the case of arrays in arrays - `aa array(row(a double, b array(row(c integer, d varchar(60)))))` was getting parsed with a name of `aa array(row(a double, b ` and type of `array(row(c integer, d varchar(60)))))`, this makes sure we stop at the first `array(`
=> Fix double nested schema parsing

packages/malloy-db-duckdb/src/duckdb_wasm_connection.spec.ts, packages/malloy/src/dialect/duckdb/duckdb.ts, test/src/databases/duckdb/duckdb.spec.ts
For DuckDB, DuckDB WASM specifically. Workaround for https://github.com/malloydata/malloy/issues/1715
=> Cast decimal literal to DOUBLE

packages/malloy-db-snowflake/src/snowflake_executor.spec.ts, packages/malloy-db-snowflake/src/snowflake_executor.ts, packages/malloy/src/dialect/snowflake/snowflake.ts, test/snowflake/uploaddata.sql, test/src/databases/all/expr.spec.ts
- ensure output col names from snowflake are of same case as the malloy identifiers
- snowflake connection and executor tests succeed now
- add support for safe cast
- ensure safe cast expr test passes for snowflake
In Snowflake:
by default even if we have quotes it seems to have ALL_CAPS in output
but explicitly saying please do not ignore case (which is what we decided for malloy)
outputs match expected outputs (in terms of case)
=> [snowflake] enable snowflake safe cast when src type == string

packages/malloy/src/model/malloy_query.ts, test/src/databases/all/functions.spec.ts
See #1729, incorrectly computing analytic functions in deeply nested data.
=> wrap complex analytic functions in group_set

packages/malloy-render/src/index.ts
Exporting Malloy Render component props type so that frameworks / apps using typescript can use `<malloy-render />` with type safety
=> chore: export render types

packages/malloy-render/src/component/render.tsx
Previously, our malloy-render webcomponent would throw an error if you did not provide any results for it to render. However, this has made it hard to incorporate into components in certain frameworks (**cough** React **cough**) because of the way those frameworks handle instantiating and passing values to web components.
This PR adjusts the malloy-render webcomponent with a wrapper that will return an empty element if the results aren't provided, rather than throwing an error. That way, certain frameworks can create the web component instance and attach it to the DOM before passing along initial properties without any error throwing issues.
=> feat: allow incomplete render

packages/malloy-db-duckdb/src/duckdb_connection.ts
Windows users have reported having to manually set `MOTHERDUCK_TOKEN`, so set it as well when a token is passed in.
=> Set both token cases

packages/malloy-render/src/component/render-numeric-field.ts, packages/malloy-render/src/data_styles.ts, packages/malloy-render/src/html/duration.ts, packages/malloy-render/src/stories/basic.stories.ts, packages/malloy-render/src/stories/static/basic.malloy, packages/malloy-render/src/stories/static/tables.malloy
Adds:
- ability to format a duration when the `# number` tag is included
- ability to list durations in a terse format using `# duration.terse`
Fixes:
- if bad duration name is supplied, it is ignored and the default duration (seconds) is used
Cleanup:
- extracts duration functions into 1 place and exports them for re-use across both old and new renderer
Old renderer
New renderer
=> feat: duration formatting

packages/malloy-render/src/component/render-webcomponent.ts
Throw a warning when malloy-render is accidentally loaded twice, instead of throwing an error. Developers should avoid situations where the component library is instantiated twice but its not always a show stopper
=> fix: warn when malloy-render already exists

packages/malloy/src/dialect/snowflake/snowflake.ts, packages/malloy/src/dialect/trino/trino.ts, test/src/databases/all/nomodel.spec.ts
We were getting some weird casting numeric problems.  We now do all calculations as integers and avoid overflows.
=> rewrite symmetric aggregate implementation

packages/malloy/src/lang/ast/expressions/expr-func.ts, packages/malloy/src/lang/ast/expressions/pick-when.ts, packages/malloy/src/lang/parse-log.ts, packages/malloy/src/lang/test/parse.spec.ts, test/src/databases/all/expr.spec.ts
As mentioned in  #1787 this adds the ability for an error message to contain a link to a longer error explanation.
- If an error messages ends with `[xxx]` then the `xxx` is extracted and added to the log entry as an error code
- Error message explanations will be added to https://docs.malloydata.dev/documentation/error_dictionary, since each section of the markdown file has a target, the target portion of the url is the "error code" which should be added to the message
- The VS Code extension is modified to display errors which contain a code, with a link to the error dictionary containing the target.
For example
```TypeScript
this.log(
`pick type '${whenType}', expected '${returnType.dataType}'[pick-values-must-match]`
);
```
```Markdown
The types of each `pick` (and the `else` if it is …
```
=> Add the ability for errors messages to link to error explanations

package-lock.json, packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-duckdb/src/duckdb_common.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy-db-snowflake/src/snowflake_connection.ts, packages/malloy-db-trino/package.json, packages/malloy-db-trino/src/trino_connection.ts, packages/malloy/src/lang/ast/expressions/expr-cast.ts, packages/malloy/src/lang/ast/types/expression-def.ts, packages/malloy/src/lang/ast/types/space-field.ts, packages/malloy/src/lang/test/expressions.spec.ts, packages/malloy/src/lang/test/field-symbols.spec.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts
Fixes https://github.com/malloydata/malloy/issues/1781
I picked `Unsupported SQL native type 'XXX'` to describe the type, and added an entry to the error dictionary -- https://github.com/malloydata/malloydata.github.io/pull/176
=> rename unsupported to "sql native"

packages/malloy-render/src/html/link.ts
Often in an HTML table you want to link to some external resource.  This simple mechanism allows create linkage in the result table with simple text substitution.
```
run: flights -> {
// by default appends to the end of the template
group_by: origin_code
// can also do substitution. $$ is replaced.
// link.url_template="" and link{url_template=""} are equivalent
group_by: carrier
}
```
=> Rendering link Templates.

packages/malloy-render/src/html/link.ts, packages/malloy-render/src/html/utils.ts, packages/malloy-render/src/stories/link.stories.ts, packages/malloy-render/src/stories/static/image.malloy, packages/malloy-render/src/stories/static/link.malloy, test/src/render/render.spec.ts
- Changes the `field` ref in tags to use / paths
- Updates link tag to optionally use `field` lookups for the href component, both for full URL and templated URL
=> feat: path fields in render tags

packages/malloy-render/src/html/html_view.ts
Removes auto importing of webcomponent.
If you want support for new renderer but are using the old HTML view like:
```
import {HTMLView} from "@malloydata/render";
```
You now need to explicitly add an import for the webcomponent like so:
```
import {HTMLView} from "@malloydata/render";
import "@malloydata/render/webcomponent";
```
If you do not import this and you try to use new renderer via `## renderer_next`, the legacy renderer will show and a console warning will appear about not finding the new renderer component
=> feat: dont auto import webcomponent

packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-tree-walkers/document-symbol-walker.ts, packages/malloy/src/lang/test/parameters.spec.ts
Makes a new shortcut for joining with parameters:
```malloy
source: my_source(param is 1) is ... {
join_one: other_source(param) on 1 = 1
// equivalent to / shorthand for:
join_one: other_source is other_source(param) on 1 = 1
// equivalent to / shorthand for:
join_one: other_source is other_source(param is param) on 1 = 1
}
```
=> Add join with parameters shortcut

.github/workflows/main.yaml, packages/malloy-render/package.json, packages/malloy-render/src/component/apply-renderer.tsx, packages/malloy-render/src/component/register-webcomponent.ts, packages/malloy-render/src/component/render-link.tsx, packages/malloy-render/src/html/html_view.ts, packages/malloy/src/lang/ast/expressions/expr-id-reference.ts, packages/malloy/src/lang/ast/parameters/has-parameter.ts, packages/malloy/src/lang/ast/query-elements/query-head-struct.ts, packages/malloy/src/lang/ast/query-elements/query-reference.ts, packages/malloy/src/lang/ast/source-elements/named-source.ts, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/expr.spec.ts
Linting in CI got overlooked when moving from CloudBuild to Github Actions, fix that and some things that have crept in.
=> Restore linting in CI

packages/malloy-render/src/component/render-list.tsx, packages/malloy-render/src/component/render-result-metadata.ts, packages/malloy-render/src/component/table/table-layout.ts, packages/malloy-render/src/component/table/table.css, packages/malloy-render/src/component/table/table.tsx, packages/malloy-render/src/component/types.ts, packages/malloy-render/src/component/util.ts, packages/malloy-render/src/stories/static/image.malloy, packages/malloy-render/src/stories/static/list.malloy, packages/malloy-render/src/stories/static/tables.malloy, packages/malloy-render/src/stories/tables.stories.ts
Rearchitects the table renderer using CSS Subgrids instead of nested tables. The benefits:
- No longer need to hardcode column widths so that nested tables match; subgrid CSS handles this so everything can be autosized
- Works more effectively with sticky cells; now we can have text/numeric cells pin as a user scrolls a deeply nested structure
- Allows the removal of extra cell elements like our cell gutters, which were necessary due to the idiosyncrasies of table elements
This PR also adds the ability to manually width columns using presets or hardcoded pixels like so:
```
a_med_width_col
a_300px_col
```
=> feat: nested table as subgrids

packages/malloy-render/src/component/apply-renderer.tsx, packages/malloy-render/src/component/dashboard/dashboard.css, packages/malloy-render/src/component/dashboard/dashboard.tsx, packages/malloy-render/src/component/register-webcomponent.ts, packages/malloy-render/src/component/render-result-metadata.ts, packages/malloy-render/src/component/render.tsx, packages/malloy-render/src/component/table/table-context.ts, packages/malloy-render/src/component/table/table-layout.ts, packages/malloy-render/src/component/table/table.css, packages/malloy-render/src/component/table/table.tsx, packages/malloy-render/src/component/types.ts, packages/malloy-render/src/component/util.ts, packages/malloy-render/src/stories/dashboard.stories.ts, packages/malloy-render/src/stories/static/dashboard.malloy
- Implements dashboard renderer in renderer_next
- Moves FieldHeaderRangeMap calcs from Result Metadata to TableLayout, because it should be specific to tables which can nested within a larger data structure being rendered as say, a dashboard
- Adds auto field name renaming, per feedback from @lloydtabb 
- Adds support for hidden fields in renderer_next tables
New dashboards:
https://github.com/user-attachments/assets/6f850fc5-bce5-421c-82de-251db1f6c62c
=> feat: dashboards, hidden fields, rename columns

packages/malloy-render/src/component/table/table.css, packages/malloy-render/src/component/table/table.tsx
- uses an IntersectionObserver to detect pinning instead of a scroll event. This allows us to detect pinning even if the scrolling container is a parent of the table rather than the table container itself
- exports CSS part for the table container, so that you can override the scroll behavior
The above changes are needed to support embedding the renderer_next in VSCode output cells while enabling proper scrolling
=> feat: better pinned detection

packages/malloy-render/src/html/html_view.ts
Flips the renderer tags so now the official renderer is the new renderer, and the legacy one requires a model tag of `## renderer_legacy`
=> feat: flip renderer tag

packages/malloy/src/model/utils.ts, test/src/databases/all/time.spec.ts
```
days(@2001 to @2002) => 365
floor(days(@2001 to @2002)) => 0
```
... due to a bug in function expression walker where the the rhs of the diff is replaced with the lhs
=> Passing a timeDiff to a function always returns zero

packages/malloy-render/src/component/table/table.css, packages/malloy-render/src/component/table/table.tsx
When limiting nested table rows, show a placeholder row at the bottom indicating that the data was limited
=> feat: row limit banner

packages/malloy-render/package.json, packages/malloy-render/src/component/apply-renderer.tsx, packages/malloy/src/malloy.ts
If fromISO date parsing fails, we can try falling back to fromSQL. This should properly parse systems like Presto
The `applyRenderer` file change has to do with handling null values, not specifically about fixing time issues although will prevent us from bombing out if a timestamp field has a null value in it.
=> feat: fallback to fromSQL date parsing

packages/malloy/src/lang/ast/query-items/field-declaration.ts, packages/malloy/src/lang/test/expressions.spec.ts
```
// TODO this should work for dates too
if (isGranularResult(exprValue) && template.type === 'timestamp') {
```
Not my finest hour :)
=> add timeframes to truncated dates

packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/duckdb/duckdb.ts, packages/malloy/src/dialect/duckdb/functions/dialect_functions.ts, packages/malloy/src/dialect/postgres/functions/dialect_functions.ts, packages/malloy/src/dialect/postgres/postgres.ts, packages/malloy/src/dialect/snowflake/functions/dialect_functions.ts, packages/malloy/src/dialect/snowflake/snowflake.ts, packages/malloy/src/dialect/standardsql/functions/dialect_functions.ts, packages/malloy/src/dialect/standardsql/standardsql.ts, packages/malloy/src/dialect/trino/functions/dialect_functions.ts, packages/malloy/src/dialect/trino/trino.ts, packages/malloy/src/lang/ast/expressions/expr-func.ts, packages/malloy/src/lang/ast/types/dialect-name-space.ts, packages/malloy/src/lang/ast/types/malloy-element.ts, packages/malloy/src/lang/test/query.spec.ts, test/src/databases/all/functions.spec.ts
This adds a new namespace underneath the global namespace, which dynamically contains function definitions specific to the current dialect.
This PR does not add very many function definition, just sets the groundwork for it.
There are no name conflicts between the "global" namespace (where Malloy standard functions live) and this dialect namespace. If there were, you would always get the global version, since they are always stacked and there is no way to explicitly access one namespace or another. The intent is that in the future, you can explicitly reference `dialect.function_name` to access the conflicting version — e.g. `dialect.starts_with(x, "prefix")` would give you three-state boolean null behavior rather than the "Malloy standard" two-state boolean null behavior.
=> Add dialect namespace with dialect functions

packages/malloy/src/dialect/postgres/postgres.ts, packages/malloy/src/dialect/snowflake/snowflake.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/expr.spec.ts
In Presto,   the code below would fail because we complicate joining of sources with where clauses always using the the more complex path to avoid SQL errors.
We now just use the simple path for Presto but we probably need to add better error checking or another strategy.  See the notes in the code.  
This is a blocker so I'm going to land and revisit.
```
source: sf is ${databaseName}.table('malloytest.state_facts') extend {
measure: state_count is count()
primary_key: state
}
source: al is sf extend {where: state = 'AL'}
source: a is sf extend {
where: state ~ 'A%'
join_one: al with state
}
source: allx is sf extend {
join_one: a with state
}
// # test.debug
run: allx -> {
aggregate:
allx is state_count
a is a.state_count
al is a.al.state_count
```
=> Joined filtered Sources

test/src/databases/streaming/streaming.spec.ts
Tests were relying on natural table order which changed when I cloned the table into our new test db.
=> Make streaming test deterministic

packages/malloy/src/model/malloy_query.ts, test/src/databases/all/expr.spec.ts, test/src/tags.spec.ts
Reverts malloydata/malloy#1912
This approach does not work with joined fields
```
it('bug with wrong join being used with annotation', async () => {
await expect(`
run: aircraft -> {
group_by: aircraft_models.seats
}
`).malloyResultMatches(expressionModel, {
seats: 0,
});
});
```
=> Revert "Fix issue where nested fields of the same field overwrite their tag"

packages/malloy/src/malloy.ts, test/src/databases/duckdb/materialization.spec.ts
The refactor I was trying to describe is really hard to explain so I just did it...
The philosophy: the runtime API has two kinds of things, "Malloy entities" and "Malloy entity materializers" (e.g. `Model` vs `ModelMaterializer`). The Malloy entities contain nothing more than the result of compiling that entity. The materializers contain runtime information needed to re-compile, run, etc.. Therefore, it didn't fit the philosophy for a `PreparedQuery` (which just represents the internal `Query` IR object) have a `replaceMaterializedReferences` property, since this is a description of _how_ you want to compile the SQL, not _what_ the query is.
I will add comments to all the code changes to describe in more detail the philosophy.
=> Move `replaceMaterializedReferences` outside of `PreparedQuery`

packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, test/src/databases/duckdb/reference-id.spec.ts
Each field in a result will now have a `referenceId` in the `resultMetadata`. This id should be the same for fields which are references to the same definition. Fields which are inline definitions in the query also get a reference id, it will just be unique.
=> Add a unique reference ID to resultMetadata

packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-log.ts, packages/malloy/src/lang/test/source.spec.ts
User reported confusion at getting an error on `join_many: .. with` and the user was correctly confused, no reason to disallow that.
=> allow join_many: with

packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-log.ts, packages/malloy/src/lang/test/source.spec.ts
The work was based on a mis-understanding of a comment from lloyd which made me believe this was trivial and OK
This reverts commit 9f3b0dbdf3a3e1e6cfea40b74fc07615adbb194f.
There is a desire for a future where a "key only" join could exist and be a many or a one join based on the sources involved. Someday that discussion will happen. For now, backing the wrong thing out.
=> Revert "allow join_many: with (#1950)"

test/bin/postgres_init.sh
Initialize the expected `tsm_system_rows` when creating the test database. I tested that this survives `postgres_stop.sh`, `postgres_start.sh` and is repeatable over multiple `postgres_init.sh` invocations.
=> Init required extension

packages/malloy/src/lang/ast/expressions/expr-cast.ts, packages/malloy/src/lang/parse-log.ts, test/src/databases/all/expr.spec.ts
Reviewing the MySQL dialect I realized we throw at compile if a dialect doesn't support safe cast, but this is already a dialect property, and so the translator should flag these errors.
=> error at translation time on unsafe cast

packages/malloy-render/src/component/table/table-layout.ts, packages/malloy-render/src/component/table/table.css, packages/malloy-render/src/component/table/table.tsx, packages/malloy-render/src/stories/tables.stories.malloy
Force table to fill entire width of container with tag:
```
view: my_table
```
=> feat: full width table

packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/test/parse.spec.ts
Adding this rule to the grammar ...
```
closeCurly
: CCURLY
| { this.notifyErrorListeners("'{' missing a '}'"); }
;
```
Makes turns this error message ...
```
line 2: extraneous input '<EOF>' expecting {AGGREGATE, CALCULATE, DECLARE, DIMENSION, EXTENDQ,
GROUP_BY, HAVING, INDEX, JOIN_CROSS, JOIN_ONE, JOIN_MANY, LIMIT, MEASURE, NEST, ORDER_BY,
PROJECT, QUERY, RUN, SAMPLE, SELECT, SOURCE, TOP, WHERE, VIEW, TIMEZONE, ALL, AVG, CASE, CAST,
COUNT, DAY, EXCLUDE, FALSE, HOUR, IS, MAX, MIN, MINUTE, MONTH, NOT, NOW, NULL, PICK, QUARTER,
SECOND, SOURCE_KW, SUM, TABLE, TRUE, WEEK, YEAR, HACKY_REGEX, SQ_STRING, DQ_STRING,
BQ_STRING, DOC_ANNOTATION, ANNOTATION, '(', '[', '{', '}', '-', ';', LITERAL_TIMESTAMP, LITERAL_HOUR,
LITERAL_DAY, LITERAL_QUARTER, LITERAL_MONTH, LITERAL_WEEK, LITERAL_YEAR, …
```
=> add experimental rule to catch missing close brace

packages/malloy-render/src/component/dashboard/dashboard.tsx, packages/malloy-render/src/component/table/table.tsx, packages/malloy-render/src/stories/line_charts.stories.malloy
There is a bug in tanstack-virtual where if using max-height for a scroll container, measurement updates don't properly update cache and elements will be missing if the the total size ends up being under the max height of the container.
https://github.com/TanStack/virtual/issues/869
This workaround is to set an arbitrarily large initial height for elements, which seems to avoid the bug where some items are not drawn.
=> fix: table virtual scroll bug with missing items

packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/test/document-symbol-walker.spec.ts
If a `}` appears in column zero, the parser stopIndex appears as both the end of the second to the last line and the beginning of the last line.
So for
```
run: flights -> {
group_by: carrier
}
```
the values in `MalloyTranslation.rangeFromTokens()` are:
```
> stopToken.stopIndex
38
> this.parseStep.sourceInfo.at
(3) [{…}, {…}, {…}]
0 = {begin: 0, end: 18}
1 = {begin: 18, end: 38}
2 = {begin: 38, end: 39}
```
It appears that end is meant to be exclusive.
This didn't show up in any of our existing test cases because if there is a space before the `}` which just happens to be how we formatted all the test Malloy, then `stopIndex` is unambiguously on one line.
=> Fix multiline lens range

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-duckdb/src/duckdb.spec.ts, packages/malloy-db-duckdb/src/duckdb_common.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy-db-snowflake/src/snowflake_connection.ts, packages/malloy-db-trino/src/trino_connection.spec.ts, packages/malloy-db-trino/src/trino_connection.ts, packages/malloy/src/dialect/postgres/postgres.ts, packages/malloy/src/dialect/snowflake/snowflake.ts, packages/malloy/src/doc/fielddef.md, packages/malloy/src/index.ts, packages/malloy/src/lang/ast/expressions/expr-aggregate-function.ts, packages/malloy/src/lang/ast/expressions/expr-array-literal.ts, packages/malloy/src/lang/ast/expressions/expr-record-literal.ts, packages/malloy/src/lang/ast/field-space/reference-field.ts, packages/malloy/src/lang/ast/field-space/static-space.ts, packages/malloy/src/lang/ast/query-items/field-declaration.ts, packages/malloy/src/lang/ast/source-properties/join.ts, packages/malloy/src/lang/ast/typedesc-utils.ts, packages/malloy/src/lang/test/field-symbols.spec.ts, packages/malloy/src/lang/test/imports.spec.ts, packages/malloy/src/lang/test/query.spec.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/composite_source_utils.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, test/src/databases/all/compound-atomic.spec.ts
Made the TypeDefs for these not be StructDefs
in anticipation of using this in function value typing
=> refactor TypeDef for arrays and records

packages/malloy-db-trino/src/trino_connection.ts, packages/malloy/src/dialect/snowflake/snowflake.ts, packages/malloy/src/doc/fielddef.md, packages/malloy/src/index.ts, packages/malloy/src/lang/ast/expressions/expr-aggregate-function.ts, packages/malloy/src/lang/ast/expressions/expr-time-extract.ts, packages/malloy/src/lang/ast/expressions/expr-time.ts, packages/malloy/src/lang/ast/expressions/time-literal.ts, packages/malloy/src/lang/ast/field-space/static-space.ts, packages/malloy/src/lang/ast/query-builders/reduce-builder.ts, packages/malloy/src/lang/ast/typedesc-utils.ts, packages/malloy/src/lang/ast/types/expression-def.ts, packages/malloy/src/lang/ast/view-elements/reference-view.ts, packages/malloy/src/lang/test/field-symbols.spec.ts, packages/malloy/src/lang/test/imports.spec.ts, packages/malloy/src/lang/test/query.spec.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/composite_source_utils.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts
I checked in before I did a scan for cleanliness and then I found some things later.
=> Typedef cleanup cleanup

packages/malloy-render/src/component/table/table.tsx
Avoid clashes between navigation and drilling.
=> Don't drill link renderers

packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/trino/dialect_functions.ts, packages/malloy/src/dialect/trino/trino.ts, test/src/databases/all/functions.spec.ts, test/src/databases/presto-trino/presto-trino.spec.ts
Added functions
* hll_accumulate(scalar) - aggregate function, build an hll counter
* hll_combine(hll_counter) - aggregate function, combine HLL counters
* hll_estimate(hll_counter) - convert a HLL counter to a number
* hll_export(hll_counter) - export a HLL counter into BINARY (for storage)
* hll_import(binary) - import (from storage) an HLL counter.
```
run: presto.table('malloytest.state_facts') -> {
aggregate:
state_count is hll_estimate(hll_accumulate(state))
```
```
run: presto.table('malloytest.state_facts') -> {
group_by: state
aggregate: names_hll is hll_accumulate(popular_name)
} -> {
aggregate: name_count is hll_estimate(hll_combine(names_hll))
}
```
```
CREATE TABLE foo as %{
x -> {group_by: state, aggregate: name_hll is hll_export(hll_accumulate(popular_name)) 
}%
```
``` …
```
=> added some basic hyperloglog functions

packages/malloy/src/lang/test/expressions.spec.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/functions.spec.ts
This adds a (temporary!) compiler flag `##! unsafe_complex_select_query` which removes an error-checking condition in the compiler where if "complex SQL" was ever generated for a `select` it would throw an error. This was probably once reasonable when the only way you could generate complex SQL was when there were nests, but now it can also happen if you use window functions. This is locked behind a compiler flag because this error checking condition still does catch some incorrect cases, and to handle both properly, there is a more involved long-term fix. See https://github.com/malloydata/malloy/issues/1604.
=> Fix issue where BQ refused to generate "complex SQL" for a select

packages/malloy/src/dialect/duckdb/dialect_functions.ts, packages/malloy/src/dialect/functions/README.md, packages/malloy/src/dialect/functions/malloy_standard_functions.ts, packages/malloy/src/dialect/functions/util.ts, packages/malloy/src/dialect/mysql/dialect_functions.ts, packages/malloy/src/dialect/postgres/dialect_functions.ts, packages/malloy/src/dialect/snowflake/dialect_functions.ts, packages/malloy/src/dialect/standardsql/dialect_functions.ts, packages/malloy/src/dialect/trino/dialect_functions.ts, packages/malloy/src/dialect/trino/function_overrides.ts, test/src/databases/all/expr.spec.ts, test/src/databases/presto-trino/presto-trino.spec.ts
I pushed #2051 early to catch a release train so there would be an alpha available. Finishing up here.
* repeat and reverse are no longer in the standard library
* string_reverse is added to the standard library
* repeat and reverse are now in each dialects dialect library, with dialect specific semantics
In general, because some dialects have few or no functions supporting arrays, at this time, there will not be any further array functions in the standard library. We need a re-think of the standard library before that happens.
=> More cleanup of array functions

packages/malloy-render/package.json
Eg "npm run storybook-windows".  The unix version fails on a windows machine.
=> Added the windows equivalent command to the unix storybook script. 

packages/malloy-render/DEVELOPING.md, packages/malloy-render/src/component/line-chart/generate-line_chart-vega-spec.ts, packages/malloy-render/src/stories/line_charts.stories.malloy
This PR adds support for boolean (x-axis) for line charts.  See:
https://www.internalfb.com/tasks/?t=211025161  (for the Malloy team)
https://github.com/malloydata/malloy/issues/104  (an older, but related issue)
Still to do:
- null values are still missing from the legend.  That will be a separate fix.
- bar charts seem to have the same issue with booleans.
=> Added an initial fix for broken line charts when the x dimension is boolean

package.json, packages/malloy-db-snowflake/src/snowflake_connection.spec.ts, packages/malloy-db-snowflake/src/snowflake_connection.ts, packages/malloy-db-snowflake/src/snowflake_executor.ts, packages/malloy/src/dialect/snowflake/snowflake.ts
These are the changes from #2072 and #2074 and #2088
Working on our external PR process so we don't have to do this again
=> Merge contributions manually

demo/malloy-duckdb-wasm/README.md, packages/malloy-db-snowflake/src/snowflake_connection.spec.ts, packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/mysql/mysql.ts, packages/malloy/src/lang/ast/expressions/expr-compare.ts, packages/malloy/src/lang/ast/expressions/expr-not.ts, packages/malloy/src/lang/ast/expressions/expr-null.ts, packages/malloy/src/lang/ast/types/expression-def.ts, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/test/expressions.spec.ts, packages/malloy/src/lang/test/parameters.spec.ts, test/src/databases/all/composite_sources.spec.ts, test/src/databases/all/expr.spec.ts, test/src/databases/all/functions.spec.ts, test/src/databases/all/nomodel.spec.ts, test/src/databases/all/parameters.spec.ts, test/src/databases/bigquery/malloy_query.spec.ts, test/src/databases/bigquery/nested_source_table.spec.ts, test/src/databases/duckdb/nested_source_table.spec.ts, test/src/databases/duckdb/streaming.spec.ts
1) `= NULL` and `!= NULL` are deprecated
2) `IS NULL` and `IS NOT NULL` are official
3) `!=` and `!~` return true if either argument `is null`
4) `not x` returns true if `x is null`
5) Added partials for `is null` and `is not null` for the sake of pick statements
=> Finalize NULL related decisions

.github/workflows/db-bigquery.yaml, .github/workflows/db-duckdb-wasm.yaml, .github/workflows/db-duckdb.yaml, .github/workflows/db-motherduck.yaml, .github/workflows/db-mysql.yaml, .github/workflows/db-postgres.yaml, .github/workflows/db-presto.yaml, .github/workflows/db-snowflake.yaml, .github/workflows/db-trino.yaml, .github/workflows/main.yaml, .github/workflows/run-tests.yaml, CONTRIBUTING.md
This grants external PRs access to secrets in order to be able to run database tests. For security purposes external PRs will not automatically run tests, tests must be triggered by someone with write permissions to the repo (the core Malloy team).
This changes the names of the tests that are run, so older PRs will need to be updated to include these changes in order to pass the required test checks.
=> Update PR tests to use pull_request_target

packages/malloy-db-duckdb/src/duckdb.spec.ts, packages/malloy/src/dialect/duckdb/duckdb.ts, packages/malloy/src/dialect/tiny_parser.ts
There's a blog post with an example where a STRUCT(x UUID) field exists and the type parser for duckdb did not properly handle that.
Fixed the bug and added the missing test that should have existed.
=> fix for STRUCT() with unknown fields in duckdb

packages/malloy/src/lang/ast/field-space/query-spaces.ts, packages/malloy/src/lang/test/query.spec.ts
In this kind of construction:
```
source: a_2 is a extend { join_one: b is b extend {
join_one: c is b on 1 = c.ai
} with astr }
run: a_2 -> {
nest: x is {
group_by: ai is b.c.ai
}
}
```
I was computing the wrong join usage (which is used for the composite sources feature). Specifically, it was making it out that `ai is b.c.ai` used joins `b.c` as well as `c` (unqualified). Then when the nest was evaluated in the outer query, it tried to figure out what `c` was (unqualified), and that doesn't exist.
=> Fix issue with referencing field in doubly-nested join inside a nest

packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, test/src/core/api.spec.ts
When calling `getPreparedResult`, `loadPreparedResult`, or `run`, you can now pass in `defaultRowLimit` option. This will change the compiled SQL to have a row limit on the last stage if one is not already present.
=> Add `defaultRowLimit` parameter when compiling queries

packages/malloy-db-trino/src/trino_connection.ts
the odd way the meta connection is built makes the sharing work better if the explain parser is a static method on the open source presto connection
=> make schema explain shareable

packages/malloy-db-bigquery/src/bigquery.spec.ts, packages/malloy-db-snowflake/src/snowflake_connection.spec.ts, packages/malloy-render/src/stories/util.ts, packages/malloy/src/index.ts, packages/malloy/src/malloy.ts, packages/malloy/src/runtime_types.ts, test/src/core/multi_connection.spec.ts, test/src/databases/duckdb/model-caching.spec.ts, test/src/databases/duckdb/model_caching.spec.ts, test/src/runtimes.ts
Changes:
* Changes constructor of `Runtime` (and related subclasses) to take an object with named things, rather than an arbitrary list of things: `new Runtime({ urlReader, connections })`
* Changes `Malloy.compile` to allow you to pass in a `url: URL` or `source: string` directly, rather than having to first call `Malloy.parse`. Therefore, you only need to use `Malloy.parse` if you only want to parse. If you always want to compile, you may as well use `Malloy.compile`.
* Adds a new thing you can give to a runtime, `CacheManager`, which maintains the information needed to interact with a `ModelCache` which is an async map from `URL` to `{modelDef: ModelDef; invalidationKeys: {[url: string]: InvalidationKey}}`, where `invalidationKeys` should be the set of invalidation keys for all the …
=> Add model caching capability to Runtime

test/presto/presto_start.sh, test/trino/trino_start.sh
Allow setting of port and have different file names because docker won't mount the same host file in two running containers. Also fail fast if errors occur instead of polling out.
=> Allow Presto and Trino to run at the same time

packages/malloy-render/src/component/render-numeric-field.ts
This line was erroring when queries returned null numerics:
Cannot read properties of undefined (reading 'toLocaleString')
See T214044108 for details
=> Improved handling of null or non-numeric values.

.github/workflows/run-tests.yaml
After all the excitement of completely restructuring our test builds I didn't make the actual final cut over to pull_request_target
=> Really switch to pull_request_target

packages/malloy-db-snowflake/src/snowflake_connection.ts, packages/malloy/src/dialect/snowflake/snowflake.ts
* asymm aggregates: cast the field to int (to prevent float arithmetic from throwing off the computation)
* combine nested fields that are decimal, float, double etc.
=> Snowflake fixes

packages/malloy-db-trino/src/trino_connection.ts
In order to provide a good user experience in the new Trino and Presto connection editors, we need the `test` functionality to actually work.
Implement that for the `TrinoPrestoConnection`.
Associated with https://github.com/malloydata/malloy-vscode-extension/issues/589
Example:
=> Implement the test functionality for trino connections

packages/malloy/src/lang/syntax-errors/custom-error-messages.ts, packages/malloy/src/lang/syntax-errors/malloy-parser-error-listener.ts, packages/malloy/src/lang/test/syntax-errors.spec.ts
Fixes https://github.com/malloydata/malloy/issues/34
I added a helpful error message: "'aggregate:' entries must include a name (ex: `some_name is count()`)"
Add an error message rewriter for the case:
```
run: x -> {
aggregate: count()
}
```
**Was:**
**Now:**
I also wanted to make sure we could support the aggregate error even when it is nested inside of a view. To do so, we couldn't rely on the same logic because the parser fails to parse the entire `view:` clause. Instead, I added a new error rewriter option `lookbackFromOffendingSymbol` that lets us do relative sequence comparisons from the token associated with the error, rather than the token associated with the parser's current position. The Malloy grammar has a lot of ambiguity that is resolved by lookahead logic in the ATN and so …
=> Add a custom error message for a missing alias after 'aggregate:'

packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/standardsql/standardsql.ts, packages/malloy/src/lang/grammar/MalloyLexer.g4, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-log.ts, packages/malloy/src/lang/test/expressions.spec.ts, packages/malloy/src/lang/test/literals.spec.ts, packages/malloy/src/lang/test/parse-expects.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/expr.spec.ts
This implements [WN-0020](https://github.com/malloydata/whatsnext/blob/main/wns/WN-0020-like-escape/wn-0020.md)
=> Allow escaping of % and _ in LIKE strings

packages/malloy/src/index.ts
Used by the composer and extension for now.
=> Export annotationToTaglines

packages/malloy-query-builder/README.md, packages/malloy-query-builder/src/query-ast.spec.ts, packages/malloy-query-builder/src/query-ast.ts
- Field references in `ASTOrderByViewOperation`s were resolving themselves in the segment input schema, when they should resolve themselves in the output schema
- Getting the output schema of an `ASTView` resulted in an infinite loop if it contained an `ASTRefinementViewDefinition`.
- Adds `ASTQuery.fieldWasCalculation(fieldInfo)` to determine whether an output field was a calculation (measure)
=> Query builder bug fixes

packages/malloy/src/api/sessioned.spec.ts, packages/malloy/src/api/sessioned.ts
I feel pretty silly for overlooking this... 
If two clients tried to compile the same model, they would share the same session and stomp on each other.
So now the methods all accept a `session_id` parameter. This is required to reuse a session. In the first call, don't pass a `session_id` (or if you do and it doesn't correspond to a session, it will be ignored). The first response (and all subsequent responses) will have a `session_id` that you can use to keep the session state.
---
Also changed: `ttl` in subsequent requests is no longer ignored, and will cause the expiry date to update. This allows TTL to be used like a "maximum allowed time between requests" feature by always passing e.g. `{ seconds: 5 }`.
=> API: Handle race condition with multiple sessions compiling the same source/model/query

packages/malloy-db-trino/src/trino_connection.ts
Add extra field to Trino connector for passing extra values
This field allows us to pass extra values like extraHeaders, SSL, and can support additional fields in the future.
=> add extra fields to the trino connector

packages/malloy-interfaces/src/index.ts, packages/malloy-interfaces/src/nest_unions.spec.ts, packages/malloy-interfaces/src/to_malloy.ts, packages/malloy-interfaces/src/types.ts, packages/malloy-interfaces/thrift/malloy.thrift, packages/malloy-query-builder/README.md, packages/malloy-query-builder/src/query-ast.spec.ts, packages/malloy-query-builder/src/query-ast.ts, packages/malloy/src/api/asynchronous.spec.ts, packages/malloy/src/api/core.ts, packages/malloy/src/api/sessioned.spec.ts, packages/malloy/src/api/stateless.spec.ts, packages/malloy/src/lang/malloy-parse-info.ts, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/malloy-to-stable-query.ts, packages/malloy/src/lang/parse-log.ts, packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/parse-tree-walkers/model-annotation-walker.ts, packages/malloy/src/lang/run-malloy-parser.ts, packages/malloy/src/lang/syntax-errors/malloy-parser-error-listener.ts, packages/malloy/src/lang/test/malloy-to-stable-query.spec.ts, packages/malloy/src/lang/utils.ts
Adds a function `malloyToQuery` (name is not final), which converts Malloy code into a `Malloy.Query` (from `@malloydata/interfaces`). This runs the real parser with a different parse tree walker.
Where clauses (in both views and filtered aggregates) are not implemented, because the Malloy syntax for filter string filters has not been implemented.
This also changes the thrift interface for queries slightly. Arrow queries can now have a source which is query refinement (e.g. `run: (cool_query + { group_by: x }) -> { group_by: y }`). The query builder `QueryAST` data structure has been updated to account for this.
=> Implement parser for Malloy.Query

test/presto/example_presto.malloy, test/trino/example_trino.malloy
While testing the connection editors for trino and presto, I built small malloy files I could use for manual testing. I figured it would be useful to check in for future use cases, because I could not find any other `trino` or `presto` connections represented in our repos or documentation.
=> Add two minimal .malloy test files for presto and trino

packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/mysql/mysql.ts, packages/malloy/src/dialect/standardsql/standardsql.ts, packages/malloy/src/lang/test/sql-block.spec.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/db_filter_expressions.spec.ts, test/src/databases/all/nomodel.spec.ts, test/src/databases/all/orderby.spec.ts, test/src/databases/bigquery/wildcard_table_names.spec.ts
We are missing some rigor here and it bit me when writing some tests for a different feature.
Here is the behavior which we do NOT consistently implement, but which I am going to make all dialects implement.
1) `NULL` is last in all queries under all circumstances and it is impossible to ever change this
2) In a reduce query without any ordering
* If there is an aggregate field, the ordering is that field, descending
* else if there is a string field, the ordering is that field ascending
* else if there is a time field, the ordering is that field ascending
* else no order is generated except that NULLS are last, like all queries
=> order_by: and NULL ... make all dialects do the same thing

packages/malloy-filter/src/filter_interface.ts, packages/malloy-filter/src/nearley_parse.ts, packages/malloy/src/model/malloy_query.ts
In the case the filter is undefined, make sure we return the default value (also handled in the `null` case) instead of throwing an unexpected script error.
=> Fix a script exception if the filter is undefined

packages/malloy-render/package.json
As title, package.json didn't previously include types with its exports; now it does.
**Why is this an issue/why now?**
Older ts module resolution strategies (like 'node') don't reference package.json exports; instead, they use 'main' and 'types'. These are the module resolution strategies used by 'malloy-composer' and 'malloy-vscode-extension.' Newer resolution strategies (like 'bunder', used in malloy-explorer) use package.json exports, and as such don't get types from the package.json 'types' field. Thus, this is needed.
**Testing**
- 'npm link'ed malloy-render to malloy-vscode-extension & checked things still worked. If there's a more robust way to test this I'd love to hear it.
=>  Update package.json exports to support types.

packages/malloy-filter/src/filter_interface.ts, packages/malloy-filter/src/nearley_parse.ts, packages/malloy/src/model/malloy_query.ts
Followup to https://github.com/malloydata/malloy/pull/2226
Reverts two unnecessary `if` conditions because we updated the `isFilterExpression()` to handle undefined properly.
The core issue was this block of code:
```
const expr = results[0];
if (isFilterExpression(expr)) {
```
If results.length === 0, then `expr` will be undefined. TypeScript does *not* enforce strict undefined checking, especially when reading from an array. Essentially, the lesson here is that all functions should always assume that values provided could be undefined.
=> Simplify undefined checking in filter_interface.ts

package-lock.json, packages/malloy/package.json, packages/malloy/src/lang/syntax-errors/custom-error-messages.ts, packages/malloy/src/lang/syntax-errors/malloy-parser-error-listener.ts, packages/malloy/src/lang/test/syntax-errors.spec.ts
A common pattern is
```
keyword: name DEFINITIONTION
```
this looks for IDENTIFIER COLOR IDENTIFIER error messages and prints something more helpful.
=> Add better error messages when a keyword is spelled wrong

packages/malloy/src/dialect/trino/trino.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/problems.spec.ts, test/src/databases/presto-trino/presto-trino.spec.ts, test/src/util/db-jest-matchers.ts, test/src/util/db-matcher-support.ts
```
run: t -> {
nest: foo is {
group_by: one
aggregate: `#` is count(one)
nest: foo is {
group_by: one
aggregate: `#` is count(one)
}
}
```
on presto this generates
```
SELECT
ARRAY_AGG(CAST(ROW("one__1",
"#__1",
"foo__1") AS ROW("one" BIGINT, 
"#" BIGINT, 
"foo" ARRAY<ROW(one BIGINT,# BIGINT)>))  ORDER BY  "#__1" desc) FILTER (WHERE group_set=1) as "foo"
FROM __stage2
```
note the unquoted `# BIGINT`
fixed in presto, also added a test for all dialects
Also includes some updated matchers I have been working on because it made the test for this easier to write.
=> Quote record field names when typing a record

packages/malloy-query-builder/src/query-ast.ts
Typescript was typing some of these as `any`, so enforce typing. Not sure why this is an issue, perhaps we need to update Typescript.
Discovered by doing `grep ': any' packages/malloy-query-builder/dist/query-ast.d.ts`
=> Enforce return types

packages/malloy/src/dialect/trino/dialect_functions.ts, test/src/databases/presto-trino/presto-trino.spec.ts
Examination of current production models, found these used a few times.
=> add split_part and regexp_extract to tresto dialect functions

packages/malloy-filter/src/clause_utils.ts, packages/malloy-filter/src/grammars/fexpr_number.ne, packages/malloy-filter/src/grammars/ftemporal.ne, packages/malloy-filter/src/test/ftemporal.spec.ts, test/src/databases/all/db_filter_expressions.spec.ts
@narreola hit this, and after some discussion with language group, it was agreed these should not be case sensitive. I skipped this work when implementing filter expressions because it required me to learn something about the lexer generator (moo) that I didn't feel like i had time to learn.
Coming back to it later, it is pretty simple.
Fixes #2265 
keywords in boolean filters were already insensitive, I did add a test.
=> keywords in filter expressions should not be case sensitive

packages/malloy-query-builder/src/query-ast.spec.ts, packages/malloy-query-builder/src/query-ast.ts
Fixed a couple bugs with the code to handle default field order in the query builder. The intended behavior is that as long as operations are never re-ordered, they will always appear in this order: `group_by`, `aggregate`, `where`, `having`, `nest`, `order_by`, `limit`, with fields of each type of operation appearing in the order in which they were inserted.
The following rules allow us to implement this slightly more generally so that it has the desired behavior when operations are never re-ordered, and sensible behavior after they've been meddled with. When adding a new operation:
1. If an operation of that kind already exists, add the new operation after the last operation in the first consecutive run of that kind
```
group_by: existing
group_by: existing
group_by: new
aggregate: …
```
=> Fix bugs with default field order in query builder

packages/malloy-render/src/component/line-chart/generate-line_chart-vega-spec.ts, packages/malloy-render/src/stories/line_charts.stories.malloy
The current line chart tooltip contains unlimited items and is unsorted.
See: https://www.internalfb.com/intern/px/p/73M7B
Limits the visible items to 10 (plus the hovered item), and sorts them:
=> Limit size of line chart tooltip and sort the conents

package-lock.json, packages/malloy-db-duckdb/package.json
Apparently version 1.1.1. does not have prebuilt binaries in NPM -- thus resulting in log build times.
=> Update duckdb to 1.2.1.

packages/malloy-db-trino/src/trino_connection.ts, test/src/databases/presto-trino/presto-trino.spec.ts
Allows schemas with maps to be read without errors.
=> Parse map types to sql_native

packages/malloy/src/model/malloy_query.ts, test/src/databases/all/compound-atomic.spec.ts, test/src/util/db-matcher-support.ts
Something like
```
dimension: my_record is existing_record
...
-> { select: my_record.property }
```
results in a compiler error saying `'existing_record' not found`
This fixes that
=> fix access of property from generated record

packages/malloy/src/lang/ast/expressions/expr-aggregate-function.ts, packages/malloy/src/lang/test/expressions.spec.ts
A user was hitting a case where they saw a script error while authoring Malloy, instead of a helpful error message:
`"Cannot read property 'name' of undefined"`
Fixes that error by correcting the computation of the join path overlap to avoid reading arrays out of bounds.
=> Fix an error message shown for 0-length join path overlaps

.github/workflows/prerelease.yaml
We want to be able to push in progress work, so skip tests.
=> Don't require tests for dev releases

packages/malloy-render/src/component/bar-chart/generate-bar_chart-vega-spec.ts, packages/malloy-render/src/component/chart-layout-settings.ts, packages/malloy-render/src/component/chart/chart.css, packages/malloy-render/src/component/chart/chart.tsx, packages/malloy-render/src/component/line-chart/generate-line_chart-vega-spec.ts, packages/malloy-render/src/component/types.ts, packages/malloy-render/src/stories/bar_chart.stories.malloy, packages/malloy-render/src/stories/line_charts.stories.malloy
First pass at limiting data rendered into charts to prevent blow ups in the browser
For bar charts:
- sets a lower bound on bar width of 6px for grouped bars, 16px for non-grouped bars. Won't render any more bars than can within a single view.
- sets a max of 20 series that can be rendered at the same time
- handles limiting data both at shared level (when x axis shared across nested rows) and chart by chart level (when having independent x axes)
For line charts:
- sets max number of series to 12 by default. This is overridable via `# line_chart { series.limit=# }`
- sets a max limit of data points per chart to 5k
- when data is limited across line charts with shared y-axis, we disable the y-axis sharing for now because we don't currently capture the min / max values within that limited …
=> feat: limit bar and line data

packages/malloy-interfaces/src/to_malloy.ts, packages/malloy-query-builder/src/query-ast.spec.ts, packages/malloy-query-builder/src/query-ast.ts
Avoid any string -> Date -> string conversions, and allow for disambiguating filter expressions and strings.
=> Allow setting parameters with literal objects

packages/malloy/src/dialect/trino/dialect_functions.ts
the presto function approx_count(...) uses a accuracy of 0.0040625.  The HLL functions should give pretty close to the same values by default.
=> Make HLL user the same default value that count_approx uses

packages/malloy/src/model/malloy_query.ts
BigQuery can't use expressions as  'partition by:' fields in queries with a 'group by', but they work in regular select queries (or mostly anyway).
This skips the logic that works around the problem when the query is just a select query.
The one side effect is that you won't be able to `partition by` a float64 in a select query.  As this is a bigquery limitation, I don't think it is a big deal.
=> in BigQuery, on select: queries, don't use the lateral join bag

packages/malloy-render/src/component/bar-chart/generate-bar_chart-vega-spec.ts, packages/malloy-render/src/component/chart-layout-settings.ts, packages/malloy-render/src/component/line-chart/generate-line_chart-vega-spec.ts, packages/malloy-render/src/component/render-result-metadata.ts, packages/malloy-render/src/component/render.tsx, packages/malloy-render/src/component/result-context.ts, packages/malloy-render/src/component/util.ts, packages/malloy-render/src/stories/bar_chart.stories.malloy, packages/malloy-render/src/stories/line_charts.stories.malloy
Allows you to set `# size=fill` at the top level of a view, and if its a chart it will size the chart to fit the window
still some kinks to work out with fitting it properly when there are chart titles/subtitles/legends
also need to provide a way to set this programmatically on the <malloy-render> element like we do with some other controls
=> feat: chart fill size

packages/malloy/src/lang/ast/expressions/constant-expression.ts, packages/malloy/src/lang/ast/field-space/dynamic-space.ts, packages/malloy/src/lang/ast/field-space/include-utils.ts, packages/malloy/src/lang/ast/field-space/parameter-space.ts, packages/malloy/src/lang/ast/field-space/query-input-space.ts, packages/malloy/src/lang/ast/field-space/query-spaces.ts, packages/malloy/src/lang/ast/field-space/refined-space.ts, packages/malloy/src/lang/ast/field-space/static-space.ts, packages/malloy/src/lang/ast/query-elements/query-arrow.ts, packages/malloy/src/lang/ast/query-elements/query-refine.ts, packages/malloy/src/lang/ast/query-items/field-declaration.ts, packages/malloy/src/lang/ast/query-properties/qop-desc.ts, packages/malloy/src/lang/ast/source-elements/refined-source.ts, packages/malloy/src/lang/ast/types/field-space.ts, packages/malloy/src/lang/ast/view-elements/qop-desc-view.ts, packages/malloy/src/lang/ast/view-elements/view-arrow.ts, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-log.ts, packages/malloy/src/lang/test/annotation.spec.ts, packages/malloy/src/lang/test/field-symbols.spec.ts, packages/malloy/src/lang/test/parse-expects.ts, packages/malloy/src/lang/test/query.spec.ts, packages/malloy/src/lang/test/source.spec.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/model/composite_source_utils.ts
This allows `internal` fields to be accessed in a joining source.
E.g., this is allowed:
```
source: joined is ... {
internal dimension: x_internal is 1
}
source: joining is ... {
join_one: joined on joined.x_internal = 1
dimension: uses_internal is joined.x_internal
}
```
Using an internal joined field in a query is still not allowed.
```
run: joining -> {
group_by: joined.x_internal // Error: `x_internal is internal`
}
```
Also allow `include` to mention fields in joins:
```
source: x is y include {
internal: joined.*
except: joined.a, joined.b, joined.c
}
```
Also *changes the default behavior of include* to make fields `private` if they are not mentioned.
`include { a }` used to be the same as `include { a; except: * }`. Now it is the same as `include { a; private: * }`
=> Allow internal fields to be used in joins (in sources; not queries)

packages/malloy-render/src/component/bar-chart/get-bar_chart-settings.ts, packages/malloy-render/src/component/line-chart/get-line_chart-settings.ts, packages/malloy-render/src/stories/bar_chart.stories.malloy, packages/malloy-render/src/stories/line_charts.stories.malloy
If a chart is using implicit mappings, prefer to use a time field for the x axis, if there is one
=> feat: auto time axis

packages/malloy-tag/src/tags.ts, test/src/core/tags.spec.ts
@skokenes found that adding `-line_chart` to a run statement does not remove the line chart tag inherited from a view.
test and fix included.
=> don't find deleted tags (plus a test)

packages/malloy-render/src/component/render-result-metadata.ts, packages/malloy-render/src/data_tree.ts, packages/malloy-render/src/stories/line_charts.stories.malloy
Deleted tags were still being recognized. Possibly there's a better API for this but this a quick fix.
=> Fix render tag override

packages/malloy-interfaces/src/types.ts, packages/malloy-interfaces/thrift/malloy.thrift, packages/malloy/src/to_stable.ts
Required to support the filter UI since each type has a different UI.
=> Pass along filter type if available

packages/malloy/src/dialect/functions/malloy_standard_functions.ts, test/src/databases/all/functions.spec.ts
We support row_number() and rank() but not dense_rank(), adding it.
=> add a dense_rank to standard functions

packages/malloy-render/src/component/apply-renderer.tsx, packages/malloy-render/src/component/bar-chart/get-bar_chart-settings.ts, packages/malloy-render/src/component/chart/chart-dev-tool.tsx, packages/malloy-render/src/component/chart/chart.tsx, packages/malloy-render/src/component/error-message/error-message.css, packages/malloy-render/src/component/error-message/error-message.tsx, packages/malloy-render/src/component/line-chart/generate-line_chart-vega-spec.ts, packages/malloy-render/src/component/line-chart/get-line_chart-settings.ts, packages/malloy-render/src/component/register-webcomponent.ts, packages/malloy-render/src/component/render-result-metadata.ts, packages/malloy-render/src/component/render.tsx, packages/malloy-render/src/plugins/line-chart-series-plugin.ts, packages/malloy-render/src/stories/bar_chart.stories.malloy, packages/malloy-render/src/stories/line_charts.stories.malloy
Adds
- error messages when charts are misconfigured
- `renderAs` property on malloy render element for inspecting which renderer is used
Fixes
- broken line chart x hovering
=> [render] feat: chart misconfiguration error messages

packages/malloy-interfaces/src/nest_unions.spec.ts, packages/malloy-interfaces/src/nest_unions.ts
I am trying to convert a thrift interface, but the Thrift object has 'null' as the value for all the non-active items in a union, like this:
```
array_type: null,
boolean_type: null,
date_type: null,
json_type: null,
number_type: {subtype: 1},
record_type: null,
sql_native_type: null,
string_type: null,
timestamp_type: null,
```
I have not exhaustively thought through the implications of this, so wanted to run it by the team before digging too deep.
=> Treat null values as undefined in thrift unions

packages/malloy-filter/src/grammars/ftemporal.ne, packages/malloy-filter/src/temporal_filter_expression.ts, packages/malloy-filter/src/test/ftemporal.spec.ts
Explorer UI testing reveals a need for "on or after" in addition to after.
The filter expressions words are ( where _X_ is a time-literal like `today` or `2023-01-17` )
| Expression | Meaning |
| ---- | ---- |
| `before` _X_ | All time strictly before (less than) _X_ |
| `through` _X_ | All time up to the end of _X_ |
| _X_ | All time >= the beginning of _X_ and < the end |
| `starting` _X_ | All time >= the beginning of _X_ |
| `after` _X_ | All after the end of _X_ |
=> add 'through' and 'starting' to temporal filter expressions

packages/malloy-render/src/plugins/line-chart/generate-line_chart-vega-spec.ts
Updates line chart to read settings from the correct location
=> [render] fix: read line chart settings from correct location

packages/malloy-render/src/data_tree/fields/base.ts, packages/malloy-render/src/drill.spec.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, packages/malloy/src/to_stable.ts
Fixes an issue where drilling on a query that directly references a joined-in field fails because it produces the wrong drill filter (`drill: field = 'value'` rather than `drill: join_name.field = 'value'`)
=> Fix drill on join field reference

package-lock.json, packages/malloy-db-duckdb/package.json
DuckDB 1.2.1 has missing binary distributions on NPM.
Building on Linux doesn't work for some HW architectures.
Moving to 1.3.1 seems to resolve this.
=> Updates malloy/duckdb to 1.3.1

packages/malloy/src/lang/ast/field-space/reference-field.ts, packages/malloy/src/lang/parse-log.ts, packages/malloy/src/lang/test/composite-field-usage.spec.ts, packages/malloy/src/lang/test/query.spec.ts, packages/malloy/src/model/composite_source_utils.ts, packages/malloy/src/model/malloy_types.ts
Simplifies error message reporting for composite errors involving issues other than just conflicting fields, e.g. a required group by issue in one source and a missing field in another source.
=> Improve complex composite error messages

packages/malloy-render/src/data_tree/fields/nest.ts
Refactors RecordField constructor to use an options object instead of boolean parameters, making the code more readable and self-documenting.
Addresses review feedback on #2455.
=> refactor: Eliminate boolean trap in RecordField constructor

packages/malloy/src/lang/ast/query-properties/qop-desc.ts, packages/malloy/src/lang/syntax-errors/custom-error-messages.ts, packages/malloy/src/lang/syntax-errors/malloy-parser-error-listener.ts, packages/malloy/src/lang/test/locations.spec.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/syntax-errors.spec.ts, packages/malloy/src/lang/utils.ts
Identifies a few common error messages encountered when an AI system authors Malloy models and queries, and adds clearer error messages in those cases.
Example error messages:
* "Unexpected type 'int' in dimension definition. Expected an expression or field reference."
* "Unknown function 'percent_of_total'. You can find available functions here: https://docs.malloydata.dev/documentation/language/functions"
* "The 'project:' keyword is no longer supported. Use 'select:' instead."
* "Unsupported keyword 'as'. Use 'is' to name something (ex: `dimension: name is expression`)"
* "Use of select is not allowed in a grouping query"
=> Add a few additional error message improvements

packages/malloy/src/lang/ast/field-space/dynamic-space.ts, packages/malloy/src/lang/ast/source-elements/refined-source.ts, packages/malloy/src/lang/ast/types/malloy-element.ts, packages/malloy/src/model/malloy_query.ts
In general, we don't mutate objects much in the compiler/translator, so deep copy operations (which are slow) should not be necessary. If we hit issues with mutations causing issues, replace the _mutation_ with a shallow copy and update rather than a deep copy. 
For a large example cube request, this improved performance from an average of 99.57ms to 41.73ms (57.84ms savings on average, or 58% reduction in compile time).
As the Malloy IR is becoming bigger/more complex, deep copy results in a bigger performance impact. 
There are separate issues with larger IR, some of which can be solved with smarter choices in the translator; others may require making design tradeoffs to keep the IR small.
Some obvious candidates:
- Nest references in queries copy the view definition
- Joins copy the …
=> Remove a bunch of unnecessary deep copy operations

packages/malloy-render/src/component/table/table.tsx, packages/malloy-render/src/stories/scroll-override.stories.malloy, packages/malloy-render/src/stories/scroll-override.stories.ts
Fixes a bug where we weren't hardcoding the width when appropriate on table header cells. This was causing content overflow issues.
Also added a story for testing the scroll override feature of the renderer API
=> fix: header width setting; scroll override story

packages/malloy/src/api/core.ts
When compiling a query, we would take the `compiler_needs` and convert them into a `ParseUpdate` to pass to the translator, but we did that twice; once to pass to the translator responsible for compiling the model (or loading it from the cached JSON) and once for the translator responsible for compiling the query. Since parsing a JSON model is slow, doing this once and passing the resulting `ParseUpdate` saves a lot of time.
In my testing, this reduces compilation time of a query against a complex cube model from 40.78ms to 20.14ms (20.64ms or a 51% reduction in compilation time).
=> Don't double-process compiler needs

packages/malloy/src/lang/ast/query-items/field-declaration.ts, packages/malloy/src/lang/test/query.spec.ts
Currently, if you write a query like this, it leads to an error: `Circular reference to 'dep_time' in definition`
```
run: flights -> {
group_by: dep_time.day
order_by: dep_time
}
```
Fix the field lookup to properly resolve the `dep_time` that was already defined in the query, rather than trying to re-create it in the output space, which ends up referencing itself by mistake.
=> Fix a broken order_by/group_by interaction

packages/malloy/src/lang/ast/statements/define-source.ts, packages/malloy/src/lang/parse-log.ts, packages/malloy/src/lang/test/composite-field-usage.spec.ts, packages/malloy/src/model/composite_source_utils.ts, packages/malloy/src/model/malloy_types.ts, test/src/databases/all/composite_sources.spec.ts
One of the primary uses for composite sources is to handle partition selection of cubes stored as partition tables. This results in a pattern like:
```malloy
##! experimental.composite_sources
source: partition_a is connection.table('cube_table') include { a } extend {
where: partition = 'a'
}
source: partition_b is connection.table('cube_table') include { b } extend {
where: partition = 'b'
}
source: partition_c is connection.table('cube_table') include { c } extend {
where: partition = 'c'
}
source: cube is compose(partition_a, partition_b, partition_c)
```
For large cubes, this can result in significantly bloated models, since each partition gets its own source definition complete with its own field list; then based on the (not yet optimized) way composite sources are stored in model …
=> Experimental partition composites

packages/malloy/src/model/expression_compiler.ts, packages/malloy/src/model/field_instance.ts, packages/malloy/src/model/query_query.ts
Information for an expression compilation was being extract from two places (QueryField and QueryStruct) when it should have come from one. It's leftover cleanup from when expression compliation was a method of QueryField.
Getting set to do constant expression evaluation and this was the first thing that I noticed.
=> simplify input to exprToSQL

packages/malloy/src/lang/malloy-to-stable-query.ts, packages/malloy/src/lang/test/malloy-to-stable-query.spec.ts
This fixes the case where the parser would silently fail when there were filter parameters, like:
```
run: a(b is f`c`) -> {}
```
I'm not certain of the implementation, it seems like with other contexts there are built in methods for this sort of thing, but this does address the issue.
=> Fix parsing filter parameters

packages/malloy-render/package.json
This PR fixes a bug where `@malloydata/render` types couldn't be resolved.
=> Fix "@malloydata/render" types path

packages/malloy-render/src/component/bar-chart/generate-bar_chart-vega-spec.ts, packages/malloy-render/src/component/render-numeric-field.ts, packages/malloy-render/src/data_tree/fields/base.ts, packages/malloy-render/src/html/html_view.ts, packages/malloy-render/src/html/utils.ts, packages/malloy-render/src/plugins/bar-chart/generate-bar_chart-vega-spec.ts, packages/malloy-render/src/util.ts, packages/malloy/src/dialect/pg_impl.ts, packages/malloy/src/dialect/trino/trino.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/field_instance.ts, packages/malloy/src/model/malloy_types.ts, packages/malloy/src/model/query_query.ts, packages/malloy/src/to_stable.ts, test/src/core/bugless.spec.ts, test/src/databases/all/time.spec.ts
There were a number of problems with query time zones
1. They broke when moving to the new renderer
2. They never have never worked with nested queries with different time zones.
Fixes #2392
Here's the AI summary:
This PR addresses timezone handling issues by implementing comprehensive timezone propagation across the entire codebase, from core data structures to rendering layers.
Previously, timezone information was not properly propagated to the nested query contexts, causing timezone-related operations to fail or produce incorrect results in complex query scenarios involving nested views and explore fields.
Implemented end-to-end timezone propagation with the following key changes:
- **Enhanced Type System**: Added new discriminators and timezone-aware types in `malloy_types.ts`
- …
=> Fix query time zones

packages/malloy-db-trino/src/trino_connection.ts
Handle an issue where row[4] is `19` (meaning `<eof>`) rather than a type.
Only use that entry as a type when it is a string value as opposed to if it merely exists.
=> Avoid non-string values in row[4] of the presto/trino response
