malloydata/malloy

README.md
=> clarified install/build directions

packages/malloy-render/src/html/dashboard.ts, packages/malloy/src/index.ts, packages/malloy/src/malloy.ts
Chris, let's chat about this when you get back.
=> Fix breakage when rendering dashboards that are Records, not Arrays

packages/malloy-db-test/src/expr.spec.ts, packages/malloy-render/src/drill.ts, packages/malloy-render/src/html/bar_chart.ts, packages/malloy-render/src/html/cartesian_chart.ts, packages/malloy-render/src/html/chart.ts, packages/malloy-render/src/html/container.ts, packages/malloy-render/src/html/dashboard.ts, packages/malloy-render/src/html/list.ts, packages/malloy-render/src/html/list_detail.ts, packages/malloy-render/src/html/point_map.ts, packages/malloy-render/src/html/segment_map.ts, packages/malloy-render/src/html/shape_map.ts, packages/malloy-render/src/html/table.ts, packages/malloy-render/src/html/vega_spec.ts, packages/malloy-vscode/src/extension/tree_views/schema_view.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, samples/faa/flights.malloy
The ability to group_by an entire explore in a query.  The result ends up with a foreign key and a deep copy of the explore def...
=> group_by explores

samples/the_met/the_met.malloy, samples/the_met/the_met.styles.json
This dataset is the-met's 200,000 item collection with images.  Should make a really nice data set to show off drilling and search (and actually be really useful).
=> the_met data set

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy-db-test/src/multi_connection.spec.ts, packages/malloy-db-test/src/runtimes.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts
=> Make a runtime that can handle multiple dialects.

packages/malloy-vscode/src/extension/commands/run_query_utils.ts, packages/malloy-vscode/src/extension/state.ts, packages/malloy-vscode/src/extension/tree_views/schema_view.ts, packages/malloy-vscode/webpack.config.js
for now, just postgres and bigquery
=> Support multiple connections in the VSCode App

packages/malloy-db-postgres/src/postgres_connection.ts, samples/faa/flights.malloy, samples/faa/flights_base_bigquery.malloy, samples/faa/flights_base_postgres.malloy
Lots of small little bugs to work out to get the examples to work on postgres...
=> Start getting flights to work on postgres

packages/malloy-render/src/drill.ts, packages/malloy-render/src/html/bar_chart.ts, packages/malloy-render/src/html/dashboard.ts, packages/malloy-render/src/html/line_chart.ts, packages/malloy-render/src/html/point_map.ts, packages/malloy-render/src/html/scatter_chart.ts, packages/malloy-render/src/html/segment_map.ts, packages/malloy-render/src/html/shape_map.ts, packages/malloy-render/src/html/vega_spec.ts, packages/malloy/src/malloy.ts
=> We needed to pay attention to how the field was generated,

samples/faa/airports.malloy, samples/faa/airports.styles.json
=> Airports should use elevation instead of owner type

packages/malloy-db-test/src/expr.spec.ts, packages/malloy-db-test/src/handexpr.spec.ts, packages/malloy-db-test/src/join.spec.ts, packages/malloy-db-test/src/orderby.spec.ts, packages/malloy-db-test/src/performance.spec.ts, packages/malloy-db-test/src/runtimes.ts
Return a close function with list of runtimes
Modify tests to use it.
=> Make multi dialect tests close properly

packages/malloy-db-test/src/join.spec.ts, packages/malloy-db-test/src/orderby.spec.ts
=> turn on the postgres tests

packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/beta.spec.ts, packages/malloy/src/lang/grammar/Malloy.g4
Walking through the grammar, trying to have at least one test for every legal phrase.
=> Fill out basic parsing tests

docs/_src/language/basic.md
I am not a good "reviewer for mistakes" person because my brain shuts off after about 15 minutes. "Hey michael, whatever this boring thing you are doing is, let me know when you are done and I will power back up".
So here are 15 minutes of changes I think the quick start page needs. Some are typos and some are edits for clarity.
Made the a PR because I don't know what the right thing to do is when I have doc changes.
=> Quick set of edits to the quick start page

packages/malloy/src/lang/beta.spec.ts, packages/malloy/src/lang/field-space.ts
=> do not allow rename to old name

docs/_src/language/join.md, packages/malloy-db-test/src/handexpr.spec.ts, packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/grammar/Malloy.g4, packages/malloy/src/lang/parse-to-ast.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts
* Fix the model/ join interface, associated changes in lang/
* More doc editing
=> fixups to join types and computations

packages/malloy-db-test/src/nomodel.spec.ts, packages/malloy/src/model/malloy_query.ts
Make sure symmetric aggregates work in all possible cross join combinations
=> Make cross joins works.  Tests.

docs/_layouts/documentation.html, docs/_scripts/build_docs/index.ts, docs/_scripts/build_docs/page.ts, docs/css/document.css, docs/img/article_icon.svg, docs/img/section_close.svg, docs/img/section_open.svg, docs/js/sidebar_state.js
- Also remembers state of each section
- Sections default to collapsed
- Remember scroll position
=> Allow collapsing navbar sections in docs

packages/malloy-vscode/src/extension/webviews/connections_page/App.tsx, packages/malloy-vscode/src/extension/webviews/webview_html.ts
* Adds a spinner to the React HTML template, so that while react is "booting" you see a spinner that says "Loading"
* Adds a spinner to the connections page while waiting for connections to be sent over
=> Add some more spinners

docs/_layouts/documentation.html, docs/_scripts/build_docs/malloy_prism.ts, docs/_scripts/build_docs/run_code.ts, docs/_src/visualizations/segment_maps.md, docs/css/document.css, docs/js/sidebar_state.js, docs/js/view_toggles.js
https://user-images.githubusercontent.com/3538955/150885326-8aa66f48-1720-40ed-9044-8793539446f7.mov
=> Show toggle in docs between HTML, JSON, and SQL

packages/malloy/src/lang/ast/ast-main.ts
=> Fix typo in error message

packages/malloy-vscode/src/extension/webviews/connections_page/ConnectionEditor/PostgresConnectionEditor/PostgresConnectionEditor.tsx
Fixes https://github.com/looker-open-source/malloy/issues/257
=> Hide postgres password (and add show password checkbox)

packages/malloy/src/lang/beta.spec.ts, packages/malloy/src/lang/parse-malloy.ts
=> Accept zero length documents

docs/_src/examples/wordle/wordle.md, docs/_src/examples/wordle/wordle1a.md, docs/_src/examples/wordle/wordle2.md, docs/_src/examples/wordle/wordle214.md, docs/_src/examples/wordle/wordle215.md, docs/_src/examples/wordle/wordle216.md, docs/_src/examples/wordle/wordle217.md, docs/_src/examples/wordle/wordle3.md, docs/_src/examples/wordle/wordle4.md
=> point old wordle solutions to old words table

packages/malloy-vscode/package.json, packages/malloy-vscode/scripts/build-extension.ts, packages/malloy-vscode/src/extension/extension.ts, packages/malloy-vscode/src/extension/webview_message_manager.ts, packages/malloy-vscode/src/extension/webview_views/help_view.ts, packages/malloy-vscode/src/extension/webviews/help_page/App.tsx, packages/malloy-vscode/src/extension/webviews/help_page/entry.ts, packages/malloy-vscode/src/extension/webviews/help_page/help_vscode_context.ts
https://user-images.githubusercontent.com/3538955/151888126-a6482281-a2af-41c4-a274-754a54070244.mov
=> Add Help panel to VSCode extension

packages/malloy-render/src/data_styles.ts, packages/malloy-render/src/html/cartesian_chart.ts, packages/malloy-render/src/html/chart.ts, packages/malloy-render/src/html/html_view.ts, packages/malloy-render/src/html/shape_map.ts
Ignore null data in shape maps
=> Show larger maps when graphing everything

packages/malloy-vscode/media/connections.md, packages/malloy-vscode/media/docs.md, packages/malloy-vscode/media/sample-models.md, packages/malloy-vscode/package.json
Adds a walkthrough to the "Get Started" menu in VSCode:
=> VSCode Walkthrough

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-vscode/src/common/connection_manager.ts
=> Fix location not being set properly in BQ connections

packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/test/parse.spec.ts
@christopherswenson  fixed this in #360 but reviewing his fix made me hate the code he fixed, so I am fixing the part I hated.
Also added the empty model to the test suite.
=> Better handling of empty models

docs/_src/examples/malloy_by_example.md
=> Malloy by Example doc. 

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/malloy.ts, packages/malloy/src/runtime_types.ts
Have you ever seen an error for a bad table name appearing on line one of your file? Then this PR is for **YOU**!
=> Catch errors in requesting files, table schemas, and sql schemas, and pass them correctly into the translator

packages/malloy/src/lang/parse-tree-walkers/document-symbol-walker.ts, packages/malloy/src/lang/test/document-symbol-walker.spec.ts
Fixes https://github.com/looker-open-source/malloy/issues/163
=> Fix document symbol walker and tests

packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/test-translator.ts
Fixes #373
Any turtle which appended queries to an existing turtle would fail.
=> Allow new turtles to be created which append to old ones

packages/malloy/src/lang/ast/ast-expr.ts, packages/malloy/src/lang/test/parse.spec.ts
=> translate pick on values to partial comparisons

packages/malloy/src/lang/ast/apply-expr.ts, packages/malloy/src/lang/test/parse.spec.ts
=> error better when regex compare to undefined

samples/imdb/.gitignore, samples/imdb/movie_complex.malloy, samples/imdb/movie_queries.malloy, samples/imdb/movie_with_tags.malloy, samples/imdb/movielens.malloy, samples/imdb/upload_imdb.sh, samples/imdb/upload_movielens.sh
Shows how to merge two different analysises.
=> Add the Kaggle Movielens data to this data set for movie tags.

packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/test/parse.spec.ts
=> Where clause in query should access refined source

docs/_src/examples/iowa/iowa.md, packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy-db-test/src/index.spec.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, packages/malloy/src/runtime_types.ts
Add search indexes back into the interface.
=> Make search indexes work again.

docs/_src/language/time-ranges.md, packages/malloy-db-test/src/datetimes.spec.ts, packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/postgres.ts, packages/malloy/src/dialect/standardsql.ts, packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/ast/ast-time-expr.ts, packages/malloy/src/lang/parse-to-ast.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts
Fixes #315
As of this writing there is some code, and a few test, and already there are problems with the tests that I don't quite know how to solve. I'm pushing in this state, this will not pass CI, that is expected at this point.
=> Implement time difference

docs/_src/language/expressions.md
Add interval extractions to time expressions doc
=> update expressions doc

packages/malloy-db-test/src/datetimes.spec.ts
There are a handful that are `test.skip` but I'd like to get the working ones into CI now.
=> Add missing tests for time operation suite

packages/malloy/src/model/malloy_query.ts
=> Improve the search index query to show first matches

packages/malloy/src/model/malloy_query.ts
=> remove orderby in search index

developing.md
=> vsix ends up in dist directory

packages/malloy-render/src/html/date.ts
=> Render null dates, closes #448

packages/malloy-db-test/src/nomodel.spec.ts, packages/malloy/src/model/malloy_query.ts
Fixes #454
@greg-finley @mtoy-googly-moogly FYI
=> Parenthesize when doing a field substitution

packages/malloy-vscode/src/extension/webviews/query_page/ResultKindToggle.tsx
This addresses https://github.com/looker-open-source/malloy/pull/451 in the simplest way. We could still also consider merging #492.
=> Avoid selecting UI elements

packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/test/parse.spec.ts
=> Prevent query composition from changing definition of source query

packages/malloy-vscode/scripts/build-extension.ts, packages/malloy-vscode/src/extension/webviews/query_page/App.tsx, packages/malloy/src/malloy.ts
Fixes https://github.com/looker-open-source/malloy/issues/29
1
=> Add row limit warning

package.json, packages/malloy-vscode/package.json, packages/malloy-vscode/scripts/build-extension.ts, tsconfig.packages.json, yarn.lock
Fixes webview debugging with sourcemaps by inlining sourcemaps. Also patch up some Typescript issues along the wahy.
=> Fix some Typescript/sourcemap issues

packages/malloy-db-test/src/nomodel.spec.ts, packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/duckdb.ts, packages/malloy/src/dialect/postgres.ts, packages/malloy/src/dialect/standardsql.ts, packages/malloy/src/lang/ast/apply-expr.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts
Create a new dialect fragment type for REGEXP_CONTAINS
=> Cross Dialect REGEXP_CONTAINS

demo/malloy-demo-composer/src/app/ActionIcon/ActionIcon.tsx, demo/malloy-demo-composer/src/app/Explore/Explore.tsx, demo/malloy-demo-composer/src/app/MalloyLogo/MalloyLogo.tsx, demo/malloy-demo-composer/src/app/data/use_directory.ts, demo/malloy-demo-composer/src/app/data/use_open_directory.ts, demo/malloy-demo-composer/src/app/data/use_save_field.ts, demo/malloy-demo-composer/src/electron/app.d.ts, demo/malloy-demo-composer/src/electron/directory.ts, demo/malloy-demo-composer/src/electron/file_system.ts, demo/malloy-demo-composer/src/electron/main.ts, demo/malloy-demo-composer/src/electron/preload.ts
=> Open directory

packages/malloy-db-postgres/src/postgres_connection.ts, packages/malloy-db-test/src/index.spec.ts, packages/malloy/src/dialect/postgres.ts, packages/malloy/src/model/malloy_query.ts
All dialects now support Index and have guards to keep it from trashing the database.
=> Indexing capabilities for Postgres

packages/malloy-db-duckdb/package.json, yarn.lock
Reverts looker-open-source/malloy#578. I'm seeing SEGVs so maybe this is a bit too bleeding edge.
=> Revert "Track duckdb next"

packages/malloy-render/src/html/dashboard.ts, packages/malloy-render/src/html/point_map.ts, packages/malloy-render/src/html/segment_map.ts, packages/malloy-render/src/html/shape_map.ts, packages/malloy-render/src/html/table.ts, packages/malloy-render/src/html/utils.ts, packages/malloy-render/src/html/vega_spec.ts, packages/malloy-vscode/src/extension/html/html.ts, packages/malloy-vscode/src/extension/webviews/components/Spinner/Spinner.tsx, packages/malloy-vscode/src/extension/webviews/webview_html.ts
=> Dashboard theming

packages/malloy-db-test/src/datetimes.spec.ts, packages/malloy/src/model/malloy_query.ts
Fixes #532
Waiting for @lloydtabb to get back from vacation for review.
=> Do not double truncate

packages/malloy-db-duckdb/package.json, packages/malloy-db-duckdb/src/duckdb.d.ts, packages/malloy-db-duckdb/src/duckdb_connection.ts, packages/malloy-vscode/scripts/build-extension.ts, yarn.lock
Gives us search paths, readonly mode and we should be able to remove the JSON wrapper now.
=> Update to duckdb 0.4.0

packages/malloy-vscode/src/extension/webviews/query_page/App.tsx
Gives them a little flavor plus helps with multi-line error readability.
=> Style error messages somewhat

packages/malloy-db-duckdb/src/duckdb_connection.ts
Fixes issues surfaced by https://github.com/looker-open-source/malloy/issues/635
=> Handle DECIMALs and nested STRUCTS better

demo/malloy-demo-composer/src/app/ErrorMessage/ErrorMessage.tsx, demo/malloy-demo-composer/src/app/ErrorMessage/index.ts, demo/malloy-demo-composer/src/app/Explore/Explore.tsx, demo/malloy-demo-composer/src/app/data/use_models.ts, demo/malloy-demo-composer/src/app/data/use_open_directory.ts, demo/malloy-demo-composer/src/app/data/use_run_query.ts, demo/malloy-demo-composer/src/app/data/use_save_field.ts, demo/malloy-demo-composer/src/app/data/use_schema.ts, demo/malloy-demo-composer/src/app/data/use_search.ts, demo/malloy-demo-composer/src/app/data/use_top_values.ts, demo/malloy-demo-composer/src/electron/app.d.ts, demo/malloy-demo-composer/src/electron/main.ts
Allows backend errors to be seen by the frontend, adds a simple error display for now.
=> Marshal error across api

packages/malloy-db-test/src/nomodel.spec.ts, packages/malloy/src/model/malloy_query.ts
=> ALL(xxx) generates extra rows in the results.  Remove them in the next stage

packages/malloy/src/malloy.ts
This associates connection exceptions with their tables and schemas at the point where we are processing them so that they get placed at the correct file position instead of floating at the top of the document.
=> Handle connection exceptions

packages/malloy-db-duckdb/src/duckdb_connection.ts
`runDuckDBQuery()` and `runRawSQL()` are somewhat confusingly named, `runRawSQL()` is needed if you want to ensure that `init()` is called. This will make sure extensions are loaded before the first query, so `httpfs` will work once we figure out how to package that.
=> Make sure init is called for queries

packages/malloy/src/lang/ast/ast-expr.ts, packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/field-space.ts
Handle bad connections closer to the source so error highlighting works, also fix some typos I found along the way.
=> Various error handling cleanups

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy-vscode/src/common/connection_manager.ts, packages/malloy-vscode/src/common/connection_manager_types.ts, packages/malloy-vscode/src/extension/webviews/connections_page/ConnectionEditor/BigQueryConnectionEditor/BigQueryConnectionEditor.tsx
Fixes https://github.com/looker-open-source/malloy/issues/697.
=> Add maximum bytes billed config option

packages/malloy-render/src/html/bar_chart.ts, packages/malloy-render/src/html/cartesian_chart.ts, packages/malloy-render/src/html/chart.ts, packages/malloy-render/src/html/point_map.ts, packages/malloy-render/src/html/segment_map.ts, packages/malloy-render/src/html/shape_map.ts, packages/malloy-render/src/html/table.ts
=> Make bar charts less cluttered and increase size of charts in tables

packages/malloy-db-duckdb/src/duckdb.d.ts, packages/malloy-db-duckdb/src/duckdb_connection.ts
Flesh out our duckdb types. I hope to migrate this into the duckdb repo once I find all the typos.
=> Flesh out DuckDB types

demo/malloy-demo-composer/src/electron/main.ts, packages/malloy-render/src/html/html_view.ts
Make the imdb links clickable automagically, and fix clicking on them from within Composer.
=> Make _url magic, fix composer links

packages/malloy-db-duckdb/src/duckdb.d.ts, packages/malloy-db-duckdb/src/duckdb_connection.ts
Support unlimited downloads for duckdb by implemented a pseudo streaming interface.
=> Implement streaming interface for duckdb

packages/malloy/src/lang/field-space.ts, packages/malloy/src/lang/test/parse.spec.ts
=> Disallow redefinition in source

packages/malloy-vscode/src/common/connection_manager.ts, packages/malloy-vscode/src/worker/download_query.ts, packages/malloy-vscode/src/worker/refresh_config.ts
This is a quick fix, I should refactor the defaults so there is Only One.
=> Fix default row limit

packages/malloy-vscode/src/extension/webviews/query_page/App.tsx
Fixes https://github.com/looker-open-source/malloy/issues/695. Monitor for dark mode, and use a lighter color scheme (mostly based on the default dark color scheme for VS Code) when in dark mode.
=> Embrace the dark side

packages/malloy-vscode/src/extension/commands/query_download.ts, packages/malloy-vscode/src/extension/commands/run_query_utils.ts, packages/malloy-vscode/src/worker/worker_connection.ts
@anikaks If you have any suggestions for better verbiage let me know.
=> Better death handling

packages/malloy-vscode/src/extension/webviews/query_page/App.tsx
Fixes https://github.com/looker-open-source/malloy/issues/748
=> Disable drilling

demo/malloy-demo-bq-cli/package.json, demo/malloy-demo-composer/package.json, lerna.json, package-lock.json, package.json, packages/malloy-db-bigquery/README.md, packages/malloy-db-bigquery/package.json, packages/malloy-db-duckdb/README.md, packages/malloy-db-duckdb/package.json, packages/malloy-db-postgres/README.md, packages/malloy-db-postgres/package.json, packages/malloy-render/README.md, packages/malloy-render/package.json, packages/malloy/README.md, packages/malloy/package.json, test/package.json, vscode-extension/package.json
Prep for publishing NPM packages.
=> Npm packages

packages/malloy-db-bigquery/.npmignore, packages/malloy-db-duckdb/.npmignore, packages/malloy-db-postgres/.npmignore, packages/malloy-render/.npmignore, packages/malloy/.npmignore, packages/malloy/README.md
final few changes before manually pushing to npm
=> final npm prep

packages/malloy/src/malloy.ts
Fixes https://github.com/looker-open-source/malloy/issues/794
=> Handle numeric timestamps

docs/_config.yml, docs/_includes/banner.html, docs/_layouts/documentation.html, docs/css/document.css, docs/js/banner.js
=> Add GA and banner

demo/malloy-duckdb-wasm/README.md
A quick summary of how to use the demo.
=> First pass at docs

packages/malloy/src/dialect/duckdb.ts, packages/malloy/src/dialect/postgres.ts, packages/malloy/src/dialect/standardsql.ts
Fixes part 1 of https://github.com/looker-open-source/malloy/issues/819
=> type concat() as string

developing.md
fixes https://github.com/looker-open-source/malloy/issues/830
=> fix path to postgres test data

packages/malloy/src/lang/grammar/build_parser.js
Merged a change ( b6e81baa7d735f8f2d4b645fc4c9566b295d9a59 ) to main without a PR, and thus without tests. Making this PR so I can see all the tests pass.
=> Minor comment edit

packages/malloy/src/dialect/duckdb.ts
Use an UNNEST for symmetric agg instead of SUM(DISTINCT)
=> use unnest for symmetric agg

package-lock.json, package.json
We require node >= 16 and npm => 8 so make that explicit.
=> Specify node and npm versions

packages/malloy/src/model/malloy_query.ts
=> Fix typo in malloy_query.ts

demo/malloy-demo-composer/src/app/Result/Result.tsx
Fixes https://github.com/looker-open-source/malloy/issues/870
=> Allow scroll in SQL and Malloy tabs in composer

demo/malloy-demo-bq-cli/package.json, demo/malloy-demo-composer/package.json, demo/malloy-duckdb-wasm/package.json, package-lock.json, package.json, packages/malloy-db-bigquery/package.json, packages/malloy-db-duckdb/package.json, packages/malloy-db-postgres/package.json, packages/malloy-render/package.json, packages/malloy/package.json, test/package.json, vscode-extension/package.json
Make all versions 0.0.3 so that we can tag everything v0.0.3 when we publish. Add docs and homepage URLs.
=> Prepare for 0.0.3 release

packages/malloy/src/lang/ast/ast-expr.ts, packages/malloy/src/lang/test/parse.spec.ts
=> Correctly preserve parens when applying

docs/_src/examples/iowa/iowa.md
I think we need an unknown type in Malloy but remove from the docs for now.
=> We need to figure out how to deal with unknown types.

packages/malloy-db-bigquery/package.json, packages/malloy-db-duckdb/package.json, packages/malloy-db-postgres/package.json, packages/malloy-render/package.json, packages/malloy/package.json
Try to fix partial build issue by adding explicit pre-publish build to each module.
=> Add prepublish step

lerna.json, package-lock.json, package.json, packages/malloy-db-bigquery/package.json, packages/malloy-db-duckdb/package.json, packages/malloy-db-postgres/package.json, packages/malloy-render/package.json, packages/malloy/package.json, test/package.json
Update pre-release version to 0.0.7
=> version 0.0.7

packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/duckdb.ts, packages/malloy/src/dialect/postgres.ts, packages/malloy/src/dialect/standardsql.ts, packages/malloy/src/lang/ast/ast-expr.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, test/src/databases/all/expr.spec.ts, test/src/databases/all/nomodel.spec.ts, test/src/util/index.ts
=> Fix string literal quoting in all dialects

docs/_scripts/build_docs/index.ts, docs/_scripts/build_docs/run_code.ts
Use same root for zipping as finding samples.
=> Fix sample zips

package-lock.json, package.json, packages/malloy-db-duckdb/package.json, packages/malloy-db-duckdb/src/duckdb_common.ts, packages/malloy-db-duckdb/src/duckdb_connection.ts, packages/malloy/src/dialect/duckdb.ts, test/src/databases/duckdb/duckdb.spec.ts, test/src/runtimes.ts
@lloydtabb @christopherswenson @mtoy-googly-moogly  This is currently failing several tests in expr.spec.ts around interval extraction, like "interval extraction - duckdb › minutes"
=> DuckDB 0.6.1

packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/parse-to-ast.ts
Using the IntelliJ plugin I played around with some small optimizations that don't break the grammar too much.
I *think* this is about 20% faster, but the numbers fluctuate so much it is hard to be sure.
Anyway, without a major change to the grammar this is definitely at least a little better.
=> attempt to parse partials better

packages/malloy/src/dialect/duckdb.ts, packages/malloy/src/model/malloy_query.ts
=> Turn of union indexes until DuckDB supports real lateral joins.

packages/malloy-render/src/drill.ts, packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/duckdb.ts, packages/malloy/src/dialect/postgres.ts, packages/malloy/src/dialect/standardsql.ts, packages/malloy/src/lang/ast/apply-expr.ts, packages/malloy/src/lang/ast/ast-expr.ts, packages/malloy/src/lang/ast/ast-main.ts, packages/malloy/src/lang/ast/ast-time-expr.ts, packages/malloy/src/lang/ast/ast-types.ts, packages/malloy/src/lang/field-space.ts, packages/malloy/src/lang/space-field.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, test/src/databases/bigquery/handexpr.spec.ts, test/src/databases/bigquery/malloy_query.spec.ts, test/src/models/faa_model.ts, test/src/models/medicare_model.ts, test/src/util/index.ts
In expressions, type can now be
"scalar"
"aggregate"
"analytic"
=> Lay the ground work for Analytic functions in the Parser and Code generator.

packages/malloy/src/malloy.ts
More Typescript compatibility shenanigans.
=> Use protected member over super method

packages/malloy/src/run_sql_options.ts
File was recently added during reference cleanup and was likely missed in license migration
=> Fix license on file that was missed.

package-lock.json, packages/malloy-db-duckdb/package.json
https://duckdb.org/2023/02/13/announcing-duckdb-070.html
=> Update DuckDB to 0.7.0

cloudbuild/deploy/malloy-npm-publish.sh, cloudbuild/deploy/malloy-npm-release-publish.sh
Reverts malloydata/malloy#1029
Needs more work to set up postgres, backing out for the moment.
=> Revert "Test before publishing"

scripts/cloud/update_malloy.sh
Add setup script to install Malloy IDE extension, samples, and composer for cloud shell and IDE.
=> Add Cloud IDE setup script.

.eslintrc.cjs, packages/malloy-render/package.json, packages/malloy-render/src/data_styles.ts, packages/malloy-render/src/html/cartesian_chart.ts, packages/malloy-render/src/html/chart.ts, packages/malloy-render/src/html/container.ts, packages/malloy-render/src/html/dashboard.ts, packages/malloy-render/src/html/html_view.ts, packages/malloy-render/src/html/point_map.ts, packages/malloy-render/src/html/segment_map.ts, packages/malloy-render/src/html/shape_map.ts, packages/malloy-render/src/html/table.ts, packages/malloy-render/src/html/utils.ts, packages/malloy-render/src/html/vega_spec.ts, packages/malloy-render/src/renderer.ts
Fix for https://github.com/malloydata/malloy/issues/1020, plus the capability of auto TitleCasing that's currently off by default, pending some logic on the other side for when to apply that.
=> Trim renderer hints, allow auto TitleCase

cloudbuild/deploy/cloudbuild.yaml, cloudbuild/deploy/malloy-npm-publish.sh, cloudbuild/deploy/malloy-npm-release-publish.sh
Take two, now with more postgresness.
=> Test before publish

packages/malloy/src/malloy.ts
Support for multi-cell notebooks.
=> Add ability to extend a model with another model

packages/malloy-db-duckdb/src/duckdb_wasm_connection.ts
When there were parallel requests for a remote db, only the first one was waiting, so subsequent requests could get table not found errors.
=> Fix parallel table data fetches

packages/malloy/src/lang/ast/elements/define-query.ts, packages/malloy/src/lang/ast/elements/import-statement.ts, packages/malloy/src/lang/ast/query-elements/existing-query.ts, packages/malloy/src/lang/ast/query-elements/full-query.ts, packages/malloy/src/lang/ast/sources/query-source.ts, packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/test/imports.spec.ts, packages/malloy/src/lang/test/parse-expects.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/test-translator.ts
User reports have revealed some problems with imports, which also means there are problems with the tests for imports. Some things which don't work, should work, and we should have had tests for those things.
=> Fix more import related problems

packages/malloy-db-duckdb/src/duckdb_common.ts, test/src/databases/duckdb/duckdb.spec.ts
@lloydtabb was there any reason we didn't do this from the start?
Fixes #1073
=> Accept all duckdb numerics as numbers

packages/malloy-db-duckdb/src/duckdb_wasm_connection.ts
Make an effort to pick out tables from SQL that may not have shown up as a source prior.
=> Find SQL tables

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_types.ts
=> Exposing bytes processed when running a bigquery query through malloy api.

test/src/databases/bigquery-duckdb/nested_source_table.spec.ts
> I bet it has to do with my sampling test on indexing. Intermittently getting different results. I'd comment out the test and I'll take a look at it when I get back. -- @lloydtabb 
This will work around https://github.com/malloydata/malloy/issues/1113 ... for now.
=> Disable intermittent test

packages/malloy/src/lang/ast/expressions/expr-filter.ts, packages/malloy/src/lang/test/parse.spec.ts
=> Error on filtered scalar expression

packages/malloy/src/lang/ast/expressions/expr-coalesce.ts, packages/malloy/src/lang/ast/index.ts, packages/malloy/src/lang/grammar/MalloyLexer.g4, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/test/parse.spec.ts, test/src/databases/all/expr.spec.ts
* `expr ?? altValue`
generates
* `COALESCE(expr,altValue)`
=> Add ?? (nullish) operator

packages/malloy/src/model/malloy_query.ts, test/src/databases/all/expr.spec.ts
=> always parenthesize field expression replacement

packages/malloy/src/model/malloy_query.ts, test/src/databases/bigquery/wildcard_table_names.spec.ts
=> Pass through table suffix when generating UUID for wildcard tables

packages/malloy/src/dialect/duckdb/duckdb.ts, packages/malloy/src/dialect/postgres/postgres.ts, packages/malloy/src/dialect/standardsql/standardsql.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/nomodel.spec.ts
Reverts malloydata/malloy#1153
=> Revert "make spaces work in aliases and bigquery and other bugs"

packages/malloy/src/dialect/standardsql/standardsql.ts, test/src/databases/all/functions.spec.ts
Fixes https://github.com/malloydata/malloy/issues/1155
=> Use normal (non-raw) strings for BQ regexps

packages/malloy/src/dialect/duckdb/duckdb.ts, packages/malloy/src/dialect/postgres/postgres.ts, packages/malloy/src/dialect/standardsql/standardsql.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/functions.spec.ts, test/src/databases/all/nomodel.spec.ts
And fix some bugs around spaces in various identifiers.
=> Make BigQuery work with spaces among other things.

packages/malloy/src/index.ts
Export AtomicFieldDef -  needed in Composer.
=> export FieldAtomicDef.

packages/malloy/src/dialect/dialect_map.ts, packages/malloy/src/dialect/duckdb/functions/greatest_and_least.ts, packages/malloy/src/dialect/functions/avg_moving.ts, packages/malloy/src/dialect/functions/coalesce.ts, packages/malloy/src/dialect/functions/first_value_window.ts, packages/malloy/src/dialect/functions/greatest_and_least.ts, packages/malloy/src/dialect/functions/ifnull.ts, packages/malloy/src/dialect/functions/lag.ts, packages/malloy/src/dialect/functions/lead.ts, packages/malloy/src/dialect/functions/nullif.ts, packages/malloy/src/dialect/functions/sum_min_max_window.ts, packages/malloy/src/dialect/functions/util.ts, packages/malloy/src/dialect/postgres/functions/greatest_and_least.ts, packages/malloy/src/dialect/postgres/functions/ifnull.ts, packages/malloy/src/lang/ast/types/global-name-space.ts
Fix build breakage in closure compiler.
=> fix imports - import explicitly from files.

packages/malloy/src/lang/test/imports.spec.ts, packages/malloy/src/lang/test/parse-expects.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/sql-block.spec.ts, packages/malloy/src/lang/test/test-translator.ts
After some discussion @christopherswenson and I have a smaller, cleaner set of test matchers in lang that we agree on.
Been waiting for this moment to standardize, and fix all the old tests.
Now done.
=> cleanup custom lang test matchers

jest.config.js, packages/malloy-render/src/html/utils.ts, test/src/render/__snapshots__/render.spec.ts.snap, test/src/render/render.spec.ts
=> Fix issue where we were normalizing truncated dates with client

packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/reference-list.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/utils.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_types.ts
Added a `getImport` API on the Model which returns the import, if one exists, at the given position in the document.
=> Add getImport API

packages/malloy-render/src/html/table.ts, packages/malloy-render/src/html/utils.ts, test/src/render/render.spec.ts
=> Add ability to specify which fields should be used as dimensions for

packages/malloy-malloy-sql/src/grammar/malloySQL.pegjs, packages/malloy-malloy-sql/src/grammar/test/parse.spec.ts, packages/malloy-malloy-sql/src/malloySQLParser.ts, packages/malloy-malloy-sql/src/types.ts
=> Allow markdown sections in MalloySQL

packages/malloy-malloy-sql/src/malloySQLParser.ts, packages/malloy-malloy-sql/src/malloySQLSQLParser.ts, packages/malloy-malloy-sql/src/types.ts
Should probably move to a real grammar but doing the easy thing for now.
=> Move connection comment logic to package

packages/malloy-malloy-sql/src/grammar/malloySQLSQL.pegjs, packages/malloy-malloy-sql/src/grammar/test/parse.spec.ts, packages/malloy-malloy-sql/src/malloySQLParser.ts, packages/malloy-malloy-sql/src/malloySQLSQLParser.ts, packages/malloy-malloy-sql/src/types.ts
Delegate comment parsing to SQLSQL parser, source config and add tests.
=> MalloySQL connection parsing delegation and tests

packages/malloy-malloy-sql/src/malloySQLParser.ts
Allow for complete re-serialization.
=> Preserve initial comments

packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/test/parse.spec.ts
=> Allow parenthesized partials

packages/malloy/src/model/malloy_query.ts, test/src/databases/all/nomodel.spec.ts
Fixes https://github.com/malloydata/malloy/issues/1284
=> Fix issue where output fields are not parenthesized when used

packages/malloy/src/lang/ast/field-space/query-spaces.ts
In reading #1319 after I merged I found these two
stupid lines of code which I thought I should
have written better.
=> Cleanup something I missed in #1319

packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/test/query.spec.ts
=> source.turtle, -> is now a warning

packages/malloy/src/lang/grammar/MalloyLexer.g4, packages/malloy/src/lang/test/source.spec.ts
=>  view:  not view

packages/malloy-syntax-highlight/package.json, packages/malloy/src/malloy.ts, test/src/model/sql_source.spec.ts
=> wrap turducken inserts in () if non are given

packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/test/query.spec.ts
This experiment was run, and deemed incorrect.
Un does #1323
=> take out src.turtle

packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/test/source.spec.ts
=> Deprecate leading arrow in turtle defs or refs

packages/malloy/src/lang/ast/field-space/reference-field.ts, packages/malloy/src/lang/test/annotation.spec.ts, packages/malloy/src/lang/test/query.spec.ts
Fixes #1371
Any field reference which was a path would fail to be annotated properly.
=> fix annotated path references

packages/malloy-syntax-highlight/grammars/malloy-notebook/malloy-notebook-language.json, packages/malloy-syntax-highlight/grammars/malloy-sql/malloy-sql-language.json, packages/malloy-syntax-highlight/grammars/malloy/malloy-language.json
Fixes https://github.com/malloydata/malloy-vscode-extension/issues/263
=> Use -- to comment in Malloy, MalloySQL

cloudbuild/deploy/malloy-npm-release-publish.sh
Prevent failure when commits to main have happened since we started publishing.
=> Harden version bump

packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/test/expressions.spec.ts
Fixes https://github.com/malloydata/malloy/issues/1387
=> `count(distinct column)` should be a warning not an error

README.md
Previous had typo, went to 404.
=> Update Quickstart url in README.md

packages/malloy-render/src/html/link.ts
Reference document from `this`.
=> Fix link renderer in Colab

packages/malloy/src/malloy.ts
This allows us to show warnings related to a compiled query.
=> Add problem list to PreparedQuery.

cloudbuild/build-test/cloudbuild.yaml, cloudbuild/build-test/test.sh
=> Pass in PG variables rather than hard code

test/src/databases/postgres/postgres.spec.ts
See #1432 and #1433 ... workaround
=> Skip postgres case test on npm publish builds

packages/malloy/src/lang/ast/types/malloy-element.ts, packages/malloy/src/lang/doc/experimental.md, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/tags.ts
First pass at the framework of experimental feature support
=> Add support for experimental features

packages/malloy/src/dialect/postgres/postgres.ts, test/src/databases/postgres/postgres.spec.ts
And add some tests for numbers, including "DOUBLE PRECISION"
=> Fix types with spaces in Postgres

packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/test/source.spec.ts
=> join_many: .. with errors

packages/malloy/src/lang/ast/field-space/reference-field.ts, packages/malloy/src/lang/test/annotation.spec.ts, packages/malloy/src/model/malloy_types.ts
=> properly annotate references to joined measures

cloudbuild/build-test/cloudbuild.yaml, cloudbuild/deploy/cloudbuild.yaml, package-lock.json
```
% npm install @esbuild/darwin-x64
% git checkout package.json
% git add package-lock.json
% git commit -m"possible for for esbuild problem"
```
=> possible fix for esbuild problem

test/src/render/render.spec.ts
=> make render results work more consistently

packages/malloy-render/src/html/table.ts, packages/malloy/src/malloy.ts
Adds an api to ExploreField for checking whether this field returns a record or an array
=> feat: use API for determining if ExploreField is record

packages/malloy-db-postgres/src/postgres_connection.ts
Detect when we got zero rows back for schema, and throw an error. This prevents more confusing errors down the line, but we do not have a more specific error still.
=> Throw error when failing to fetch schema

package-lock.json, package.json
"resolutions" is a yarn thing, we're currently using npm. Fix axios audit warning.
=> Remove old resolutions, update axios

packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/malloy.ts, test/src/api.spec.ts
For the purpose of allowing cache invalidation when imported files change.
=> Expose TranslateResponseData.fromSources on Model

packages/malloy-db-bigquery/src/bigquery.spec.ts, packages/malloy-db-duckdb/src/duckdb.spec.ts
I fixed postgres, but didn't touch bigquery or duckdb before for some reason.
=> Fix flaky caching tests

packages/malloy-db-postgres/src/postgres_connection.ts
Try and figure out why postgres is timing out.
=> Remove unnecessary tweak

packages/malloy-render/src/drill.ts, packages/malloy/src/malloy.ts
Fixes:
1. New malloy query format.
2. Fix column value comparison operator
3. Fix for renamed column names
4. Multi-word column names
5. Fix Date type columns from being converted to DateTime
=> Fixes for drill filters

packages/malloy-render/src/component/table.ts
Adds right alignment for numeric fields in the new renderer
=> feat: number alignment

packages/malloy-render/src/drill.ts, packages/malloy-render/src/index.ts, packages/malloy/src/malloy.ts, test/src/render/drill.spec.ts
1. Fix column name for joined in tables.
2. Move select to down below.
=> fix drill for joined in tables.

packages/malloy-render/src/drill.ts, packages/malloy/src/malloy.ts, test/src/render/drill.spec.ts
fix source expression, format drill query
=> drill enhance 2

packages/malloy-db-postgres/src/postgres_connection.ts
Per discussion on Slack: https://malloy-community.slack.com/archives/C025JAK8G0N/p1702065262634369
=> Support Postgres connectionString parameter

packages/malloy-render/src/stories/bars.stories.ts, packages/malloy-render/src/stories/tables.stories.ts, packages/malloy-render/src/stories/themes.stories.ts
Fixing a minor vertical scroll issue with storybook
=> fix: storybook scroll height dependent on window

packages/malloy-db-duckdb/src/duckdb.spec.ts, packages/malloy-db-duckdb/src/duckdb_connection.ts
Use a single database per database path, and multiple connections on that database for different settings. Will allow the mechanism we use to track relative database path names in VS Code to work with on disk databases, once I merge the worker logic back into the language server.
=> Memoize DuckDB databases

packages/malloy/src/model/malloy_query.ts, test/src/databases/all/nomodel.spec.ts
=> count distinct in leafy nested queries

developing.md, packages/malloy/src/lang/ast/expressions/expr-minus.ts, packages/malloy/src/lang/ast/fragtype-utils.ts, test/src/databases/all/functions.spec.ts
Thought I would try my hand at fixing a small issue, any and all comments on the PR are definitely welcome (whether they be technical, aesthetic, best practices, etc.). Thanks!
(Also included small typo fix).
=> #1306 - Can't negate analytic value

packages/malloy/src/lang/doc/experimental.md
Fixes https://github.com/malloydata/malloy/issues/1591
=> Add to internal list of known experiments

packages/malloy/src/malloy.ts, test/src/databases/bigquery-postgres/streaming.spec.ts, test/src/databases/duckdb/streaming.spec.ts
Creates  CSV for Malloy Results where nested data is converted to CSV as well.
=> CSV writer for nested data

packages/malloy-db-duckdb/src/duckdb_connection.ts
=> Lowercase md token

cloudbuild/build-db/cloudbuild.yaml, cloudbuild/build-db/test-snowflake.sh, cloudbuild/build-test/test.sh, packages/malloy-db-snowflake/src/snowflake_connection.spec.ts, packages/malloy-db-snowflake/src/snowflake_connection.ts, packages/malloy-db-snowflake/src/snowflake_executor.spec.ts, packages/malloy-db-snowflake/src/snowflake_executor.ts, test/src/runtimes.ts
Add support for testing Snowflake in CI. Test in separate job because building with secrets means we can publish the result log, which would be a real hassle for the rest of Malloy.
=> Set up Snowflake CI environment

.github/workflows/db-bigquery.yaml, .github/workflows/db-motherduck.yaml, .github/workflows/db-postgres.yaml
Create a BigQuery test workflow. Move DB test workflows to PR only to reduce overhead.
=> Bigquery action

packages/malloy-db-trino/src/trino_connection.ts, packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/trino/trino.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/expr.spec.ts
Trino has integer math but the 1.0 trick doesn't work
=> Working on the Trino dialect

packages/malloy-db-trino/src/trino_connection.ts, packages/malloy/src/dialect/trino/trino.ts, test/src/databases/all/expr.spec.ts
=> More fixes for Trino.

packages/malloy-db-trino/src/trino_connection.spec.ts, packages/malloy-db-trino/src/trino_connection.ts
Handle arrays and structs, add a couple more types
=> Handle nested schemas

packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/trino/trino.ts, packages/malloy/src/model/malloy_query.ts
=> Trino: more bug fixes.

jest.config.ts, test/jest.setup.js, test/jest.setup.ts, test/src/databases/all/db_index.spec.ts, test/src/databases/all/expr.spec.ts, test/src/databases/all/join.spec.ts, test/src/databases/all/nomodel.spec.ts, test/src/databases/all/orderby.spec.ts, test/src/databases/all/time.spec.ts, test/src/render/render.spec.ts, test/src/util/index.ts, test/tsconfig.json, test/types/jest.d.ts
Extend `test()`/`it()` to have a `when()` method that can act as a conditional skip. Replaces `onlyIf()` helper.
=> Add test.when()

packages/malloy-db-trino/src/trino_connection.spec.ts, packages/malloy-db-trino/src/trino_connection.ts, packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/trino/functions/string_agg.ts, packages/malloy/src/dialect/trino/functions/trino_functions.ts, packages/malloy/src/dialect/trino/trino.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/expr.spec.ts, test/src/databases/all/functions.spec.ts, test/src/databases/all/nomodel.spec.ts
make nested table calculations work
=> TRINO: String_agg and other bugfixes

packages/malloy/src/model/malloy_query.ts, test/src/databases/all/nomodel.spec.ts, test/src/model/sql_source.spec.ts
Fixes (hopefully) https://github.com/malloydata/malloy/issues/1733
=> change all starting aliases to be 'base'

.github/workflows/db-motherduck.yaml, package-lock.json, packages/malloy-db-duckdb/package.json, packages/malloy-db-duckdb/src/duckdb_wasm_connection.ts
Update to duckdb 0.10.x where possible.
=> Update to duckdb 0.10.x

test/src/experimental-dialects.spec.ts
Fixes https://github.com/malloydata/malloy/issues/1744
=> Add test for experimental dialects

packages/malloy/src/dialect/trino/trino.ts, test/src/databases/all/nomodel.spec.ts
Doesn't seem to work with ga_sample data but works in many other cases, not sure why yet.
=> Simulate left join in Presto

package-lock.json, package.json
Result of running `npm audit fix` + updating to lerna 8.1.8 as recommended.
=> Audit fixes for 2024/08/05

packages/malloy/src/lang/ast/types/expression-def.ts, packages/malloy/src/lang/test/expressions.spec.ts, packages/malloy/src/lang/test/parameters.spec.ts, packages/malloy/src/lang/test/query.spec.ts
=> better error message for + typecheck

packages/malloy/src/lang/ast/source-elements/named-source.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/parameters.spec.ts
=> Fix issue #1816 with extending a source without providing a value for a default-valued parameter

packages/malloy-render/src/component/apply-renderer.tsx, packages/malloy-render/src/component/legacy-charts/legacy_chart.tsx, packages/malloy-render/src/component/plot/plot-to-vega.ts, packages/malloy-render/src/component/render-result-metadata.ts, packages/malloy-render/src/component/table/table.tsx, packages/malloy-render/src/component/types.ts, packages/malloy-render/src/component/util.ts, packages/malloy-render/src/html/vega_spec.ts, packages/malloy-render/src/stories/legacy-charts.stories.ts, packages/malloy-render/src/stories/static/legacy-charts.malloy, test/src/render/__snapshots__/render.spec.ts.snap
Forwarding chart renderers to legacy charts until we replace them
=> feat: next renderer can show legacy charts

packages/malloy-db-bigquery/src/bigquery_connection.ts, packages/malloy/src/connection/base_connection.ts, packages/malloy/src/connection/types.ts
And use BigQuery as a first use case. To be continued over in VS Code...
=> Add simple metadata methods

packages/malloy/src/malloy.ts
Part of fix for error fixes not propagating through cells.
=> Make noThrowOnError work with extend

packages/malloy-render/src/component/dashboard/dashboard.css, packages/malloy-render/src/component/render-list.tsx, packages/malloy-render/src/component/render-result-metadata.ts, packages/malloy-render/src/component/render.css, packages/malloy-render/src/component/table/table-context.ts, packages/malloy-render/src/component/table/table.css, packages/malloy-render/src/component/table/table.tsx, packages/malloy-render/src/component/types.ts, packages/malloy-render/src/stories/dashboard.stories.ts, packages/malloy-render/src/stories/static/dashboard.malloy, packages/malloy-render/src/stories/static/tables.malloy
- wraps text
- dynamically calculates wrapped header heights and applies them to all nested headers
- dynamically calculates sticky positions for nested content
- prevents dashboard items from overflowing in x direction
- adjust gap size strategy to have smaller gaps between normal columns, wider gaps around nested tables
=> feat: increase table density

packages/malloy/src/malloy.ts, test/src/api.spec.ts
=> Fix bug with resultExplore not having correct annotations attached when running a view

package-lock.json, packages/malloy-render/package.json, packages/malloy-render/src/component/table/table-context.ts, packages/malloy-render/src/component/table/table.css, packages/malloy-render/src/component/table/table.tsx, packages/malloy-render/src/stories/tables.stories.ts
Reverts malloydata/malloy#1855, introduced a bug in VSCode
=> Revert "feat: virtualize"

.github/workflows/prerelease.yaml, .github/workflows/release.yaml
Our snowflake instance is down, don't gate on it for releases.
=> Unblock on snowflake

.github/workflows/prerelease.yaml, .github/workflows/release.yaml
Reverts malloydata/malloy#1887
Snowflake is back.
=> Revert "Unblock on snowflake"

packages/malloy-render/src/component/table/table.css, packages/malloy-render/src/component/table/table.tsx
Fixes some bugs related to chart padding, pinned header overlays
=> fix: spacing, pinned bugs

.github/workflows/release.yaml
The bot needs to sign off its commits now.
=> Sign release commit

packages/malloy/src/lang/ast/types/expression-def.ts, packages/malloy/src/lang/test/expressions.spec.ts, packages/malloy/src/lang/test/parse-expects.ts
This got broken, and there were no tests to tell me.
Both should be fixed now.
=> Fix for STR !~ REGEXP

CHANGELOG.md, README.md, demo/malloy-demo-composer/README.md, packages/malloy-db-bigquery/src/bigquery.spec.ts, packages/malloy/src/lang/test/parse.spec.ts, test/src/databases/all/nomodel.spec.ts, test/src/databases/bigquery/double_truncation.spec.ts, test/src/databases/bigquery/handexpr.spec.ts, test/src/databases/bigquery/injestion_time_partitioning.spec.ts, test/src/databases/bigquery/joined_filters.spec.ts, test/src/databases/bigquery/malloy_query.spec.ts, test/src/databases/bigquery/performance.skipped.spec.ts, test/src/databases/bigquery/wildcard_table_names.spec.ts, test/src/databases/streaming/streaming.spec.ts, test/src/models/faa_model.ts, test/src/models/medicare_model.ts, test/src/render/render.spec.ts, test/src/runtimes.ts
Switch over from 'malloy-test' to 'malloydata-org' everywhere.
=> Normalize bq database

packages/malloy/src/lang/ast/source-query-elements/sq-reference.ts, packages/malloy/src/lang/ast/types/malloy-element.ts, packages/malloy/src/lang/parse-malloy.ts, packages/malloy/src/lang/test/test-translator.ts, packages/malloy/src/malloy.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts
more stuff which the refactor of composer revealed
=> isSourceDef accepts NamedModelObjects

package-lock.json, packages/malloy-db-duckdb/package.json
Update DuckDB in investigation of https://github.com/malloydata/malloy/issues/1983
=> DuckDB 1.1.1 and pals

package-lock.json, packages/malloy-db-snowflake/package.json, packages/malloy-db-snowflake/src/snowflake_executor.ts
Pull in https://github.com/malloydata/malloy/pull/1778 with tests
Step to address https://github.com/malloydata/malloy/issues/1984
=> [snowflake] upgrade snowflake package and fix breaking changes

packages/malloy/src/dialect/trino/dialect_functions.ts, test/src/databases/presto-trino/presto-trino.spec.ts
=> add Presto url functions

packages/malloy-db-duckdb/src/duckdb_common.ts, packages/malloy/src/dialect/duckdb/duckdb.ts, packages/malloy/src/dialect/tiny_parser.ts, test/src/databases/all/compound-atomic.spec.ts, test/src/databases/all/nomodel.spec.ts, test/src/databases/duckdb/duckdb.spec.ts
Compound object testing had holes in it, HT @whscullin for pointing this out.
=> Make schema reading work for nested arrays

packages/malloy/src/dialect/standardsql/dialect_functions.ts, packages/malloy/src/dialect/standardsql/standardsql.ts, test/src/databases/bigquery/malloy_query.spec.ts
Initial test, kickoff BQ tests
=> Added initial support for BQ HLL functions

.github/workflows/db-duckdb-wasm.yaml, .github/workflows/db-duckdb.yaml, .github/workflows/db-motherduck.yaml, .github/workflows/db-mysql.yaml, .github/workflows/db-postgres.yaml, .github/workflows/db-presto.yaml, .github/workflows/db-snowflake.yaml, .github/workflows/db-trino.yaml, .github/workflows/main.yaml
Reverts malloydata/malloy#2076
Forked PRs are still running tests without secrets...
=> Revert "Enable pull-request-target for github actions"

.github/workflows/prerelease.yaml, .github/workflows/release.yaml
main uses the bigquery secret now.
=> Update release secret usage

packages/malloy-db-trino/src/index.ts, packages/malloy-db-trino/src/trino_connection.ts
The meta internal presto connection needs access to the explain parser.
=> move explain parser to protected status

packages/malloy/src/lang/test/expressions.spec.ts
Explicitly tests the apply operator "?" and it's precedence when in a compound expression.  Verifies precedence order.
=> Added tests for apply operator within a series of conditionals

test/src/databases/all/nomodel.spec.ts, test/src/databases/duckdb/model_caching.spec.ts
Fix use of string templates and fix error when running tests other than duckdb.
=> Fix some test names

packages/malloy-db-trino/src/trino_connection.ts
=> Allow passing fields into unpackArray

package-lock.json, packages/malloy-render/package.json
Reverts malloydata/malloy#2130
=> Revert "Remove extraneous dep"

.github/workflows/prerelease.yaml, .github/workflows/release.yaml
=> Pull PACKAGES from package.json

packages/malloy/src/lang/syntax-errors/custom-error-messages.ts, packages/malloy/src/lang/syntax-errors/malloy-parser-error-listener.ts, packages/malloy/src/lang/test/syntax-errors.spec.ts
Create yet another pull request to try to get past the broken Pull Request testing workflow.
I temporarily disabled the broken workflow, but it looks like I need to create yet another pull request to avoid triggering it.
=> Another attempt to fix CI/CD [skip ci]

packages/malloy-filter/SAMPLES.md, packages/malloy-filter/SERIALIZE_SAMPLES.md, packages/malloy-filter/src/generate_samples.ts, packages/malloy-filter/src/string_parser.ts, packages/malloy-filter/src/string_serializer.ts
=> The parsers now flag invalid characters as errors.  Samples updated

packages/malloy-query-builder/src/query-ast.spec.ts, packages/malloy-query-builder/src/query-ast.ts
Suggested fields/methods is now much more sane.
=> Refactor as and find in query builder

packages/malloy/src/model/malloy_query.ts, test/src/databases/all/expr.spec.ts
=> having query with nest and no group by.

packages/malloy-filter/src/clause_utils.ts, packages/malloy-filter/src/filter_clause.ts, packages/malloy-filter/src/grammars/fexpr_number.ne, packages/malloy-filter/src/grammars/ftemporal.ne, packages/malloy-filter/src/number_filter_expression.ts, packages/malloy-filter/src/temporal_filter_expression.ts, packages/malloy-filter/src/test/fbool.spec.ts, packages/malloy-filter/src/test/fnumber.spec.ts, packages/malloy-filter/src/test/fstring.spec.ts, packages/malloy-filter/src/test/ftemporal.spec.ts, packages/malloy/src/dialect/dialect.ts, packages/malloy/src/dialect/postgres/postgres.ts, packages/malloy/src/lang/ast/expressions/expr-filter-expr.ts, packages/malloy/src/lang/test/filter-expressions.spec.ts, packages/malloy/src/model/filter_compilers.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/db_filter_expressions.spec.ts
Here's the next stage of filter expressions. Many basic numeric filters and temporal filters are working and passing tests.
=> Get numeric and boolean filter expressions working

.github/workflows/release.yaml, package-lock.json
Re-generate package-lock.json after lerna patches versions.
=> Work around lerna package-lock.json corruption

scripts/gen-flow.ts
Massage output of flow conversion to appease other tools.
=> Still more flow massaging.

packages/malloy-filter/src/test/fnumber.spec.ts, packages/malloy-filter/src/test/fstring.spec.ts, packages/malloy/src/lang/ast/expressions/expr-filter-expr.ts, packages/malloy/src/lang/parse-log.ts, packages/malloy/src/lang/test/filter-expressions.spec.ts, packages/malloy/src/model/filter_compilers.ts, packages/malloy/src/model/filter_temporal_compiler.ts, packages/malloy/src/model/malloy_query.ts, test/src/databases/all/db_filter_expressions.spec.ts
This is that last set of changes needed to reach MVP for filter expressions.
=> Continue to implement filter expressions

test/src/databases/all/db_filter_expressions.spec.ts
This reverts commit 779c14c98e64a88a3f4c69bbaf65a8a8ec80a515.
I think this was accidentally pushed to main.
=> Revert "maybe everything but mysql will pass?"

packages/malloy-render/package.json
Simplify package dependencies.
=> DuckDB only used by storybook

packages/malloy/src/lang/ast/query-properties/declare-fields.ts, packages/malloy/src/lang/grammar/MalloyLexer.g4, packages/malloy/src/lang/grammar/MalloyParser.g4, packages/malloy/src/lang/malloy-to-ast.ts, packages/malloy/src/lang/parse-tree-walkers/document-symbol-walker.ts, packages/malloy/src/lang/parse-tree-walkers/find-external-references.ts, packages/malloy/src/lang/parse-tree-walkers/find-table-path-walker.ts, packages/malloy/src/lang/test/document-help-context-walker.spec.ts, packages/malloy/src/lang/test/document-symbol-walker.spec.ts, packages/malloy/src/lang/test/parse.spec.ts, packages/malloy/src/lang/test/query.spec.ts, packages/malloy/src/lang/test/source.spec.ts
Last stage of the M4 transition, time to do it.
=> Remove support for M0 - M3

test/src/databases/all/compound-atomic.spec.ts
=> Add a test for a known bug which I am not fixing right now (literal record access)

packages/malloy/src/lang/syntax-errors/custom-error-messages.ts
also make matching slightly more efficient
=> document new error matcher property

packages/malloy-interfaces/src/to_malloy.ts, packages/malloy-interfaces/src/types.ts, packages/malloy-interfaces/thrift/malloy.thrift, packages/malloy-query-builder/src/query-ast.spec.ts, packages/malloy-query-builder/src/query-ast.ts, packages/malloy/src/lang/malloy-to-stable-query.ts
~Part one of of adding this to the query builder.~ Just pulling that thread all the way...
=> Add 'having' to known stable query types

packages/malloy-interfaces/src/types.ts, packages/malloy-interfaces/thrift/malloy.thrift
Update filtered field defintions.
=> Add 'having' to known stable query types, part 2

packages/malloy-query-builder/src/query-ast.ts
=> Allow segments with just nests to run

packages/malloy-query-builder/src/query-ast.spec.ts, packages/malloy-query-builder/src/query-ast.ts
e.g. group_by and where of fields in records
=> [Query Builder] Add support for operating on records and repeated records

test/src/databases/all/compound-atomic.spec.ts, test/src/util/db-matcher-support.ts
.. .and fix a todo while i was looking at it
=> tweak malloy matcher error output

.github/workflows/release.yaml
Test duckdb instead of motherduck for release
=> motherduck -> duckdb

packages/malloy/src/dialect/trino/dialect_functions.ts, test/src/databases/presto-trino/presto-trino.spec.ts
Not sure this is the right thing, need to talk to people a bit. but saving this work as a PR in case we decide this is the right thing.
=> Add array_agg to presto dialect functions

packages/malloy-render/src/component/bar-chart/generate-bar_chart-vega-spec.ts, packages/malloy-render/src/component/chart-layout-settings.ts, packages/malloy-render/src/component/chart/chart.css, packages/malloy-render/src/component/chart/chart.tsx, packages/malloy-render/src/component/line-chart/generate-line_chart-vega-spec.ts, packages/malloy-render/src/component/render.tsx, packages/malloy-render/src/component/vega/measure-axis.ts, packages/malloy-render/src/component/vega/vega-chart.tsx, packages/malloy-render/src/data_tree.ts, packages/malloy-render/src/plugins/line-chart-series-plugin.ts, packages/malloy-render/src/stories/bar_chart.stories.malloy, packages/malloy-render/src/stories/line_charts.stories.malloy
Starts initial set up of renderer plugins with line chart being first
Creates line chart top series approximations at global level
=> feat: line plugin with top series approximation

packages/malloy-render/src/component/bar-chart/generate-bar_chart-vega-spec.ts, packages/malloy-render/src/component/line-chart/generate-line_chart-vega-spec.ts, packages/malloy-render/src/plugins/line-chart-series-plugin.ts, packages/malloy-render/src/stories/bar_chart.stories.malloy, packages/malloy-render/src/stories/line_charts.stories.malloy
Adds stories and fixes for various combinations of null data in the bar chart and line charts
=> fix: chart nulls

packages/malloy-render/src/component/line-chart/generate-line_chart-vega-spec.ts, packages/malloy-render/src/stories/line_charts.stories.malloy
Reverts malloydata/malloy#2352
=> Revert "feat: line charts support null times"

packages/malloy-render/src/api/malloy-viz.tsx, packages/malloy-render/src/html/html_view.ts
Adds copy to legacy API, and fixes bug in MalloyViz copy method
=> feat: copy html from legacy api

package-lock.json, packages/malloy-render/package.json, packages/malloy-render/vite.config.base.mts, packages/malloy-render/vite.config.mts
Switch to using vite plugins to fix up path aliases, generate type files.
=> fix: renderer type output

packages/malloy-render/src/component/bar-chart/generate-bar_chart-vega-spec.ts, packages/malloy-render/src/component/render-time.ts, packages/malloy-render/src/component/render.tsx, packages/malloy-render/src/component/vega/vega-expr-addons.ts, packages/malloy-render/src/data_tree/fields/atomic.ts, packages/malloy-render/src/plugins/bar-chart/generate-bar_chart-vega-spec.ts, packages/malloy-render/src/plugins/line-chart/generate-line_chart-vega-spec.ts, packages/malloy-render/src/plugins/line-chart/get-line_chart-settings.ts, packages/malloy-render/src/plugins/line-chart/line-chart-plugin.tsx, packages/malloy-render/src/plugins/line-chart/line-chart-settings.ts, packages/malloy-render/src/stories/line_charts.stories.malloy, packages/malloy-render/src/util.ts
=> feat: line yoy mode

packages/malloy-render/src/data_tree/fields/base.ts, packages/malloy-render/src/drill.spec.ts, packages/malloy/src/model/malloy_query.ts, packages/malloy/src/model/malloy_types.ts, packages/malloy/src/to_stable.ts
Reverts malloydata/malloy#2409
=> Revert "Fix drill on join field reference"

packages/malloy-render/src/api/plugin-types.ts, packages/malloy-render/src/component/chart/chart-layout-settings.ts, packages/malloy-render/src/component/render-result-metadata.ts, packages/malloy-render/src/component/render.css, packages/malloy-render/src/component/render.tsx, packages/malloy-render/src/component/util.ts, packages/malloy-render/src/plugins/bar-chart/bar-chart-plugin.tsx, packages/malloy-render/src/plugins/bar-chart/generate-bar_chart-vega-spec.ts, packages/malloy-render/src/plugins/line-chart/generate-line_chart-vega-spec.ts, packages/malloy-render/src/plugins/line-chart/line-chart-plugin.tsx, packages/malloy-render/src/stories/scroll-override.stories.ts, packages/malloy-render/src/stories/vega-config-override.stories.ts
- chart background color inherited from vega config
- font measurements based on vega config
- y axis sizing
=> feat: vega config override improvements

packages/malloy/src/dialect/postgres/postgres.ts, packages/malloy/src/model/filter_compilers.ts
=> deal with EXTRACT returning double in pg < 14

packages/malloy-filter/src/clause_utils.ts, packages/malloy-filter/src/test/ftemporal.spec.ts, packages/malloy/src/model/filter_compilers.ts, test/src/databases/all/db_filter_expressions.spec.ts
Excellent bug report ( #2458 ) resulted in a review of filter expressions and a number of problems have been fixed. There were missing tests, and in most cases, where there was a missing test, the genrated code was also incorrect.
=> Fix many problems with filter expressions

packages/malloy/src/model/expression_compiler.ts, packages/malloy/src/model/filter_compilers.ts, test/src/databases/all/db_filter_expressions.spec.ts
=> filter expressions respect query time zone

packages/malloy/src/lang/malloy-to-stable-query.ts, packages/malloy/src/lang/test/malloy-to-stable-query.spec.ts
originally submitted by @aszenz in #2508
Fixes the function malloyToQuery, originally created in https://github.com/malloydata/malloy/pull/2181
=> correctly collect run: annotations
